# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar/qt-designer/exam_wizard.ui'
#
# Created: Sat Apr 11 11:53:02 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(332, 320)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.examA_radioButton = QtGui.QRadioButton(Dialog)
        self.examA_radioButton.setChecked(True)
        self.examA_radioButton.setObjectName("examA_radioButton")
        self.verticalLayout.addWidget(self.examA_radioButton)
        self.examB_radioButton = QtGui.QRadioButton(Dialog)
        self.examB_radioButton.setObjectName("examB_radioButton")
        self.verticalLayout.addWidget(self.examB_radioButton)
        self.examC_radioButton = QtGui.QRadioButton(Dialog)
        self.examC_radioButton.setObjectName("examC_radioButton")
        self.verticalLayout.addWidget(self.examC_radioButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 2, 3)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 3, 2, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dateEdit = QtGui.QDateEdit(Dialog)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_3.addWidget(self.dateEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 4, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dents_comboBox = QtGui.QComboBox(Dialog)
        self.dents_comboBox.setObjectName("dents_comboBox")
        self.verticalLayout_2.addWidget(self.dents_comboBox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 4, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 5)
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 5)
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 4, 0, 1, 1)
        self.co_comboBox = QtGui.QComboBox(Dialog)
        self.co_comboBox.setObjectName("co_comboBox")
        self.co_comboBox.addItem(QtCore.QString())
        self.co_comboBox.addItem(QtCore.QString())
        self.co_comboBox.addItem(QtCore.QString())
        self.co_comboBox.addItem(QtCore.QString())
        self.co_comboBox.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.co_comboBox, 4, 1, 1, 4)
        self.softTissues_checkBox = QtGui.QCheckBox(Dialog)
        self.softTissues_checkBox.setObjectName("softTissues_checkBox")
        self.gridLayout_2.addWidget(self.softTissues_checkBox, 5, 0, 1, 5)
        self.oh_checkBox = QtGui.QCheckBox(Dialog)
        self.oh_checkBox.setObjectName("oh_checkBox")
        self.gridLayout_2.addWidget(self.oh_checkBox, 6, 0, 1, 5)
        self.canines_checkBox = QtGui.QCheckBox(Dialog)
        self.canines_checkBox.setObjectName("canines_checkBox")
        self.gridLayout_2.addWidget(self.canines_checkBox, 7, 0, 1, 5)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 8, 0, 1, 5)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Exam Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.examA_radioButton.setText(QtGui.QApplication.translate("Dialog", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.examB_radioButton.setText(QtGui.QApplication.translate("Dialog", "Extensive", None, QtGui.QApplication.UnicodeUTF8))
        self.examC_radioButton.setText(QtGui.QApplication.translate("Dialog", "Full Case Assessment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Exam Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Dentist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Pt c/o", None, QtGui.QApplication.UnicodeUTF8))
        self.co_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "nil", None, QtGui.QApplication.UnicodeUTF8))
        self.co_comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Broken Tooth", None, QtGui.QApplication.UnicodeUTF8))
        self.co_comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "Pain", None, QtGui.QApplication.UnicodeUTF8))
        self.co_comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "Denture Problems", None, QtGui.QApplication.UnicodeUTF8))
        self.co_comboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "Sensitive Teeth", None, QtGui.QApplication.UnicodeUTF8))
        self.softTissues_checkBox.setText(QtGui.QApplication.translate("Dialog", "Soft Tissues Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.oh_checkBox.setText(QtGui.QApplication.translate("Dialog", "OHI given", None, QtGui.QApplication.UnicodeUTF8))
        self.canines_checkBox.setText(QtGui.QApplication.translate("Dialog", "Palpated for upper canines - NAD", None, QtGui.QApplication.UnicodeUTF8))

