#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'openmolar',
 'build_date': '2009-06-16 16:14:59 +0100',
 'clean': None,
 'date': '2009-06-16 15:07:27 +0100',
 'revision_id': 'rowinggolfer@googlemail.com-20090616140727-csk2ntf0ebcvghzm',
 'revno': 161}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
