#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'openmolar',
 'build_date': '2009-05-31 02:26:03 +0100',
 'clean': None,
 'date': '2009-05-31 02:25:50 +0100',
 'revision_id': 'rowinggolfer@googlemail.com-20090531012550-ydoa5tus5g6q7dh2',
 'revno': 112}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
