DRUGLIST = [
     '50:50 Ointment',
     'Abacavir Sulphate',
     'Abatacept',
     'Abciximab',
     'Abelcet',
     'Abidec Multivitamin Drops',
     'Abilify',
     'Acamprosate Calcium',
     'Acarbose',
     'Accolate',
     'Accupro',
     'Accuretic',
     'Acea',
     'Acebutolol',
     'Acebutolol Hydrochloride',
     'Aceclofenac',
     'Acemetacin',
     'Acenocoumarol',
     'Acepril',
     'Acetazolamide',
     'Acetic Acid Cough Linctus',
     'Acetylcholine Chloride',
     'Acetylcysteine',
     'Acezide',
     'Aciclovir',
     'Aciclovir Sodium',
     'Acipimox',
     'Acitretin',
     'Aclasta',
     'Acnamino',
     'Acnecide Gel',
     'Acnecide Wash',
     'Acnisal',
     'Acnocin',
     'Acrivastine',
     'Actifed',
     'Actilyse',
     'Activated Charcoal/Magnesium Hydroxide',
     'Actonel',
     'Actonel Combi',
     'Actonorm Gel',
     'Actos',
     'Actrapid',
     'Acular',
     'Acwy Vax',
     'Adalat',
     'Adalimumab',
     'Adapalene',
     'Adartrel',
     'Adcal',
     'Adcal D3',
     'Adcortyl',
     'Adefovir Dipivoxil',
     'Adenocor',
     'Adenosine',
     'Adenuric',
     'Adipine',
     'Adizem',
     'Adrenaline',
     'Adrenaline Acid Tartrate',
     'Advagraf',
     'Aerobec',
     'Afinitor',
     'Aggrastat',
     'Agomelatine',
     'Agrippal',
     'Aknemycin Plus',
     'Aldactide',
     'Aldactone',
     'Aldara',
     'Aldesleukin',
     'Aldioxa/Chloroxylenol',
     'Alemtuzumab',
     'Alendronate Sodium',
     'Alendronate Sodium/Colecalciferol',
     'Alfacalcidol',
     'Alfentanil Hydrochloride',
     'Alfuzosin Hydrochloride',
     'Alimemazine Tartrate',
     'Alimta',
     'Aliskiren',
     'Alitretinoin',
     'Alkeran Injection',
     'Alkeran Tablets',
     'Allantoin/Coal Tar Extract/Hydrocortisone',
     'Allantoin/Lidocaine',
     'Allegron',
     'Allopurinol',
     'Almogran',
     'Almond Oil/Arachis Oil/Camphor',
     'Almotriptan Hydrogen Malate',
     'Alomide',
     'Alphaderm',
     'Alphagan',
     'Alphanine',
     'Alphosyl Hc',
     'Alprazolam',
     'Alprostadil',
     'Altacite Plus',
     'Altargo',
     'Alteplase',
     'Alu-Cap Capsules',
     'Aluminium Hydroxide',
     'Aluminium Sulphate',
     'Alverine',
     'Amantadine Hydrochloride',
     'Amaryl',
     'Ambirix',
     'Ambisome',
     'Ambrisentan',
     'Amias',
     'Amikacin Sulphate',
     'Amikin',
     'Amilamont',
     'Amiloride',
     'Amiloride Hydrochloride',
     'Amiloride/Furosemide',
     'Amiloride/Hydrochlorothiazide',
     'Aminophylline',
     'Amiodarone',
     'Amiodarone Hydrochloride',
     'Amisulpride',
     'Amitriptyline',
     'Amlodipine',
     'Amlodipine Besilate/Valsartan',
     'Amlostin',
     'Ammonia',
     'Ammonia/Eucalyptus',
     'Amorolfine Hydrochloride',
     'Amoxicillin',
     'Amoxil',
     'Amoxil Injection',
     'Amphocil',
     'Amphotericin',
     'Amphotericin Phospholipid Complex',
     'Ampicillin',
     'Ampicillin Sodium/Flucloxacillin Sodium',
     'Amsacrine',
     'Amsidine',
     'Amylase/Lipase/Protease',
     'Anabact',
     'Anacal Rectal Ointment',
     'Anadin Extra Soluble Tablets',
     'Anadin Extra Tablets',
     'Anadin Ibuprofen',
     'Anadin Original',
     'Anadin Paracetamol',
     'Anafranil',
     'Anapen',
     'Anastrozole',
     'Ancotil',
     'Anectine',
     'Anexate',
     'Angeliq',
     'Angettes',
     'Angiox',
     'Angitil',
     'Anidulafungin',
     'Anise Oil/Menthol/Capsicum Tincture',
     'Antabuse',
     'Antazoline/Xylometazoline',
     'Antepsin',
     'Anthisan',
     'Anthisan Bite And Sting Cream',
     'Anugesic-Hc Cream',
     'Anugesic-Hc Suppository',
     'Anusol Cream',
     'Anusol Ointment',
     'Anusol Plus Hc',
     'Anusol Suppositories',
     'Apidra',
     'Apo-Go',
     'Apomorphine Hydrochloride',
     'Apraclonidine Hydrochloride',
     'Aprepitant',
     'Apresoline',
     'Aprinox',
     'Aprovel',
     'Aptivus',
     'Aquadrate',
     'Aranesp',
     'Arava',
     'Arcoxia',
     'Aredia',
     'Argipressin',
     'Aricept',
     'Arimidex',
     'Aripiprazole',
     'Arixtra',
     'Aromasin',
     'Arpicolin',
     'Arsenic Trioxide',
     'Artelac',
     'Artemether/Lumefantrine',
     'Arthrotec',
     'Arythmol',
     'Arzerra',
     'Asacol',
     'Asasantin',
     'Ascorbic Acid/Amylmetacresol/Dichlorobenzyl Alcohol',
     'Ascorbic Acid/Phenylephrine/Paracetamol',
     'Asmabec',
     'Asmanex',
     'Asmasal',
     'Aspirin',
     'Aspirin/Dipyridamole',
     'Aspirin/Paracetamol Dispersible Tablets',
     'Aspro Clear',
     'Atarax',
     'Atazanavir Sulphate',
     'Atenolol',
     'Atenolol/Chlortalidone',
     'Atenolol/Nifedipine',
     'Ativan',
     'Atorvastatin',
     'Atosiban Acetate',
     'Atovaquone/Proguanil Hydrochloride',
     'Atracurium Besilate',
     'Atriance',
     'Atripla',
     'Atropine',
     'Atropine Sulphate',
     'Atrovent',
     'Augmentin',
     'Augmentin Intravenous',
     'Augmentin-Duo',
     'Avamys',
     'Avastin',
     'Avaxim',
     'Avelox',
     'Avloclor',
     'Avodart',
     'Avonex',
     'Axid',
     'Axsain',
     'Azactam',
     'Azathioprine',
     'Azelaic Acid',
     'Azelastine Hydrochloride',
     'Azilect',
     'Azithromycin',
     'Azithromycin Dihydrate',
     'Azopt',
     'Aztreonam',
     'Baby Meltus Cough Linctus',
     'Baclofen',
     'Bactroban',
     'Balneum Bath Oil',
     'Balneum Plus Bath Oil',
     'Balneum Plus Cream',
     'Balsalazide Disodium',
     'Bambec',
     'Bambuterol',
     'Baraclude',
     'Baratol',
     'Basiliximab',
     'Baxan',
     'Bazetham',
     'Bazuka',
     'Bcg (Connaught Strain)',
     'Bcg (Tice Strain)',
     'Beclazone',
     'Beclometasone Dipropionate',
     'Becodisks',
     'Beconase',
     'Bedranol',
     'Beechams',
     'Begrivac',
     'Belimumab',
     'Bemiparin',
     'Bemiparin Sodium',
     'Benadryl',
     'Benadryl Skin Allergy Relief Cream',
     'Bendroflumethiazide',
     'Benefix',
     'Benlysta',
     'Benylin',
     'Benzalkonium Chloride',
     'Benzocaine 1% Spray',
     'Benzoyl Peroxide',
     'Benzydamine Cream',
     'Benzydamine Mouthwash',
     'Benzydamine Oral Spray',
     'Benzylpenicillin Sodium',
     'Beta-Adalat',
     'Beta-Cardone',
     'Beta-Prograne',
     'Betacap',
     'Betadine Dry Powder Spray',
     'Betaferon',
     'Betagan',
     'Betahistine Dihydrochloride',
     'Betaloc',
     'Betamethasone Dipropionate',
     'Betamethasone Valerate',
     'Betaxolol Hydrochloride',
     'Bethanechol Chloride',
     'Betim',
     'Betnovate',
     'Betoptic',
     'Bettamousse',
     'Bevacizumab',
     'Bexarotene',
     'Bezafibrate',
     'Bezalip',
     'Bi-Carzem',
     'Bicalutamide',
     'Bicnu',
     'Bimatoprost',
     'Binovum',
     'Biorphen',
     'Bisacodyl Suppositories',
     'Bisacodyl Tablets',
     'Bismuth Subsalicylate',
     'Bisodol Indigestion Relief Tablets',
     'Bisoprolol Fumarate',
     'Bivalirudin',
     'Bleo-Kyowa',
     'Bleomycin Sulphate',
     'Blistex Relief Cream',
     'Bondronat',
     'Bonefos',
     'Bonjela',
     'Bonviva',
     'Bortezomib',
     'Bosentan',
     'Botox',
     'Brevinor',
     'Brevoxyl Cream',
     'Bricanyl',
     'Bridion',
     'Brilique',
     'Brimonidine Tartrate',
     'Brinzolamide',
     'Brochlor',
     'Broflex',
     'Bromocriptine Mesilate',
     'Brufen',
     'Buccastem',
     'Budesonide',
     'Bumetanide',
     'Bupivacaine Hydrochloride',
     'Bupropion Hydrochloride',
     'Burinex',
     'Burneze Spray',
     'Buscopan',
     'Buserelin Acetate',
     'Busilvex',
     'Buspar',
     'Buspirone',
     'Busulfan',
     'Buttercup Max Strength Sore Throat Lozenge',
     'Buttercup Syrup',
     'Bydureon',
     'Byetta',
     'Cabaser',
     'Cabergoline',
     'Cabren',
     'Cacit',
     'Caelyx',
     'Calaband',
     'Calceos',
     'Calchan',
     'Calcicard',
     'Calcichew',
     'Calcijex',
     'Calcipotriol',
     'Calcitonin (Salmon)',
     'Calcitriol',
     'Calcium Acetate',
     'Calcium Carbonate Antacids',
     'Calcium Carbonate Supplements',
     'Calcium Folinate',
     'Calcium Lactate',
     'Calcium Levofolinate',
     'Calcium Phosphate/Colecalciferol',
     'Calcium-Sandoz Syrup',
     'Calcold Six Plus',
     'Calcort',
     'Calfovit D3',
     'Calmurid Hc',
     'Calpol',
     'Calprofen',
     'Camcolit',
     'Campto',
     'Cancidas',
     'Candesartan',
     'Canesten',
     'Canusal',
     'Capecitabine',
     'Capoten',
     'Capozide',
     'Capreomycin Sulphate',
     'Caprin',
     'Capsaicin',
     'Captopril',
     'Captopril/Hydrochlorothiazide',
     'Carace Plus',
     'Caramet',
     'Carbamazepine',
     'Carbetocin',
     'Carbidopa Monohydrate/Levodopa',
     'Carbidopa/Entacapone/Levodopa',
     'Carbimazole',
     'Carbo-Dome Cream',
     'Carbocisteine',
     'Carbomer',
     'Carbomer Eye Drops',
     'Carboplatin',
     'Carboprost Trometamol',
     'Cardene',
     'Cardicor',
     'Cardioplen',
     'Cardioxane',
     'Cardura',
     'Carmellose Sodium',
     'Carmustine',
     'Casodex',
     'Caspofungin Acetate',
     'Catapres',
     'Caverject',
     'Cayston',
     'Ceanel',
     'Cedocard',
     'Cefaclor Monohydrate',
     'Cefadroxil Monohydrate',
     'Cefalexin',
     'Cefixime',
     'Cefotaxime Sodium',
     'Cefpodoxime Proxetil',
     'Ceftazidime Pentahydrate',
     'Ceftriaxone Sodium',
     'Cefuroxime Axetil',
     'Cefuroxime Sodium',
     'Celance',
     'Celebrex',
     'Celecoxib',
     'Celectol',
     'Celevac Tablets',
     'Celiprolol',
     'Celiprolol Hydrochloride',
     'Cellcept',
     'Cellcept Powder',
     'Celluvisc',
     'Celsentri',
     'Ceplene',
     'Ceporex',
     'Cerazette',
     'Certolizumab Pegol',
     'Cervarix',
     'Cetirizine Liquid',
     'Cetirizine Tablets',
     'Cetraben Bath Additive',
     'Cetraben Emollient Cream',
     'Cetrimide',
     'Cetrimide/Benzalkonium Chloride',
     'Cetrorelix Acetate',
     'Cetrotide',
     'Cetuximab',
     'Cetylpyridinium Chloride Lozenges',
     'Cetylpyridinium Chloride/Menthol',
     'Champix',
     'Chemydur',
     'Chirocaine',
     'Chlorambucil',
     'Chloramphenicol',
     'Chloramphenicol Sodium Succinate',
     'Chlordiazepoxide',
     'Chlordiazepoxide Hydrochloride',
     'Chlorobutanol/Arachis Oil',
     'Chlorobutanol/Lidocaine/Alcloxa/Cetrimide',
     'Chlorocresol/Urea/Cetrimide/Dimeticone',
     'Chloromycetin',
     'Chloroquine',
     'Chloroxylenol',
     'Chlorphenamine Maleate',
     'Chlorpromazine Hydrochloride',
     'Chlortalidone',
     'Cholestagel',
     'Choline Salicylate',
     'Choragon',
     'Choriogonadotropin Alfa',
     'Chorionic Gonadotrophin Human',
     'Cialis',
     'Cibral',
     'Cicafem',
     'Ciclesonide',
     'Ciclosporin',
     'Cidofovir',
     'Cilastatin Sodium/Imipenem Monohydrate',
     'Cilazapril',
     'Cilest',
     'Cilostazol',
     'Cimetidine',
     'Cimzia',
     'Cinacalcet Hydrochloride',
     'Cinchocaine',
     'Cinnarizine',
     'Cipralex',
     'Cipramil',
     'Cipramil Drops',
     'Ciprofibrate',
     'Ciprofloxacin',
     'Ciprofloxacin Hydrochloride',
     'Ciprofloxacin Lactate',
     'Ciproxin Injection',
     'Ciproxin Suspension',
     'Ciproxin Tablets',
     'Circadin',
     'Cisatracurium Besilate',
     'Cisplatin',
     'Citalopram Hydrobromide',
     'Citalopram Hydrochloride',
     'Citanest',
     'Citric Acid/Ipecacuanha',
     'Cladribine',
     'Claforan',
     'Clairette',
     'Clarelux',
     'Clarie Xl',
     'Clarithromycin',
     'Clemastine',
     'Clenil Modulite',
     'Clexane',
     'Climagest',
     'Climaval',
     'Climesse',
     'Clindamycin Hydrochloride',
     'Clindamycin Phosphate',
     'Clioquinol/Flumetasone Pivalate',
     'Clobazam',
     'Clobetasol Propionate',
     'Clobetasone Butyrate',
     'Clofarabine',
     'Clomethiazole',
     'Clomid',
     'Clomifene Citrate',
     'Clomipramine',
     'Clonazepam',
     'Clonidine',
     'Clopamide/Pindolol',
     'Clopidogrel',
     'Clopixol Acuphase',
     'Clopixol Conc',
     'Clopixol Tablets',
     'Clotam',
     'Clotrimazole',
     'Clozapine',
     'Clozaril',
     'Co-Beneldopa',
     'Co-Careldopa',
     'Co-Danthramer',
     'Co-Diovan',
     'Co-Fluampicil',
     'Co-Magaldrox',
     'Co-Simalcite',
     'Co-Trimoxazole',
     'Co-Zidocapt',
     'Coaprovel',
     'Cobalin-H',
     'Codeine/Paracetamol',
     'Colazide',
     'Colchicine',
     'Colecalciferol/Calcium Carbonate',
     'Colesevelam Hydrochloride',
     'Colestid',
     'Colestipol',
     'Colestipol Hydrochloride',
     'Colestyramine Anhydrous',
     'Colifoam',
     'Colistimethate Sodium',
     'Colistin Sulphate',
     'Colofac',
     'Colomycin',
     'Colomycin Injection',
     'Colomycin Syrup',
     'Colomycin Tablet',
     'Colpermin Ibs Relief Capsules',
     'Combigan',
     'Combivent',
     'Combivir',
     'Combodart',
     'Competact',
     'Compound W',
     'Comtess',
     'Concerta Xl',
     'Condyline',
     'Conjugated Oestrogens',
     'Copaxone',
     'Copegus',
     'Coracten',
     'Cordarone X',
     'Cordilox',
     'Corgard',
     'Corifollitropin Alfa',
     'Cortisone Acetate',
     'Cosmofer',
     'Cosopt',
     'Coversyl Arginine',
     'Coversyl Arginine Plus',
     'Cozaar',
     'Cozaar-Comp',
     'Cream Of Magnesia Tablets',
     'Creon',
     'Crestor',
     'Crinone',
     'Cromogen',
     'Crotamiton',
     'Cubicin',
     'Cuprofen',
     'Cuprofen Plus',
     'Cutivate',
     'Cyanocobalamin',
     'Cyclizine Lactate',
     'Cyclo-Progynova 2Mg',
     'Cyclopentolate Hydrochloride',
     'Cyclophosphamide Monohydrate',
     'Cycloserine',
     'Cyklokapron',
     'Cymalon',
     'Cymbalta',
     'Cymevene',
     'Cymex Cream',
     'Cyproheptadine',
     'Cyprostat',
     'Cyproterone Acetate',
     'Cyproterone Acetate/Ethinylestradiol',
     'Cystrin',
     'Cytamen',
     'Cytarabine',
     'Cytotec',
     'D-Gam',
     'Dabigatran Etexilate Mesilate',
     'Dacarbazine Citrate',
     'Daktacort',
     'Daktarin Oral Gel',
     'Dalacin',
     'Dalacin C',
     'Dalmane',
     'Dalteparin',
     'Danaparoid',
     'Danazol',
     'Dandrazol',
     'Danol',
     'Dantrium',
     'Dantrolene Sodium',
     'Daptomycin',
     'Daraprim',
     'Darbepoetin Alfa',
     'Darifenacin Hydrobromide',
     'Darunavir Ethanolate',
     'Dasatinib',
     'Daunorubicin Hydrochloride Citrate',
     'Daunoxome',
     'Daxas',
     'Day Nurse',
     'Day Nurse Capsules',
     'Ddavp',
     'Deca-Durabolin',
     'Decapeptyl',
     'Defanac',
     'Deferasirox',
     'Deferiprone',
     'Deflazacort',
     'Deltacortril',
     'Deltastab',
     'Demeclocycline Hydrochloride',
     'Denosumab',
     'Denzapine',
     'Depakote',
     'Depixol',
     'Depixol Tablets',
     'Depo-Medrone',
     'Depo-Medrone With Lidocaine',
     'Depo-Provera',
     'Depocyte',
     'Dequacaine',
     'Dequadin',
     'Dequalinium',
     'Derbac M',
     'Dermalo Bath Emollient',
     'Dermamist',
     'Dermax',
     'Dermidex',
     'Dermovate',
     'Deseril',
     'Desferal',
     'Desferrioxamine Mesilate',
     'Desloratadine',
     'Desmomelt',
     'Desmopressin Acetate',
     'Desmospray',
     'Desmotabs',
     'Desogestrel',
     'Destolit',
     'Detrunorm',
     'Detrusitol',
     'Dexamethasone',
     'Dexibuprofen',
     'Dexketoprofen Trometamol',
     'Dexomon',
     'Dexrazoxane',
     'Dexsol',
     'Dextromethorphan',
     'Dextromethorphan/Menthol',
     'Dextromethorphan/Pseudoephedrine',
     'Dhc Continus',
     'Diamicron',
     'Diamorphine',
     'Diamox',
     'Dianette',
     'Diazemuls',
     'Diazepam',
     'Dichlorobenzyl Alcohol/Amylmetacresol',
     'Diclofenac Diethylammonium',
     'Diclofenac Epolamine',
     'Diclofenac Potassium',
     'Diclofenac Sodium',
     'Diclofenac Sodium/Misoprostol',
     'Dicloflex',
     'Diclomax',
     'Dicycloverine Hydrochloride',
     'Dicynene',
     'Didanosine',
     'Didronel',
     'Didronel Pmo',
     'Diethylamine Salicylate',
     'Differin',
     'Difflam Cream',
     'Difflam Solution',
     'Difflam Spray',
     'Diflucan',
     'Digoxin',
     'Dihydrocodeine Tartrate',
     'Dilcardia',
     'Dill Oil/Sodium Bicarbonate/Ginger',
     'Diloxanide Furoate',
     'Diltiazem',
     'Diltiazem Hydrochloride',
     'Dilzem',
     'Dimeticone',
     'Dinoprostone',
     'Diocalm',
     'Dioctyl',
     'Dioderm',
     'Dioralyte',
     'Dioralyte Relief',
     'Diovan',
     'Dipentum',
     'Diphenhydramine',
     'Dipivefrine Hydrochloride',
     'Diprivan',
     'Diprobase Cream',
     'Diprobase Ointment',
     'Diprobath',
     'Diprosalic',
     'Diprosone',
     'Dipyridamole',
     'Disipal',
     'Disodium Etidronate',
     'Disodium Folinate',
     'Disodium Pamidronate',
     'Disopyramide',
     'Disopyramide Phosphate',
     'Disprin',
     'Disprin Extra',
     'Distaclor',
     'Distamine',
     'Distigmine Bromide',
     'Distilled Witch Hazel',
     'Disulfiram',
     'Dithranol',
     'Dithrocream',
     'Ditropan',
     'Diurexan',
     'Dixarit',
     'Do-Do Chesteze',
     'Dobutamine Hydrochloride',
     'Docetaxel',
     'Docusate',
     'Docusate Gel Enema',
     'Docusate Sodium Ear Drops',
     'Dolmatil',
     'Domperidone',
     'Domperidone Maleate',
     'Dopamine',
     'Dopamine Hydrochloride',
     'Dopexamine',
     'Doralese Tiltab',
     'Doribax',
     'Doripenem Monohydrate',
     'Dornase Alfa',
     'Dorzolamide Hydrochloride',
     'Dorzolamide Hydrochloride/Timolol Maleate',
     'Doublebase Bath Additive',
     'Doublebase Gel',
     'Doublebase Shower Gel',
     'Doublebase Wash Gel',
     'Dovobet',
     'Dovonex',
     'Dovonex Cream',
     'Doxadura',
     'Doxazosin',
     'Doxazosin Mesilate',
     'Doxorubicin Hydrochloride',
     'Doxorubin',
     'Doxycycline Hyclate',
     'Doxycycline Monohydrate',
     'Doxylamine/Pseudoephedrine/Dextromethorphan/Paracetamol',
     'Doxylar',
     'Dozic',
     'Drapolene Cream',
     'Dromadol',
     'Dronedarone Hydrochloride',
     'Drospirenone/Estradiol Hemihydrate',
     'Drospirenone/Ethinylestradiol',
     'Drotrecogin Alfa',
     'Droxia',
     'Duac',
     'Dukoral',
     'Dulcobalance',
     'Dulcoease',
     'Dulcolax Suppositories',
     'Dulcolax Tablets',
     'Duloxetine',
     'Duloxetine Hydrochloride',
     'Duodopa',
     'Duofilm',
     'Duotrav',
     'Duovent',
     'Dutasteride',
     'Dydrogesterone/Estradiol',
     'Dysport',
     'E45 Cream',
     'E45 Itch Relief Cream',
     'Earex Ear Drops',
     'Earex Plus',
     'Easyhaler Beclometasone',
     'Easyhaler Budesonide',
     'Easyhaler Formoterol',
     'Easyhaler Salbutamol',
     'Ebixa',
     'Ecalta',
     'Eccoxolac',
     'Econac',
     'Econazole Nitrate',
     'Ecopace',
     'Eczmol',
     'Edronax',
     'Edrophonium Chloride',
     'Efavirenz',
     'Efcortesol',
     'Efexor',
     'Efient',
     'Eflornithine Monohydrate Chloride',
     'Efudix',
     'Eldepryl',
     'Electrolade',
     'Eletriptan Hydrobromide',
     'Elidel',
     'Ellaone',
     'Elleste Solo',
     'Ellimans Universal Muscle Rub Lotion',
     'Elocon',
     'Elonva',
     'Eloxatin',
     'Eludril Mouthwash',
     'Eludril Spray',
     'Emadine',
     'Emcor',
     'Emedastine Difumarate',
     'Emend',
     'Emeside',
     'Emflex',
     'Emla',
     'Emselex',
     'Emtricitabine',
     'Emtricitabine/Tenofovir Disoproxil Fumarate',
     'Emtriva',
     'Emulsiderm Emollient',
     'Enalapril',
     'Enalapril/Hydrochlorothiazide',
     'Enbrel',
     'Endoxana',
     'Enfuvirtide',
     'Engerix B',
     'Eno',
     'Enoxaparin',
     'Enoxaparin Sodium',
     'Entacapone',
     'Entecavir Monohydrate',
     'Entocort',
     'Enzira',
     'Epanutin Capsules',
     'Epanutin Infatabs',
     'Epanutin Ready Mixed Parenteral',
     'Epanutin Suspension',
     'Epaxal',
     'Ephedrine Hydrochloride',
     'Ephedrine Hydrochloride/Chlorphenamine',
     'Ephedrine Nasal Drops',
     'Epilim',
     'Epinastine Hydrochloride',
     'Epipen',
     'Epirubicin Hydrochloride',
     'Epival',
     'Epivir',
     'Eplerenone',
     'Epoetin Alfa',
     'Epoetin Beta',
     'Epoprostenol',
     'Eposin',
     'Eprex',
     'Eprosartan',
     'Eprosartan Mesilate',
     'Epsom Salts',
     'Eptacog Alfa',
     'Eptifibatide',
     'Erbitux',
     'Erdosteine',
     'Erdotin',
     'Ergometrine Maleate',
     'Ergometrine Maleate/Oxytocin',
     'Erlotinib Hydrochloride',
     'Ertapenem Sodium',
     'Eryacne 4',
     'Erymax',
     'Erythrocin',
     'Erythromycin',
     'Erythromycin Ethyl Succinate',
     'Erythromycin Lactobionate',
     'Erythromycin Stearate',
     'Erythromycin/Isotretinoin',
     'Erythromycin/Tretinoin',
     'Erythromycin/Zinc Acetate',
     'Erythroped',
     'Escitalopram',
     'Escitalopram Oxalate',
     'Esmeron',
     'Esmya',
     'Esomeprazole Injection',
     'Esomeprazole Tablets',
     'Estracyt',
     'Estraderm',
     'Estradiol',
     'Estradiol Hemihydrate',
     'Estradiol Hemihydrate/Norethisterone Acetate',
     'Estradiol Valerate',
     'Estradiol Valerate/Medroxyprogesterone',
     'Estradiol Valerate/Medroxyprogesterone Acetate',
     'Estradiol Valerate/Norethisterone',
     'Estradiol Valerate/Norgestrel',
     'Estradiol/Estriol/Estrone',
     'Estradiol/Levonorgestrel',
     'Estradiol/Norethisterone Acetate',
     'Estradot',
     'Estramustine Sodium Phosphate',
     'Estring',
     'Estriol',
     'Estropipate',
     'Etamsylate',
     'Etanercept',
     'Ethanolamine',
     'Ethinylestradiol',
     'Ethinylestradiol/Etonogestrel',
     'Ethinylestradiol/Gestodene',
     'Ethinylestradiol/Levonorgestrel',
     'Ethinylestradiol/Norelgestromin',
     'Ethinylestradiol/Norethisterone',
     'Ethinylestradiol/Norethisterone Acetate',
     'Ethinylestradiol/Norgestimate',
     'Ethosuximide',
     'Etodolac',
     'Etomidate',
     'Etonogestrel',
     'Etopophos',
     'Etoposide',
     'Etoposide Phosphate',
     'Etoricoxib',
     'Etravirine',
     'Etynodiol Diacetate',
     'Eucalyptus/Menthol/Cetylpyridinium Chloride',
     'Eucalyptus/Terpineol/Methyl Salicylate/Menthol/Camphor',
     'Eucalyptus/Thyme/Menthol',
     'Eucalyptus/Turpentine/Levomenthol/Camphor',
     'Eucalyptus/Turpentine/Methyl Salicylate/Menthol',
     'Eucreas',
     'Eumocream',
     'Eumovate',
     'Eurax',
     'Eurax Hydrocortisone',
     'Everolimus',
     'Evista',
     'Evoltra',
     'Evorel',
     'Evorel Conti',
     'Evorel Sequi',
     'Evra',
     'Ex-Lax Senna',
     'Exelon',
     'Exelon Patches',
     'Exemestane',
     'Exenatide',
     'Exforge',
     'Exjade',
     'Exocin',
     'Exorex Lotion',
     'Extavia',
     'Exterol',
     'Ezetimibe',
     'Ezetimibe/Simvastatin',
     'Ezetrol',
     'Factor Ii/Factor Vii/Protein S/Factor X/Protein C/Factor Ix',
     'Factor Ix High Purity',
     'Factor Viii/Von Willebrand Factor',
     'Factor Xiii',
     'Famciclovir',
     'Family Meltus Chesty Coughs',
     'Famotidine',
     'Famotidine/Calcium Carbonate/Magnesium Hydroxide',
     'Famvir',
     'Fareston',
     'Fasigyn',
     'Faslodex',
     'Faverin',
     'Febuxostat',
     'Felbinac',
     'Feldene',
     'Felendil',
     'Felodipine',
     'Felodipine/Ramipril',
     'Felogen',
     'Felotens',
     'Femapak',
     'Femara',
     'Fematrix',
     'Femodene',
     'Femodette',
     'Femoston',
     'Femseven Conti',
     'Femseven Patches',
     'Femseven Sequi',
     'Femulen',
     'Fenactol',
     'Fendrix',
     'Fenistil',
     'Fenofibrate',
     'Fenofibrate Micronised',
     'Fenoterol/Ipratropium',
     'Fenticonazole Nitrate',
     'Ferinject',
     'Ferric Carboxymaltose',
     'Ferriprox',
     'Ferrous Fumarate',
     'Ferrous Fumarate/Folic Acid',
     'Ferrous Sulphate Tablets',
     'Ferrous Sulphate/Ascorbic Acid',
     'Fersaday',
     'Fersamal',
     'Fesoterodine Fumarate',
     'Fexofenadine Hydrochloride',
     'Fibrazate',
     'Fibro-Vein',
     'Fibrogammin P',
     'Filgrastim',
     'Finacea',
     'Finasteride',
     'Fingolimod Hydrochloride',
     'Flagyl',
     'Flagyl-S',
     'Flamatak',
     'Flamrase',
     'Flavoxate Hydrochloride',
     'Flecainide',
     'Flecainide Acetate',
     'Flexin',
     'Flixonase',
     'Flixonase Allergy',
     'Flixotide',
     'Flolan',
     'Flomaxtra',
     'Florinef',
     'Floxapen',
     'Fluanxol',
     'Fluarix',
     'Flucloxacillin Sodium',
     'Fluconazole',
     'Fluconazole And Clotrimazole',
     'Flucytosine',
     'Fludara',
     'Fludarabine Phosphate',
     'Fludrocortisone Acetate',
     'Fluimucil N',
     'Flumazenil',
     'Fluorescein Sodium/Lidocaine Hydrochloride',
     'Fluorescein Sodium/Proxymetacaine Hydrochloride',
     'Fluorometholone',
     'Fluorouracil',
     'Fluorouracil Sodium',
     'Fluoxetine',
     'Flupentixol',
     'Flupentixol Decanoate',
     'Flupentixol Dihydrochloride',
     'Fluphenazine Decanoate',
     'Flurazepam',
     'Flurazepam Hydrochloride',
     'Flurbiprofen',
     'Flurbiprofen Sodium',
     'Fluticasone Furoate',
     'Fluticasone Propionate',
     'Fluticasone/Salmeterol',
     'Fluvastatin',
     'Fluvastatin Sodium',
     'Fluvirin',
     'Fluvoxamine',
     'Fluvoxamine Maleate',
     'Fml',
     'Folic Acid',
     'Follitropin Alfa',
     'Follitropin Alfa/Lutropin Alfa',
     'Follitropin Beta',
     'Fondaparinux',
     'Foradil',
     'Forceval',
     'Formaldehyde',
     'Formoterol Fumarate Dihydrate',
     'Forsteo',
     'Fortipine',
     'Fortum',
     'Fosamax',
     'Fosamprenavir Calcium',
     'Fosavance',
     'Foscarnet Sodium',
     'Foscavir',
     'Fosinopril',
     'Fosphenytoin Sodium',
     'Fosrenol',
     'Fostair',
     'Fragmin',
     'Freederm Gel',
     'Frisium',
     'Froben',
     'Frovatriptan Succinate Monohydrate',
     'Fru-Co',
     'Frumil',
     'Frusene',
     'Frusol',
     'Fucibet',
     'Fucidin Cream',
     'Fucidin H',
     'Fucidin H Ointment',
     'Fucidin Ointment',
     'Fucidin Suspension',
     'Fucidin Tablets',
     'Fucithalmic',
     'Fulvestrant',
     'Fungizone',
     'Furadantin',
     'Furosemide',
     'Furosemide/Spironolactone',
     'Furosemide/Triamterene',
     'Fusidic Acid',
     'Fusidic Acid/Hydrocortisone Acetate',
     'Fuzeon',
     'Fybogel',
     'Fybogel Mebeverine',
     'Gabapentin',
     'Gabitril',
     'Gadobutrol',
     'Gadoteridol',
     'Gadovist',
     'Gadoxetate Disodium',
     'Galantamine Hydrobromide',
     'Galvus',
     'Gamanil',
     'Ganciclovir Sodium',
     'Ganfort',
     'Ganirelix',
     'Gardasil',
     'Garlic Oil/Garlic/Echinacea',
     'Gastrobid',
     'Gastrocote Liquid',
     'Gastrocote Tablets',
     'Gaviscon Advance',
     'Gaviscon Cool Tablets',
     'Gaviscon Double Action',
     'Gaviscon Extra Strength Tablets',
     'Gaviscon Infant Oral Powder',
     'Gaviscon Liquid Sachets',
     'Gaviscon Tablets',
     'Gefitinib',
     'Geltears',
     'Gemcitabine Hydrochloride',
     'Gemeprost',
     'Gemfibrozil',
     'Gemzar',
     'Generic Abidec Multivitamin Drops',
     'Generic Actonorm Powder',
     'Generic Alginate/Aluminium Hydroxide/Magnesium Carbonate',
     'Generic Antitis Tablets',
     'Generic Calcimax Liquid',
     'Generic Catarrh Relief Mixture',
     'Generic Cetanorm Cream',
     'Generic Chest Mixture',
     'Generic Cymalon Granules',
     'Generic Dalivit Oral Drops',
     'Generic Deep Heat Spray',
     'Generic Diocalm',
     'Generic Dioralyte Powder',
     'Generic Dioralyte Relief',
     'Generic Diprobase Cream',
     'Generic Dubam Cream',
     'Generic Dulbalm Cream',
     'Generic Electrolade Powder',
     'Generic Fiery Jack Cream',
     'Generic Forceval Capsules',
     'Generic Germolene Antiseptic Ointment',
     'Generic Glycerin, Honey And Lemon Linctus',
     'Generic Indian Brandee',
     'Generic Karvol Decongestant Capsules',
     'Generic Karvol Decongestant Drops',
     'Generic Ketovite Liquid',
     'Generic Laxido',
     'Generic Lipobase',
     'Generic Metanium Barrier Ointment',
     'Generic Meted Shampoo',
     'Generic Molaxole Powder',
     'Generic Oxymetazoline',
     'Generic Pharmaton Vitality Capsules',
     'Generic Phytex',
     'Generic Polytar Af Liquid',
     'Generic Polytar Emollient',
     'Generic Polytar Liquid',
     'Generic Polytar Plus Liquid',
     "Generic Potter'S Strong Bronchial Catarrh Pastilles",
     "Generic Potter'S Sugar Free Cough Pastilles",
     'Generic Radian B Muscle Lotion',
     'Generic Rehydration Powder',
     'Generic Resolve Effervescent Granules',
     'Generic Sciargo Tablets',
     'Generic Senokot Comfort Tablets',
     'Generic Senokot Dual Relief Tablets',
     'Generic Sudocrem Cream',
     'Generic Tcp Antiseptic Cream',
     'Generic Tcp Antiseptic Ointment',
     'Generic Throaties Strong Original Pastilles',
     'Generic Transvasin Spray',
     'Generic Ultrabase',
     'Generic Unguentum M Cream',
     'Generic Vadarex Ointment',
     'Generic Vegetable Cough Remover Elixir',
     'Genotropin',
     'Gentamicin Sulphate',
     'Gentamicin Sulphate/Hydrocortisone Acetate',
     'Gentisone',
     'Germolene Antiseptic Cream',
     'Germolene Antiseptic First Aid Wash',
     'Germolene Antiseptic Ointment',
     'Germoloids Cream',
     'Germoloids Duo Pack',
     'Germoloids Hc Spray',
     'Germoloids Ointment',
     'Germoloids Suppositories',
     'Gestone',
     'Gestrinone',
     'Gilenya',
     'Glatiramer Acetate',
     'Gliadel',
     'Glibenese',
     'Gliclazide',
     'Glimepiride',
     'Glipizide',
     'Glivec',
     'Glucagen',
     'Glucagon',
     'Glucobay',
     'Glucophage',
     'Glucose Anhydrous',
     'Glucose/Treacle Cough Mixture',
     'Glutaraldehyde',
     'Glutarol',
     'Glycerin And Blackcurrant Cough Syrup',
     'Glycerin, Honey And Lemon Linctus',
     'Glycerin, Honey, Lemon And Ipecacuanha Linctus',
     'Glycerol Cream',
     'Glycerol Oral Solution',
     'Glycerol Skin Wash',
     'Glycerol/Glucose Cough Mixture',
     'Glycerol/Sucrose Cough Mixture',
     'Glycerol/Syrup/Citric Acid/Honey/Lemon',
     'Glycerol/White Soft Paraffin/Liquid Paraffin',
     'Glyceryl Trinitrate',
     'Glycopyrronium Bromide',
     'Goddards Muscle Lotion',
     'Golimumab',
     'Gonapeptyl',
     'Gopten',
     'Goserelin Acetate',
     'Granisetron Hydrochloride',
     'Granocyte-13',
     'Grass Pollen Extract',
     'Grazax',
     'Griseofulvin',
     'Grisol Af',
     'Guaiacol/Codeine',
     'Guaifenesin',
     'Guaifenesin/Ammonium Chloride/Ammonium Carbonate',
     'Guaifenesin/Cetylpyridinium Chloride',
     'Guaifenesin/Levomenthol',
     'Guaifenesin/Pseudoephedrine',
     'Guaifenesin/Treacle/Glucose',
     'Guanethidine',
     'Guanethidine Monosulphate',
     'Gygel',
     'Gyno-Daktarin',
     'Gyno-Pevaryl',
     'Gynoxin',
     'Haemate P',
     'Haemorrhoid Relief Ointment',
     'Haldol',
     'Haldol Decanoate',
     'Halogenated Phenols/Phenol',
     'Haloperidol',
     'Haloperidol Decanoate',
     'Hamol Senna Tablets',
     'Happinose',
     'Harmogen',
     'Havrix',
     'Haymine Tablets',
     'Hbvaxpro',
     'Hedex',
     'Hedex Extra',
     'Hedex Ibuprofen',
     'Helixate Nexgen',
     'Hemabate',
     'Heminevrin Capsules',
     'Heparin Sodium',
     'Hepatyrix',
     'Hepsal',
     'Hepsera',
     'Herceptin',
     'Herpid',
     'Hexetidine',
     'Hexopal',
     'Hexylresorcinol',
     'Hexylresorcinol/Benzalkonium Chloride',
     'Hiprex',
     'Histac',
     'Histamine Dihydrochloride',
     'Honey/Glucose/Lemon',
     'Honey/Menthol',
     'Horizem',
     'Hormonin',
     'Humalog',
     'Humalog Mix',
     'Humatrope',
     'Humira',
     'Humulin I',
     'Humulin M3',
     'Humulin S',
     'Hyaluronidase',
     'Hycamtin',
     'Hydralazine',
     'Hydralazine Hydrochloride',
     'Hydrea',
     'Hydrochlorothiazide/Irbesartan',
     'Hydrochlorothiazide/Losartan',
     'Hydrochlorothiazide/Olmesartan',
     'Hydrochlorothiazide/Olmesartan Medoxomil',
     'Hydrochlorothiazide/Quinapril',
     'Hydrochlorothiazide/Telmisartan',
     'Hydrochlorothiazide/Valsartan',
     'Hydrocortisone',
     'Hydrocortisone Acetate',
     'Hydrocortisone Acetate/Lidocaine',
     'Hydrocortisone Acetate/Pramocaine Hydrochloride',
     'Hydrocortisone Acetate/Sodium Fusidate',
     'Hydrocortisone Butyrate',
     'Hydrocortisone Sodium Phosphate',
     'Hydrocortisone Sodium Succinate',
     'Hydrocortisone/Lactic Acid/Urea',
     'Hydrocortisone/Lidocaine',
     'Hydrocortisone/Miconazole Nitrate',
     'Hydrocortisone/Neomycin Sulphate/Polymyxin B Sulphate',
     'Hydrocortisone/Urea',
     'Hydrocortistab',
     'Hydroflumethiazide/Spironolactone',
     'Hydromol Bath And Shower Emollient',
     'Hydromol Cream',
     'Hydrotalcite Suspension',
     'Hydroxocobalamin',
     'Hydroxycarbamide',
     'Hydroxychloroquine',
     'Hydroxychloroquine Sulphate',
     'Hydroxyethyl Salicylate/Methyl Nicotinate',
     'Hydroxyethyl Salicylate/Methyl Nicotinate/Capsicum Oleoresin',
     'Hydroxyzine Hydrochloride',
     'Hyetellose',
     'Hygroton',
     'Hyoscine',
     'Hyoscine Butylbromide',
     'Hyoscine Hydrobromide',
     'Hypnomidate',
     'Hypnovel',
     'Hypolar',
     'Hypovase',
     'Hypromellose',
     'Hypromellose/Dextran 70',
     'Hypurin Bovine Isophane',
     'Hypurin Bovine Lente',
     'Hypurin Bovine Neutral',
     'Hypurin Bovine Protamine Zinc',
     'Hypurin Porcine',
     'Hypurin Porcine Isophane',
     'Hypurin Porcine Neutral',
     'Hytrin',
     'Ibandronic Sodium Monohydrate',
     'Ibufem',
     'Ibuprofen',
     'Ibuprofen/Codeine Phosphate',
     'Ibuprofen/Levomenthol',
     'Ibuprofen/Phenylephrine',
     'Ibuprofen/Pseudoephedrine',
     'Idarubicin Hydrochloride',
     'Idoxuridine',
     'Iglu Gel',
     'Ikorel',
     'Iloprost Trometamol',
     'Ilube',
     'Imatinib Mesilate',
     'Imigran',
     'Imigran Nasal Spray',
     'Imigran Recovery',
     'Imipramine Hydrochloride',
     'Imiquimod',
     'Immucyst',
     'Imodium',
     'Imodium Plus',
     'Implanon',
     'Imunovir',
     'Imuran',
     'Imuvac',
     'Incivo',
     'Increlex',
     'Indacaterol Maleate',
     'Indapamide',
     'Indapamide Hemihydrate',
     'Indapamide/Perindopril Arginine',
     'Inderal',
     'Indivina',
     'Indolar',
     'Indometacin',
     'Indomod',
     'Indoramin Hydrochloride',
     'Inegy',
     'Infacol',
     'Infanrix Ipv',
     'Infanrix-Ipv+Hib',
     'Infliximab',
     'Influenza Vaccine',
     'Influvac',
     'Innohep',
     'Innovace',
     'Innozide',
     'Inosine Pranobex',
     'Inositol Nicotinate',
     'Inovelon',
     'Inspra',
     'Insulatard',
     'Insulin Aspart',
     'Insulin Aspart/Insulin Aspart Protamine',
     'Insulin Detemir',
     'Insulin Glargine',
     'Insulin Glulisine',
     'Insulin Isophane Bovine',
     'Insulin Isophane Human',
     'Insulin Isophane Human/Insulin Soluble Human',
     'Insulin Isophane Porcine',
     'Insulin Isophane Porcine/Insulin Soluble Porcine',
     'Insulin Lispro',
     'Insulin Lispro/Insulin Lispro Protamine',
     'Insulin Protamine Zinc Bovine',
     'Insulin Soluble Bovine',
     'Insulin Soluble Human',
     'Insulin Soluble Porcine',
     'Insulin Zinc Suspension Mixed Bovine',
     'Insuman Basal',
     'Insuman Comb',
     'Insuman Rapid',
     'Intal',
     'Integrilin',
     'Intelence',
     'Interferon Alfa-2A (Rbe)',
     'Interferon Alfa-2B (Rbe)',
     'Interferon Beta-1A',
     'Interferon Beta-1B',
     'Introna',
     'Invanz',
     'Invega',
     'Invirase',
     'Iopidine',
     'Ipocol',
     'Ipratropium',
     'Ipratropium/Salbutamol',
     'Irbesartan',
     'Iressa',
     'Irinotecan Hydrochloride Trihydrate',
     'Iron Dextran',
     'Iron Sucrose',
     'Isentress',
     'Ismelin',
     'Isocarboxazid',
     'Isoflurane',
     'Isoket',
     'Isoniazid',
     'Isoniazid/Pyrazinamide/Rifampicin',
     'Isoniazid/Rifampicin',
     'Isopropyl Myristate/Liquid Paraffin',
     'Isopto Alkaline',
     'Isopto Plain',
     'Isosorbide Dinitrate',
     'Isosorbide Mononitrate',
     'Isotretinoin',
     'Isotrex',
     'Isotrexin',
     'Isovorin',
     'Ispaghula Husk Granules',
     'Ispaghula Husk/Mebeverine',
     'Isradipine',
     'Istin',
     'Itraconazole',
     'Ivabradine',
     'Ixiaro',
     'Janumet',
     'Januvia',
     'Javlor',
     'Junior Meltus Chesty Coughs With Catarrh',
     'Kaletra',
     'Kaolin And Morphine Mixture',
     'Kaolin/Calcium Carbonate',
     'Karvol Decongestant Capsules',
     'Karvol Decongestant Drops',
     'Kefadim',
     'Keflex',
     'Keftid',
     'Kemadrin',
     'Kemicetine',
     'Kenalog',
     'Kentera',
     'Kentipine',
     'Kenzem',
     'Keppra',
     'Keral',
     'Ketalar',
     'Ketamine Hydrochloride',
     'Ketek',
     'Ketocid',
     'Ketoconazole',
     'Ketoprofen',
     'Ketorolac Trometamol',
     'Ketotifen',
     'Ketovail',
     'Ketovite Liquid',
     'Kivexa',
     'Klaricid',
     'Kliofem',
     'Kliovance',
     'Kolanticon Gel',
     'Kytril',
     'Lacidipine',
     'Lacosamide',
     'Lacrilube',
     'Lactulose',
     'Lamictal',
     'Lamisil',
     'Lamivudine',
     'Lamivudine/Zidovudine',
     'Lamotrigine',
     'Lanacane Cream',
     'Lanolin/White Soft Paraffin/Liquid Paraffin',
     'Lanoxin',
     'Lanreotide Acetate',
     'Lansoprazole',
     'Lanthanum Carbonate',
     'Lantus',
     'Lanvis',
     'Lapatinib Ditosylate Monohydrate',
     'Larapam',
     'Largactil',
     'Lariam',
     'Laryng-O-Jet',
     'Lasilactone',
     'Lasix',
     'Lasoride',
     'Latanoprost',
     'Latanoprost/Timolol Maleate',
     'Lauromacrogol 400/Heparinoid',
     'Laxido',
     'Leflunomide',
     'Lemon/Honey/Levomenthol/Citric Acid',
     'Lemsip Cold And Flu',
     'Lemsip Cough Chesty',
     'Lemsip Dry Cough Liquid',
     'Lemsip Flu 12 Hour Ibuprofen And Pseudoephedrine',
     'Lemsip Max All Day Cold And Flu Tablets',
     'Lemsip Max All Night Cold And Flu Tablets',
     'Lemsip Max All-In-One',
     'Lemsip Max Cold And Flu Breathe Easy',
     'Lemsip Max Cold And Flu Direct',
     'Lemsip Max Day And Night Cold And Flu Relief Capsules',
     'Lemsip Max Flu',
     'Lemsip Max Sinus',
     'Lemsip Max Sinus Capsules',
     'Lenalidomide',
     'Lenograstim (Rch)',
     'Lercanidipine',
     'Lescol',
     'Letrozole',
     'Leukeran',
     'Leuprorelin Acetate',
     'Leustat',
     'Levemir',
     'Levetiracetam',
     'Levitra',
     'Levobunolol Hydrochloride',
     'Levobupivacaine Hydrochloride',
     'Levocetirizine Dihydrochloride',
     'Levofloxacin',
     'Levofloxacin Hemihydrate',
     'Levomenthol',
     'Levomenthol/Amylmetacresol/Dichlorobenzyl Alcohol',
     'Levomenthol/Squill/Liquorice',
     'Levomepromazine Maleate',
     'Levonelle',
     'Levonorgestrel',
     'Levothyroxine Sodium',
     'Lexpec Folic Acid',
     'Li-Liquid',
     'Librium',
     'Librofem',
     'Lidocaine',
     'Lidocaine Hydrochloride',
     'Lidocaine Hydrochloride/Adrenaline Acid Tartrate',
     'Lidocaine/Aminoacridine',
     'Lidocaine/Cetalkonium Chloride',
     'Lidocaine/Cetylpyridinium Chloride',
     'Lidocaine/Chlorhexidine',
     'Lidocaine/Chlorocresol/Cetylpyridinium Chloride',
     'Lidocaine/Methylprednisolone Acetate',
     'Lidocaine/Zinc Sulphate/Cetrimide',
     'Light Liquid Paraffin',
     'Linezolid',
     'Lioresal',
     'Liothyronine Sodium',
     'Lipantil',
     'Lipitor',
     'Lipobase',
     'Liposic',
     'Lipostat',
     'Liqufilm Tears',
     'Liquid Paraffin',
     'Liquid Paraffin/Acetylated Wool Alcohols',
     'Liquid Paraffin/Isopropyl Myristate',
     'Liquid Paraffin/White Soft Paraffin',
     'Liquid Paraffin/Wool Alcohols/White Soft Paraffin',
     'Liraglutide',
     'Lisinopril',
     'Lisinopril/Hydrochlorothiazide',
     'Liskonum',
     'Lisopress',
     'Litak',
     'Lithium Carbonate',
     'Lithium Citrate',
     'Livial',
     'Loceryl',
     'Locoid',
     'Lodine',
     'Lodoxamide Trometamol',
     'Loestrin',
     'Lofepramine',
     'Lofepramine Hydrochloride',
     'Logynon',
     'Lomont',
     'Lomustine',
     'Loniten',
     'Lopace',
     'Loperamide And Rehydration Powder',
     'Loperamide Hydrochloride',
     'Lopid',
     'Lopinavir/Ritonavir',
     'Loprazolam',
     'Lopresor',
     'Loratadine',
     'Lorazepam',
     'Loron 520',
     'Losartan',
     'Losec',
     'Losec Iv',
     'Losec Mups',
     'Lotemax',
     'Loteprednol Etabonate',
     'Luborant',
     'Lucentis',
     'Lumigan',
     'Lustral',
     'Lutropin Alfa',
     'Luveris',
     'Lyclear Cream Rinse',
     'Lyclear Dermal Cream',
     'Lyflex',
     'Lymecycline',
     'Lypsyl Cold Sore Gel',
     'Lyrica',
     'Lyrinel',
     'Lysine Acetylsalicylate/Metoclopramide Hydrochloride',
     'Lysodren',
     'Lysovir',
     'Maalox',
     'Maalox Plus',
     'Mabcampath',
     'Mabthera',
     'Mackenzies Smelling Salts',
     'Macrobid',
     'Macrodantin',
     'Macrogol 4000',
     'Macrogol Compound Powder Npf',
     'Macugen',
     'Madopar',
     'Magnapen Vial',
     'Magnesium Hydroxide Oral Suspension',
     'Magnesium Hydroxide Tablets',
     'Magnesium Hydroxide/Simeticone/Aluminium Hydroxide Gel Dried',
     'Magnesium Trisilicate/Sodium Bicarbonate/Alginic Acid/Aluminium Hydroxide',
     'Magnevist',
     'Malarone',
     'Malathion',
     'Mandafen',
     'Manerix',
     'Maraviroc',
     'Marcain Heavy',
     'Marcain Polyamp Steripack',
     'Marevan',
     'Marvelon',
     'Mastaflu',
     'Maxalt',
     'Maxidex',
     'Maxitrol Eye Drops',
     'Maxitrol Eye Ointment',
     'Maxolon',
     'Maxtrex',
     'Mebendazole',
     'Mebeverine Hydrochloride',
     'Mecasermin',
     'Meclozine',
     'Medicated Talc',
     'Medijel Gel',
     'Medijel Pastilles',
     'Medised For Children',
     'Medrone',
     'Medroxyprogesterone Acetate',
     'Mefenamic',
     'Mefenamic Acid',
     'Mefloquine Hydrochloride',
     'Megace',
     'Megestrol Acetate',
     'Meggezones',
     'Meglumine Gadobenate',
     'Meglumine Gadopentetate',
     'Melatonin',
     'Meloxicam',
     'Melphalan',
     'Melphalan Hydrochloride',
     'Memantine Hydrochloride',
     'Menadiol Sodium Phosphate',
     'Meningitec',
     'Menitorix',
     'Menjugate',
     'Menopur',
     'Menotrophin',
     'Menthol Pastilles',
     'Menthol/Anise Oil',
     'Menthol/Camphor/Pine Needle Oil',
     'Menthol/Eucalyptus',
     'Menthol/Peppermint',
     'Menthol/Pine Sylvestris Oil/Abietis Oil',
     'Mepradec',
     'Mepyramine',
     'Merbentyl',
     'Mercaptopurine',
     'Mercilon',
     'Merional',
     'Merocaine',
     'Merocets Lozenges',
     'Merocets Plus',
     'Meronem',
     'Meropenem Trihydrate',
     'Mesalazine',
     'Mesren',
     'Mesterolone',
     'Mestinon',
     'Mestranol/Norethisterone',
     'Metalyse',
     'Meted',
     'Meted Shampoo',
     'Metenix',
     'Metformin',
     'Metformin Hydrochloride',
     'Metformin Hydrochloride/Sitagliptin Phosphate',
     'Metformin Hydrochloride/Vildagliptin',
     'Metformin/Pioglitazone',
     'Methenamine Hippurate',
     'Methotrexate',
     'Methotrexate Sodium',
     'Methoxy Polyethylene Glycol-Epoetin Beta',
     'Methoxymethane/Hydroxyethyl Salicylate/Isopentane',
     'Methyl Aminolevulinate Hydrochloride',
     'Methyl Salicylate',
     'Methyl Salicylate/Menthol',
     'Methyl Salicylate/Menthol/Camphor',
     'Methyl Salicylate/Menthol/Capsicum/Camphor',
     'Methylcellulose',
     'Methylnaltrexone Bromide',
     'Methylphenidate Hydrochloride',
     'Methylprednisolone',
     'Methylprednisolone Acetate',
     'Methylprednisolone Sodium Succinate',
     'Methysergide Maleate',
     'Metipranolol',
     'Metoclopramide',
     'Metoclopramide Hydrochloride',
     'Metoclopramide Hydrochloride/Paracetamol',
     'Metolazone',
     'Metopirone',
     'Metoprolol',
     'Metrogel',
     'Metrolyl',
     'Metronidazole',
     'Metronidazole Benzoate',
     'Metrosa',
     'Metrotop',
     'Metvix',
     'Metyrapone',
     'Miacalcic',
     'Micafungin Sodium',
     'Micardis',
     'Micardisplus',
     'Miconazole',
     'Miconazole Nitrate',
     'Microgynon 30',
     'Micronor',
     'Micropirin',
     'Midazolam Hydrochloride',
     'Mifegyne',
     'Mifepristone',
     'Migard',
     'Migril',
     'Mildison Lipocream',
     'Milrinone',
     'Mimpara',
     'Mini-Plasco Lidocaine',
     'Minijet Adrenaline',
     'Minijet Amiodarone',
     'Minijet Atropine',
     'Minijet Furosemide',
     'Minijet Lidocaine',
     'Minijet Naloxone',
     'Minijet Sodium Bicarbonate',
     'Minims Artificial Tears',
     'Minims Atropine',
     'Minims Chloramphenicol',
     'Minims Cyclopentolate Hydrochloride',
     'Minims Dexamethasone',
     'Minims Lidocaine And Fluorescein',
     'Minims Metipranolol',
     'Minims Pilocarpine Nitrate',
     'Minims Prednisolone',
     'Minims Proxymetacaine And Fluorescein',
     'Minims Tetracaine Hydrochloride',
     'Minims Tropicamide',
     'Minocin',
     'Minocycline Hydrochloride',
     'Minodiab',
     'Minoxidil',
     'Miochol-E',
     'Mirapexin',
     'Mircera',
     'Mirena',
     'Mirtazapine',
     'Misoprostol',
     'Misoprostol/Naproxen',
     'Mitomycin',
     'Mitomycin-C Kyowa',
     'Mitotane',
     'Mitoxantrone Hydrochloride',
     'Mivacron',
     'Mivacurium Chloride',
     'Mixtard',
     'Mizolastine',
     'Mizollen',
     'Mmrvaxpro',
     'Mobiflex',
     'Moclobemide',
     'Modafinil',
     'Modalim',
     'Modecate',
     'Modrenal',
     'Moduret',
     'Moduretic',
     'Moexipril',
     'Moexipril Hydrochloride',
     'Mogadon',
     'Molaxole',
     'Molipaxin',
     'Mometasone',
     'Mometasone Furoate',
     'Monomil',
     'Monosorb',
     'Montelukast Sodium',
     'Morhulin Ointment',
     'Morphine',
     'Motens',
     'Motifene',
     'Motilium',
     'Motilium Tablet',
     'Movelat',
     'Movicol',
     'Moxifloxacin Hydrochloride',
     'Moxisylyte Hydrochloride',
     'Moxonidine',
     'Mucodyne',
     'Mucogel',
     'Multaq',
     'Multi-Action Actifed Tablets',
     'Multihance',
     'Multiparin',
     'Mupirocin Calcium',
     'Muse',
     'Mycamine',
     'Mycil Athletes Foot Spray',
     'Mycil Ointment',
     'Mycil Powder',
     'Mycobutin',
     'Mycophenolate Mofetil',
     'Mycophenolate Mofetil Hydrochloride',
     'Mycophenolate Sodium',
     'Mycota Spray',
     'Myfortic',
     'Myleran',
     'Myocet',
     'Myocrisin',
     'Myotonine',
     'Mysoline',
     'Nabilone',
     'Nabumetone',
     'Nadolol',
     'Nafarelin Acetate',
     'Naftidrofuryl',
     'Naftidrofuryl Oxalate',
     'Nalcrom',
     'Nalidixic Acid',
     'Naloxone Hydrochloride',
     'Nandrolone Decanoate',
     'Naphazoline',
     'Napratec',
     'Naprosyn',
     'Naproxen',
     'Naproxen/Esomeprazole Magnesium Trihydrate',
     'Naramig',
     'Naratriptan Hydrochloride',
     'Naropin',
     'Nasacort',
     'Naseptin',
     'Nasofan',
     'Nasonex',
     'Natalizumab',
     'Natecal D3',
     'Nateglinide',
     'Natracalm',
     'Natrasleep',
     'Natrilix',
     'Natrilix Sr',
     'Navelbine',
     'Nebilet',
     'Nebivolol',
     'Nebivolol Hydrochloride',
     'Nedocromil',
     'Nedocromil Sodium',
     'Nelarabine',
     'Neo-Cytamen',
     'Neo-Naclex',
     'Neoclarityn',
     'Neofel',
     'Neomercazole',
     'Neomycin Sulphate',
     'Neoral',
     'Neorecormon',
     'Neostigmine Metilsulfate',
     'Neostigmine Metilsulfate/Glycopyrronium Bromide',
     'Neotigason',
     'Neulactil',
     'Neulasta',
     'Neupogen',
     'Neupro',
     'Neurobloc',
     'Neurontin',
     'Neutrogena Norwegian Formula Cream',
     'Neutrogena T-Gel Shampoo',
     'Nevirapine',
     'Nevirapine Hemihydrate',
     'Nexavar',
     'Nexium',
     'Nexium Iv',
     'Niaspan',
     'Nicam Gel',
     'Nicardipine',
     'Nicardipine Hydrochloride',
     'Nicorandil',
     'Nicorette Gum',
     'Nicorette Inhalator',
     'Nicorette Invisi Patches',
     'Nicorette Microtab',
     'Nicorette Nasal Spray',
     'Nicorette Patches',
     'Nicotinamide',
     'Nicotine Gum',
     'Nicotine Inhaler',
     'Nicotine Lozenges',
     'Nicotine Nasal Spray',
     'Nicotine Patches',
     'Nicotine Sublingual Tablets',
     'Nicotinell Gum',
     'Nicotinell Lozenges',
     'Nicotinell Patches',
     'Nicotinic Acid',
     'Nifedipine',
     'Nifopress',
     'Night Nurse',
     'Nilotinib Hydrochloride Monohydrate',
     'Nimbex',
     'Nimodipine',
     'Nimotop',
     'Nipent',
     'Niquitin Gum',
     'Niquitin Lozenges',
     'Niquitin Mini Lozenges',
     'Niquitin Patches',
     'Nirolex Chesty Cough Linctus',
     'Nirolex Dry Cough Linctus',
     'Nirolex Dry Cough Relief Lozenges',
     'Nirolex Dry Coughs With Decongestant',
     'Nitrazepam',
     'Nitrofurantoin',
     'Nizatidine',
     'Nizoral',
     'Non-Drowsy Sudafed Childrens Syrup',
     'Nonacog Alfa',
     'Nonoxinol-9',
     'Nootropil',
     'Noradrenaline Acid Tartrate',
     'Norcuron',
     'Norditropin Nordiflex',
     'Norditropin Simplexx',
     'Norethisterone',
     'Norethisterone Enantate',
     'Norfloxacin',
     'Norgalax',
     'Norgeston',
     'Noriday',
     'Norimin',
     'Norimode',
     'Norinyl-1',
     'Noristerat',
     'Normacol',
     'Normacol Plus',
     'Normal Immunoglobulin Human',
     'Nortriptyline',
     'Nortriptyline Hydrochloride',
     'Norvir',
     'Norzol',
     'Novofem',
     'Novomix 30',
     'Novorapid',
     'Novoseven',
     'Noxafil',
     'Nozinan Tablets',
     'Nu-Seals',
     'Nupercainal',
     'Nurofen',
     'Nurofen Cold And Flu',
     'Nurofen Plus',
     'Nutrizym',
     'Nutropinaq',
     'Nuvaring',
     'Nyogel',
     'Nystan',
     'Nystatin',
     'Nytol',
     'Occlusal',
     'Octim',
     'Octocog Alfa',
     'Octreotide Acetate',
     'Ocufen',
     'Oculotect',
     'Ofatumumab',
     'Ofloxacin',
     'Ofloxacin Hydrochloride',
     'Oilatum Cream',
     'Oilatum Emollient',
     'Oilatum Gel',
     'Oilatum Junior Bath Additive',
     'Oilatum Junior Cream',
     'Oilatum Plus',
     'Oilatum Shower Gel Fragrance-Free',
     'Olanzapine',
     'Olanzapine Pamoate Monohydrate',
     'Olbetam',
     'Olmesartan',
     'Olmesartan Medoxomil',
     'Olmetec',
     'Olmetec Plus',
     'Olopatadine Hydrochloride',
     'Olsalazine Sodium',
     'Omalizumab',
     'Omeprazole',
     'Omeprazole Magnesium',
     'Omeprazole Sodium',
     'Oncotice',
     'Ondansetron',
     'Ondansetron Hydrochloride',
     'One-Alpha',
     'Onglyza',
     'Onkotrone',
     'Opatanol',
     'Opilon',
     'Opticrom',
     'Optilast',
     'Optimax',
     'Optivate',
     'Oraldene',
     'Orap',
     'Orelox',
     'Orencia',
     'Orgalutran',
     'Orgaran',
     'Original Andrews Salts',
     'Orlept',
     'Orlistat',
     'Orphenadrine Hydrochloride',
     'Ortho-Gynest',
     'Orudis',
     'Oruvail',
     'Otex',
     'Otomize',
     'Otosporin',
     'Otrivine Adult Measured Dose Sinusitis Spray',
     'Otrivine Adult Menthol Nasal Spray',
     'Otrivine Adult Nasal Drops',
     'Otrivine Adult Nasal Spray',
     'Otrivine Antistin',
     'Otrivine Child Nasal Drops',
     'Otrivine Mu-Cron',
     'Ovestin',
     'Ovitrelle',
     'Ovranette',
     'Ovysmen',
     'Oxactin',
     'Oxaliplatin',
     'Oxcarbazepine',
     'Oxerutins',
     'Oxis',
     'Oxprenolol',
     'Oxprenolol Hydrochloride',
     'Oxprenolol Hydrochloride/Cyclopenthiazide',
     'Oxybuprocaine Hydrochloride',
     'Oxybutynin',
     'Oxybutynin Hydrochloride',
     'Oxymetazoline',
     'Oxytetracycline Dihydrate',
     'Oxytocin',
     'Pabal',
     'Paclitaxel',
     'Paclitaxel Albumin',
     'Pain Relief Balm',
     'Paliperidone',
     'Paliperidone Palmitate',
     'Paludrine',
     'Panadol',
     'Panadol Extra Soluble Tablets',
     'Panadol Extra Tablets',
     'Panadol Night',
     'Pancrease',
     'Pancrex',
     'Pancuronium Bromide',
     'Pandemrix',
     'Panitumumab',
     'Panoxyl Acnegel',
     'Panoxyl Aquagel',
     'Panoxyl Cream',
     'Panoxyl Wash',
     'Pantoprazole',
     'Pantoprazole Sodium Sesquihydrate',
     'Paracetamol',
     'Paracetamol/Caffeine',
     'Paracetamol/Codeine /Caffeine',
     'Paracetamol/Codeine/Diphenhydramine/Caffeine',
     'Paracetamol/Codeine/Doxylamine/Caffeine',
     'Paracetamol/Dihydrocodeine',
     'Paracetamol/Diphenhydramine',
     'Paracetamol/Diphenhydramine Liquid',
     'Paracetamol/Diphenhydramine Tablets',
     'Paracetamol/Phenylephrine Sachets',
     'Paracetamol/Phenylephrine/Caffeine',
     'Paracetamol/Pseudoephedrine',
     'Paracetamol/Sodium Salicylate',
     'Paracetamol/Tramadol Hydrochloride',
     'Paramax',
     'Paramol Soluble Tablets',
     'Paramol Tablets',
     'Parathyroid Hormone',
     'Pardelprin',
     'Parecoxib Sodium',
     'Paricalcitol',
     'Pariet',
     'Parlodel',
     'Parmid',
     'Paroven',
     'Paroxetine',
     'Passion Flower',
     'Passion Flower/Valerian/Hops',
     'Passion Flower/Valerian/Hops/Scullcap/Jamaica Dogwood',
     'Pavacol-D',
     'Paxoran',
     'Pediacel',
     'Pegaptanib Sodium',
     'Pegasys',
     'Pegfilgrastim',
     'Peginterferon Alfa-2A',
     'Peginterferon Alfa-2B (Rbe)',
     'Pegvisomant',
     'Pemetrexed Disodium',
     'Penbritin',
     'Penciclovir',
     'Penicillamine',
     'Pennsaid',
     'Pentasa',
     'Pentostatin',
     'Pentoxifylline',
     'Pentrax Shampoo',
     'Pepcid',
     'Pepcidtwo',
     'Peppermint Oil Capsules',
     'Peppermint Oil/Capsicum/Elder Flower',
     'Peppermint Oil/Cinnamon/Clove Oil/Slippery Elm Bark',
     'Peppermint Oil/Menthol/Benzoin Compound/Ipecacuanha',
     'Peppermint Oil/Menthol/Myrrh',
     'Pepto-Bismol',
     'Perdix',
     'Perfalgan',
     'Pergolide Mesilate',
     'Pergoveris',
     'Periactin',
     'Pericyazine',
     'Perinal Spray',
     'Perindopril',
     'Perindopril Arginine',
     'Permethrin',
     'Persantin',
     'Pevaryl',
     'Pharmaton Capsules',
     'Pharmorubicin',
     'Phenelzine Sulphate',
     'Phenergan',
     'Phenol',
     'Phenol/Aromatic Ammonia/Strong Ammonia',
     'Phenol/Chlorhexidine Digluconate',
     'Phenol/Chlorhexidine Gluconate',
     'Phenylephrine Hydrochloride',
     'Phenylephrine Hydrochloride/Caffeine/Paracetamol',
     'Phenylephrine/Caffeine/Paracetamol Dual Relief',
     'Phenylephrine/Caffeine/Paracetamol Max Strength Capsules',
     'Phenylephrine/Guaifenesin/Paracetamol',
     'Phenylethyl Alcohol/Undecenoic Acid/Cetrimide',
     'Phenytoin',
     'Phenytoin Sodium',
     'Phillips Milk Of Magnesia',
     'Pholcodine',
     'Pholcodine Childrens Oral Solution',
     'Pholcodine Linctus',
     'Phosex',
     'Phyllocontin',
     'Physiotens',
     'Pilocarpine Hydrochloride',
     'Pilocarpine Nitrate',
     'Pimecrolimus',
     'Pimozide',
     'Pindolol',
     'Pinefeld',
     'Pioglitazone',
     'Piperacillin Sodium/Tazobactam Sodium',
     'Piportil',
     'Pipotiazine Palmitate',
     'Piracetam',
     'Piriteze Allergy Syrup',
     'Piriteze Allergy Tablets',
     'Piriton',
     'Piroxicam',
     'Pitressin',
     'Pivmecillinam Hydrochloride',
     'Pizotifen Hydrogen Malate',
     'Plaquenil',
     'Plavix',
     'Plendil',
     'Pletal',
     'Pneumovax Ii',
     'Podophyllotoxin',
     'Pollenshield',
     'Polysaccharide-Iron Complex',
     'Polytar Af Liquid',
     'Polytar Emollient',
     'Polytar Liquid',
     'Polytar Plus Liquid',
     'Polyvinyl Alcohol',
     'Ponstan',
     'Pork Actrapid',
     'Pork Mixtard',
     'Posaconazole',
     'Potassium Citrate',
     'Potassium Citrate/Citric Acid',
     'Potassium Clavulanate/Ticarcillin Sodium',
     'Povidone K25',
     'Povidone-Iodine Spray',
     'Powergel',
     'Pradaxa',
     'Pramipexole Dihydrochloride Monohydrate',
     'Prandin',
     'Prasugrel Hydrochloride',
     'Pravastatin Sodium',
     'Praxilene',
     'Prazosin',
     'Prazosin Hydrochloride',
     'Pred Forte',
     'Predfoam',
     'Prednisolone',
     'Prednisolone Acetate',
     'Prednisolone Sodium Metasulphobenzoate',
     'Prednisolone Sodium Phosphate',
     'Predsol',
     'Pregabalin',
     'Pregnyl',
     'Premarin',
     'Premique',
     'Prempak-C',
     'Preotact',
     'Prescal',
     'Preservex',
     'Prestim',
     'Prevenar',
     'Prezista',
     'Priadel Liquid',
     'Priadel Tablets',
     'Prilocaine Hydrochloride',
     'Prilocaine/Lidocaine',
     'Primacor',
     'Primaxin',
     'Primidone',
     'Primolut N',
     'Primovist',
     'Priorix',
     'Pro-Epanutin',
     'Pro-Viron',
     'Procarbazine Hydrochloride',
     'Prochlorperazine Maleate',
     'Prochlorperazine Mesilate',
     'Procoralan',
     'Proctofoam',
     'Proctosedyl',
     'Procyclidine Hydrochloride',
     'Progesterone',
     'Prograf',
     'Prograf Infusion',
     'Proguanil Hydrochloride',
     'Progynova Patches',
     'Progynova Tablets',
     'Prohance',
     'Proleukin',
     'Prolia',
     'Promethazine',
     'Promethazine Hydrochloride',
     'Promethazine Hydrochloride/Dextromethorphan Hydrobromide/Paracetamol',
     'Promethazine/Dextromethorphan/Paracetamol',
     'Promixin',
     'Propaderm',
     'Propafenone',
     'Propain Caplets',
     'Propain Plus',
     'Propantheline Bromide',
     'Propecia',
     'Propess',
     'Propine',
     'Propiverine Hydrochloride',
     'Propofol',
     'Propranolol',
     'Propranolol Hydrochloride',
     'Proscar',
     'Prostap',
     'Prostin E2',
     'Prosulf',
     'Protamine',
     'Protamine Sulphate',
     'Protelos',
     'Protirelin',
     'Protium',
     'Protopic',
     'Provera',
     'Provigil',
     'Proxymetacaine Hydrochloride',
     'Prozac',
     'Prucalopride Succinate',
     'Pseudoephedrine',
     'Pseudoephedrine Hydrochloride/Diphenhydramine Hydrochloride/Paracetamol',
     'Pseudoephedrine/Acrivastine',
     'Pseudoephedrine/Dextromethorphan',
     'Pseudoephedrine/Paracetamol/Diphenhydramine',
     'Pseudoephedrine/Pholcodine/Paracetamol',
     'Pseudoephedrine/Triprolidine',
     'Pseudoephedrine/Triprolidine/Dextromethorphan',
     'Pseudoephedrine/Triprolidine/Guaifenesin',
     'Psoriderm Bath Additive',
     'Psoriderm Cream',
     'Psoriderm Scalp Lotion',
     'Pulmicort',
     'Pulmozyme',
     'Pumo Bailly',
     'Puregon',
     'Puri-Nethol',
     'Pyralvex',
     'Pyridostigmine Bromide',
     'Pyrimethamine',
     'Questran',
     'Quetiapine Fumarate',
     'Quinapril',
     'Quinapril Hydrochloride',
     'Quinil',
     'Rabeprazole',
     'Rabipur',
     'Ralgex Cream',
     'Ralgex Freeze Spray',
     'Ralgex Heat Spray',
     'Raloxifene Hydrochloride',
     'Raltegravir',
     'Raltitrexed',
     'Ramipril',
     'Ranexa',
     'Ranibizumab',
     'Ranitic',
     'Ranitidine Hydrochloride',
     'Ranitil',
     'Ranolazine',
     'Rapamune',
     'Rapifen',
     'Rapilysin',
     'Rapitil',
     'Rasagiline Mesilate',
     'Rasilez',
     'Rebetol',
     'Rebif',
     'Reboxetine',
     'Reboxetine Mesilate',
     'Rectogesic',
     'Refolinon',
     'Regranex',
     'Regurin',
     'Relcofen',
     'Relenza',
     'Relestat',
     'Relifex',
     'Relistor',
     'Relpax',
     'Remedeine',
     'Remegel',
     'Remegel Wind Relief',
     'Remicade',
     'Remifentanyl Hydrochloride',
     'Reminyl',
     'Renagel',
     'Renvela',
     'Reopro',
     'Repaglinide',
     'Repevax',
     'Replenine-Vf',
     'Requip',
     'Resolor',
     'Resolve',
     'Resolve Extra',
     'Respontin',
     'Restandol',
     'Retalzem',
     'Retapamulin',
     'Reteplase',
     'Retigabine',
     'Retin-A',
     'Retrovir',
     'Revatio',
     'Revaxis',
     'Revlimid',
     'Rexocaine',
     'Reyataz',
     'Rhinocort',
     'Rhinolast',
     'Rhophylac',
     'Rhumalgan',
     'Riamet',
     'Rifabutin',
     'Rifadin',
     'Rifampicin',
     'Rifater',
     'Rifinah',
     'Rilutek',
     'Riluzole',
     'Rimactane',
     'Rimexolone',
     'Rinatec',
     'Rinstead Sugar Free Pastilles',
     'Risedronate Sodium',
     'Risedronate Sodium/Colecalciferol/Calcium Carbonate',
     'Risperdal',
     'Risperidone',
     'Ritalin',
     'Ritonavir',
     'Rituximab',
     'Rivaroxaban',
     'Rivastigmine',
     'Rivastigmine Hydrogen Tartrate',
     'Rivotril',
     'Rizatriptan Benzoate',
     'Roaccutane',
     'Roactemra',
     'Robinul',
     'Robinul-Neostigmine',
     'Robitussin Chesty Cough',
     'Robitussin Chesty Cough With Congestion',
     'Robitussin Dry Cough Medicine',
     'Rocaltrol',
     'Rocephin',
     'Rocuronium Bromide',
     'Roferon-A',
     'Roflumilast',
     'Ropinirole Hydrochloride',
     'Ropivacaine Hydrochloride',
     'Rosiced',
     'Rosuvastatin',
     'Rotarix',
     'Rotigotine',
     'Rozex',
     'Rufinamide',
     'Rupafin',
     'Rupatadine Fumarate',
     'Rynacrom',
     'Rythmodan',
     'Rythmodan Capsules',
     'Sabril',
     'Saflutan',
     'Saizen',
     'Salactol Paint',
     'Salagen',
     'Salatac Gel',
     'Salazopyrin',
     'Salbutamol',
     'Salicylic Acid',
     'Salicylic Acid Ointment',
     'Salicylic Acid Paint',
     'Salicylic Acid/Camphor',
     'Salicylic Acid/Coal Tar/Sulphur',
     'Salicylic Acid/Dithranol',
     'Salicylic Acid/Lactic Acid',
     'Salicylic Acid/Menthol/Ammonium Salicylate/Camphor',
     'Salicylic Acid/Mucopolysaccharide Polysulphate',
     'Salicylic Acid/Rhubarb Extract',
     'Salmeterol',
     'Salofalk',
     'Sandimmun',
     'Sandocal',
     'Sandocal+D',
     'Sandoglobulin Nf',
     'Sandostatin',
     'Sandrena',
     'Sanomigran',
     'Saquinavir Mesilate',
     'Savlon Antiseptic Cream',
     'Savlon Antiseptic Liquid',
     'Savlon Antiseptic Wound Wash',
     'Savlon Bites And Stings Pain Relief Gel',
     'Savlon Dry Spray',
     'Scheriproct',
     'Scholl Athletes Foot Cream',
     'Scholl Athletes Foot Powder',
     'Scholl Callous Removal Pads',
     'Scholl Corn And Callus Removal Liquid',
     'Scholl Corn Removal Plasters (Fabric)',
     'Scholl Corn Removal Plasters (Washproof)',
     'Scholl Polymer Gel Corn Removal Pads',
     'Scholl Seal And Heal Verruca Removal Gel',
     'Scopoderm Tts',
     'Sea-Legs Tablets',
     'Sebivo',
     'Sebomin',
     'Sebren',
     'Sectral',
     'Securon',
     'Selectajet Dopamine',
     'Selegiline Hydrochloride',
     'Selenium Sulphide',
     'Selexid',
     'Senna Fruit/Ispaghula',
     'Senna Syrup',
     'Senna Tablets',
     'Senna/Buckthorn Bark/Psyllium Seeds',
     'Senokot Comfort Tablets',
     'Senokot Dual Relief Tablets',
     'Senokot Hi-Fibre',
     'Senokot Max Strength',
     'Senokot Syrup',
     'Senokot Tablets',
     'Septrin',
     'Seractil',
     'Serc',
     'Serenace',
     'Seretide',
     'Serevent',
     'Seroquel',
     'Seroxat',
     'Sertraline',
     'Sertraline Hydrochloride',
     'Sevelamer Carbonate',
     'Sevelamer Hydrochloride',
     'Sevoflurane',
     'Sildenafil Citrate',
     'Silkis',
     'Silver Nitrate',
     'Simeticone',
     'Simeticone Drops',
     'Simeticone/Loperamide Hydrochloride',
     'Simponi',
     'Simulect',
     'Simvador',
     'Simvastatin',
     'Sinemet',
     'Singulair',
     'Sinthrome',
     'Sinutab Non-Drowsy',
     'Sirolimus',
     'Sitaxentan Sodium',
     'Skelid',
     'Skinoren',
     'Sleepeaze Tablets',
     'Slozem',
     'Sno Tears',
     'Snufflebabe Vapour Rub',
     'Sodiofolin',
     'Sodium Alginate/Calcium Carbonate/Sodium Bicarbonate',
     'Sodium Alginate/Magnesium Alginate',
     'Sodium Alginate/Potassium Bicarbonate',
     'Sodium Aurothiomalate',
     'Sodium Bicarbonate',
     'Sodium Bicarbonate/Citric Acid/Magnesium Sulphate',
     'Sodium Bicarbonate/Dill Seed Oil',
     'Sodium Citrate',
     'Sodium Citrate Compound',
     'Sodium Clodronate',
     'Sodium Cromoglicate',
     'Sodium Feredetate',
     'Sodium Fluoride',
     'Sodium Fluoride/Triclosan',
     'Sodium Fusidate',
     'Sodium Lauryl Ether Sulpho-Succinate/Sodium Lauryl Ether Sulphate',
     'Sodium Oxybate',
     'Sodium Picosulfate',
     'Sodium Pidolate',
     'Sodium Tetradecyl Sulfate',
     'Sodium Valproate',
     'Sofradex Ear/Eye Drops',
     'Solaraze',
     'Solian',
     'Solifenacin Succinate',
     'Solpadeine Headache Soluble Tablets',
     'Solpadeine Headache Tablets',
     'Solpadeine Migraine Ibuprofen And Codeine Tablets',
     'Solu-Cortef',
     'Solu-Medrone',
     'Somatropin',
     'Somatuline',
     'Somavert',
     'Sominex Herbal Tablets',
     'Somnite',
     'Sonata',
     'Sonovue',
     'Sorafenib Tosylate',
     'Sotacor',
     'Sotalol',
     'Sotalol Hydrochloride',
     'Spasmonal',
     'Spasmonal Forte',
     'Spiriva',
     'Spironolactone',
     'Sporanox',
     'Sprycel',
     'Squill/Capsicum',
     'Squill/Pumilio Pine Oil/Ipecacuanha/Liquorice',
     'St. Johns Wort',
     'Stalevo',
     'Stannous Fluoride',
     'Staril',
     'Starlix',
     'Statin',
     'Stavudine',
     'Stelara',
     'Stelazine',
     'Stemetil',
     'Stemetil Tablet',
     'Sterculia',
     'Sterculia/Frangula',
     'Stesolid',
     'Stiemycin',
     'Stilnoct',
     'Strattera',
     'Strepsils',
     'Strepsils Extra Lozenges',
     'Strepsils Orange With Vitamin C',
     'Strepsils Sore Throat And Blocked Nose Lozenges',
     'Streptase',
     'Streptokinase',
     'Stressless Tablets',
     'Stronazon',
     'Strontium Ranelate',
     'Stugeron 15',
     'Sucralfate',
     'Sucrose/Guaifenesin/Cetylpyridinium Chloride/Honey',
     'Sudafed',
     'Sudocrem',
     'Sugammadex Sodium',
     'Sulfadiazine',
     'Sulfamethoxazole/Trimethoprim',
     'Sulfasalazine',
     'Sulphur Hexafluoride',
     'Sulphur/Salicylic Acid',
     'Sulpiride',
     'Sulpor',
     'Sumatriptan',
     'Sumatriptan Succinate',
     'Sunitinib Malate',
     'Supralip',
     'Suprax',
     'Suprecur',
     'Suprefact',
     'Sure-Amp Lidocaine',
     'Surgam',
     'Surmontil',
     'Sustiva',
     'Sutent',
     'Suxamethonium Chloride',
     'Symbicort',
     'Symmetrel',
     'Synarel',
     'Syner-Kinase',
     'Synflorix',
     'Synphase',
     'Syntocinon',
     'Syntometrine',
     'Syprol',
     'Sytron',
     'Tabphyn',
     'Tacrolimus',
     'Tadalafil',
     'Tafluprost',
     'Tagamet',
     'Tambocor',
     'Tamiflu',
     'Tamoxifen Citrate',
     'Tamsulosin Hydrochloride',
     'Tarceva',
     'Targocid',
     'Targretin',
     'Tarivid',
     'Tarivid Injection',
     'Tarka',
     'Tasigna',
     'Tavanic',
     'Tavegil',
     'Taxol',
     'Taxotere',
     'Tazarotene',
     'Tazocin',
     'Tcp Antiseptic Cream',
     'Tcp Antiseptic Liquid',
     'Tcp Antiseptic Ointment',
     'Tcp Sore Throat Lozenges',
     'Tears Naturale',
     'Tegafur/Uracil',
     'Tegretol',
     'Teicoplanin',
     'Telbivudine',
     'Telfast',
     'Telithromycin',
     'Telmisartan',
     'Telzir',
     'Temazepam',
     'Temodal',
     'Temozolomide',
     'Temsirolimus',
     'Tenecteplase',
     'Tenif',
     'Tenofovir Disoproxil Fumarate',
     'Tenoret',
     'Tenoretic',
     'Tenormin',
     'Tenoxicam',
     'Tensipine',
     'Terazosin',
     'Terazosin Hydrochloride',
     'Terbinafine Hydrochloride',
     'Terbutaline',
     'Teriparatide',
     'Tetanus Immunoglobulin Human',
     'Tetracaine Hydrochloride',
     'Tetracycline Hydrochloride',
     'Tetralysal',
     'Teveten',
     'Thelin',
     'Theophylline',
     'Thiopental Sodium',
     'Throaties Strong Original Pastilles',
     'Thurfyl Salicylate/Hexyl Nicotinate/Ethyl Nicotinate',
     'Thwart',
     'Thymoglobuline',
     'Thyrogen',
     'Thyrotropin Alfa',
     'Tiagabine Hydrochloride Monohydrate',
     'Tiaprofenic Acid',
     'Tibolone',
     'Ticagrelor',
     'Ticovac',
     'Tigecycline',
     'Tiger Balm Red',
     'Tiger Balm White',
     'Tilade',
     'Tildiem',
     'Tiloket',
     'Tiloryth',
     'Tiludronate Disodium',
     'Timentin',
     'Timodine',
     'Timolol',
     'Timolol Maleate',
     'Timolol Maleate/Travoprost',
     'Timoptol',
     'Tinidazole',
     'Tinzaparin',
     'Tioconazole',
     'Tioguanine',
     'Tiotropium',
     'Tipranavir',
     'Tirofiban',
     'Tirofiban Hydrochloride',
     'Tixylix Baby Syrup',
     'Tixylix Chesty Cough',
     'Tixylix Dry Cough',
     'Tixylix Honey, Lemon And Glycerol Syrup',
     'Tixylix Toddler Syrup',
     'Tizanidine',
     'Tobi',
     'Tobradex',
     'Tobramycin',
     'Tocilizumab',
     'Toctino',
     'Tolcapone',
     'Tolfenamic Acid',
     'Tolnaftate',
     'Tolnaftate/Benzalkonium Chloride',
     'Tolnaftate/Chlorhexidine',
     'Tolterodine Tartrate',
     'Tomudex',
     'Topal Chewable Tablets',
     'Topamax',
     'Topiramate',
     'Topotecan Hydrochloride',
     'Torasemide',
     'Torem',
     'Toremifene Citrate',
     'Torisel',
     'Toviaz',
     'Tracleer',
     'Tracrium',
     'Tractocile',
     'Tramacet',
     'Tramadol Hydrochloride',
     'Trandolapril',
     'Trandolapril/Verapamil',
     'Trandolapril/Verapamil Hydrochloride',
     'Tranexamic Acid',
     'Transiderm-Nitro',
     'Trasicor',
     'Trasidrex',
     'Trastuzumab',
     'Travatan',
     'Travoprost',
     'Traxam',
     'Trazodone',
     'Trazodone Hydrochloride',
     'Trental',
     'Treosulfan',
     'Tretinoin',
     'Triadene',
     'Triamcinolone',
     'Triamcinolone Acetonide',
     'Triamterene/Hydrochlorothiazide',
     'Triapin',
     'Tridestra',
     'Trifluoperazine Hydrochloride',
     'Trihexyphenidyl Hydrochloride',
     'Trileptal',
     'Trilostane',
     'Trimethoprim',
     'Trimipramine',
     'Trimipramine Maleate',
     'Trimovate',
     'Trinordiol',
     'Trinovum',
     'Tripotassium Dicitratobismuthate',
     'Triptorelin Acetate',
     'Trisenox',
     'Trisequens',
     'Tritace',
     'Trizivir',
     'Trobalt',
     'Tropicamide',
     'Trospium Chloride',
     'Trosyl',
     'Trusopt',
     'Truvada',
     'Tryptophan',
     'Tums Antacid Tablets',
     'Turpentine Oil/Acetic Acid',
     'Turpentine/Dilute Ammonia/Acetic Acid',
     'Twinrix',
     'Tygacil',
     'Tylex',
     'Typherix',
     'Typhim Vi',
     'Typhoid Vaccine',
     'Tyrozets',
     'Tysabri',
     'Tyverb',
     'Ubretid',
     'Uftoral',
     'Ulipristal Acetate',
     'Ultiva',
     'Ultra Chloraseptic Anaesthetic Throat Spray',
     'Ultrabase',
     'Ultramol Soluble Tablets',
     'Undecenoic Acid/Dichlorophen',
     'Unguentum M',
     'Uniroid Hc',
     'Univer',
     'Urdox',
     'Urea',
     'Urea Hydrogen Peroxide',
     'Urea/Lauromacrogols',
     'Urispas',
     'Urokinase',
     'Ursodeoxycholic Acid',
     'Ursofalk',
     'Ursogal',
     'Ustekinumab',
     'Utinor',
     'Utovlan',
     'Vagifem',
     'Valaciclovir Hydrochloride',
     'Valcyte',
     'Valdoxan',
     'Valerian/Hops',
     'Valganciclovir Hydrochloride',
     'Vallergan',
     'Valoid',
     'Valproate Semisodium',
     'Valsartan',
     'Valtrex',
     'Vancomycin Hydrochloride',
     'Vaniqa',
     'Vaqta',
     'Vardenafil Hydrochloride Trihydrate',
     'Varenicline Tartrate',
     'Varicella-Zoster Vaccine',
     'Varilrix',
     'Vascace',
     'Vascalpha',
     'Vasogen',
     'Vectavir',
     'Vectibix',
     'Vecuronium Bromide',
     'Velcade',
     'Velosulin',
     'Vemurafenib',
     'Venlafaxine',
     'Venlafaxine Hydrochloride',
     'Venofer',
     'Ventavis',
     'Ventolin',
     'Vepesid',
     'Vera-Til',
     'Verapamil',
     'Verapamil Hydrochloride',
     'Vermox',
     'Versatis',
     'Vertab',
     'Verteporfin',
     'Vervain/Valerian/Scullcap/Hops',
     'Vervain/Valerian/Scullcap/Hops/Lupulus',
     'Vesanoid',
     'Vesicare',
     'Vexol',
     'Vfend',
     'Viagra',
     'Viatim',
     'Viazem',
     'Vibramycin',
     'Vibramycin-D',
     'Vibrio Cholerae',
     'Vicks Cough Syrup For Chesty Coughs',
     'Vicks Inhaler',
     'Vicks Medinite Syrup',
     'Vicks Sinex Decongestant Nasal Spray',
     'Vicks Sinex Micromist',
     'Vicks Sinex Soother',
     'Vicks Vaporub',
     'Victoza',
     'Victrelis',
     'Videx',
     'Vigabatrin',
     'Vigam',
     'Vildagliptin',
     'Vimovo',
     'Vimpat',
     'Vinblastine',
     'Vinblastine Sulphate',
     'Vincristine Sulphate',
     'Vinflunine Ditartrate',
     'Vinorelbine Tartrate',
     'Viraferon',
     'Viraferonpeg',
     'Viramune',
     'Viramune Suspension',
     'Viread',
     'Viridal',
     'Viscotears',
     'Viskaldix',
     'Visken',
     'Vistide',
     'Visudyne',
     'Vivotif',
     'Volibris',
     'Voltarol',
     'Voltarol Dispersible',
     'Voltarol Emulgel',
     'Voltarol Gel Patch',
     'Voltarol Rapid',
     'Voriconazole',
     'Votrient',
     'Warfarin',
     'Warticon',
     'Wasp-Eze Spray',
     'Waxsol',
     'White Soft Paraffin',
     'White Soft Paraffin/Light Liquid Paraffin',
     'White Soft Paraffin/Liquid Paraffin',
     'Wind-Eze Gel Caps',
     'Wind-Eze Tablets',
     'Windsetlers',
     'Witch Doctor Gel',
     'Witch Hazel Gel',
     'Woodwards Gripe Water',
     'Xalacom',
     'Xalatan',
     'Xamiol',
     'Xanax',
     'Xarelto',
     'Xatral',
     'Xeloda',
     'Xenical',
     'Xeplion',
     'Xigris',
     'Xipamide',
     'Xismox',
     'Xolair',
     'Xylocaine With Adrenaline',
     'Xylometazoline',
     'Xyloproct',
     'Xyrem',
     'Xyzal',
     'Yasmin',
     'Yeast Plasmolysate',
     'Yentreve',
     'Zacin',
     'Zaditen',
     'Zafirlukast',
     'Zaleplon',
     'Zamadol',
     'Zanaflex',
     'Zanamivir',
     'Zanidip',
     'Zantac',
     'Zaponex',
     'Zarontin',
     'Zavedos',
     'Zeasorb',
     'Zebinix',
     'Zeffix',
     'Zelboraf',
     'Zemplar',
     'Zemtard',
     'Zerit',
     'Zestoretic',
     'Zestril',
     'Ziagen',
     'Zibor',
     'Zidoval',
     'Zidovudine',
     'Zimovane',
     'Zinacef',
     'Zinc Oxide/Bismuth Subgallate/Peru Balsam/Bismuth Oxide',
     'Zinc Oxide/Cod Liver Oil',
     'Zinc Oxide/Lidocaine',
     'Zinc Oxide/Lidocaine/Benzoic Acid/Cinnamic Acid/Bismuth Oxide',
     'Zinc Oxide/Peru Balsam/Bismuth Oxide',
     'Zinc Paste/Calamine',
     'Zinc Undecenoate/Undecenoic Acid',
     'Zineryt',
     'Zinnat',
     'Zirtek Allergy Liquid',
     'Zirtek Allergy Tablets',
     'Zispin Soltab',
     'Zithromax',
     'Zocor',
     'Zofran',
     'Zofran Melt',
     'Zofran Suppository',
     'Zoladex',
     'Zoledronic Acid Monohydrate',
     'Zolmitriptan',
     'Zolpidem',
     'Zolpidem Tartrate',
     'Zolvera',
     'Zomacton',
     'Zomig',
     'Zonegran',
     'Zonisamide',
     'Zopiclone',
     'Zorac',
     'Zoton',
     'Zovirax',
     'Zovirax I.V.',
     'Zuclopenthixol Acetate',
     'Zuclopenthixol Decanoate',
     'Zuclopenthixol Dihydrochloride',
     'Zumenon',
     'Zyban',
     'Zyloric',
     'Zyomet',
     'Zypadhera',
     'Zyprexa',
     'Zyvox'
     ]

