# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openmolar/openmolar/qt-designer/estimateItemWidget.ui'
#
# Created: Tue Jun 16 11:00:56 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(773, 28)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.number_lineEdit = QtGui.QLineEdit(Form)
        self.number_lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_lineEdit.sizePolicy().hasHeightForWidth())
        self.number_lineEdit.setSizePolicy(sizePolicy)
        self.number_lineEdit.setMinimumSize(QtCore.QSize(0, 23))
        self.number_lineEdit.setMaximumSize(QtCore.QSize(32, 16777215))
        self.number_lineEdit.setMaxLength(2)
        self.number_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.number_lineEdit.setObjectName("number_lineEdit")
        self.horizontalLayout.addWidget(self.number_lineEdit)
        self.itemCode_label = QtGui.QLabel(Form)
        self.itemCode_label.setMinimumSize(QtCore.QSize(50, 0))
        self.itemCode_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.itemCode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.itemCode_label.setObjectName("itemCode_label")
        self.horizontalLayout.addWidget(self.itemCode_label)
        self.description_lineEdit = QtGui.QLineEdit(Form)
        self.description_lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.description_lineEdit.setMaxLength(50)
        self.description_lineEdit.setObjectName("description_lineEdit")
        self.horizontalLayout.addWidget(self.description_lineEdit)
        self.code_label = QtGui.QLabel(Form)
        self.code_label.setMinimumSize(QtCore.QSize(50, 0))
        self.code_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.code_label.setAlignment(QtCore.Qt.AlignCenter)
        self.code_label.setObjectName("code_label")
        self.horizontalLayout.addWidget(self.code_label)
        self.cset_lineEdit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cset_lineEdit.sizePolicy().hasHeightForWidth())
        self.cset_lineEdit.setSizePolicy(sizePolicy)
        self.cset_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cset_lineEdit.setMaxLength(1)
        self.cset_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cset_lineEdit.setObjectName("cset_lineEdit")
        self.horizontalLayout.addWidget(self.cset_lineEdit)
        self.fee_lineEdit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fee_lineEdit.sizePolicy().hasHeightForWidth())
        self.fee_lineEdit.setSizePolicy(sizePolicy)
        self.fee_lineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.fee_lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.fee_lineEdit.setMaxLength(7)
        self.fee_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fee_lineEdit.setObjectName("fee_lineEdit")
        self.horizontalLayout.addWidget(self.fee_lineEdit)
        self.label = QtGui.QLabel(Form)
        self.label.setPixmap(QtGui.QPixmap(":/icons/chain.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ptFee_lineEdit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ptFee_lineEdit.sizePolicy().hasHeightForWidth())
        self.ptFee_lineEdit.setSizePolicy(sizePolicy)
        self.ptFee_lineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.ptFee_lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.ptFee_lineEdit.setMaxLength(7)
        self.ptFee_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ptFee_lineEdit.setObjectName("ptFee_lineEdit")
        self.horizontalLayout.addWidget(self.ptFee_lineEdit)
        self.completed_checkBox = QtGui.QCheckBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completed_checkBox.sizePolicy().hasHeightForWidth())
        self.completed_checkBox.setSizePolicy(sizePolicy)
        self.completed_checkBox.setObjectName("completed_checkBox")
        self.horizontalLayout.addWidget(self.completed_checkBox)
        self.delete_pushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_pushButton.sizePolicy().hasHeightForWidth())
        self.delete_pushButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_pushButton.setIcon(icon)
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.horizontalLayout.addWidget(self.delete_pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.itemCode_label.setText(QtGui.QApplication.translate("Form", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.description_lineEdit.setText(QtGui.QApplication.translate("Form", "small xrays", None, QtGui.QApplication.UnicodeUTF8))
        self.code_label.setText(QtGui.QApplication.translate("Form", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.cset_lineEdit.setText(QtGui.QApplication.translate("Form", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.fee_lineEdit.setText(QtGui.QApplication.translate("Form", "1000.00", None, QtGui.QApplication.UnicodeUTF8))
        self.ptFee_lineEdit.setText(QtGui.QApplication.translate("Form", "1000.00", None, QtGui.QApplication.UnicodeUTF8))
        self.completed_checkBox.setText(QtGui.QApplication.translate("Form", "Completed", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
