# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openmolar/openmolar/qt-designer/toothPerioProps.ui'
#
# Created: Sun Apr  5 19:09:30 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(144, 399)
        Form.setMinimumSize(QtCore.QSize(0, 350))
        Form.setMaximumSize(QtCore.QSize(16777215, 517))
        self.gridLayout_3 = QtGui.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tooth_label = QtGui.QLabel(Form)
        self.tooth_label.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tooth_label.setFont(font)
        self.tooth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tooth_label.setObjectName("tooth_label")
        self.gridLayout_3.addWidget(self.tooth_label, 0, 0, 1, 2)
        self.orig_frame = QtGui.QFrame(Form)
        self.orig_frame.setMinimumSize(QtCore.QSize(100, 100))
        self.orig_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.orig_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.orig_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.orig_frame.setObjectName("orig_frame")
        self.gridLayout_3.addWidget(self.orig_frame, 1, 0, 1, 2)
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.comboBox, 2, 0, 1, 2)
        self.new_frame = QtGui.QFrame(Form)
        self.new_frame.setMinimumSize(QtCore.QSize(100, 100))
        self.new_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.new_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.new_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.new_frame.setObjectName("new_frame")
        self.gridLayout_3.addWidget(self.new_frame, 3, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftTooth_pushButton = QtGui.QPushButton(Form)
        self.leftTooth_pushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.leftTooth_pushButton.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftTooth_pushButton.setIcon(icon)
        self.leftTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.leftTooth_pushButton.setObjectName("leftTooth_pushButton")
        self.horizontalLayout.addWidget(self.leftTooth_pushButton)
        self.le_frame = QtGui.QFrame(Form)
        self.le_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.le_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.le_frame.setObjectName("le_frame")
        self.horizontalLayout.addWidget(self.le_frame)
        self.rightTooth_pushButton = QtGui.QPushButton(Form)
        self.rightTooth_pushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.rightTooth_pushButton.setMaximumSize(QtCore.QSize(24, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTooth_pushButton.setIcon(icon1)
        self.rightTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.rightTooth_pushButton.setObjectName("rightTooth_pushButton")
        self.horizontalLayout.addWidget(self.rightTooth_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.copy_pushButton = QtGui.QPushButton(Form)
        self.copy_pushButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.copy_pushButton.setObjectName("copy_pushButton")
        self.gridLayout_3.addWidget(self.copy_pushButton, 5, 0, 1, 1)
        self.cp_pushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cp_pushButton.sizePolicy().hasHeightForWidth())
        self.cp_pushButton.setSizePolicy(sizePolicy)
        self.cp_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.cp_pushButton.setMaximumSize(QtCore.QSize(40, 28))
        self.cp_pushButton.setObjectName("cp_pushButton")
        self.gridLayout_3.addWidget(self.cp_pushButton, 5, 1, 1, 1)
        self.mobilitycomboBox = QtGui.QComboBox(Form)
        self.mobilitycomboBox.setMaximumSize(QtCore.QSize(16777215, 28))
        self.mobilitycomboBox.setObjectName("mobilitycomboBox")
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.mobilitycomboBox, 6, 0, 1, 1)
        self.clear_pushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_pushButton.sizePolicy().hasHeightForWidth())
        self.clear_pushButton.setSizePolicy(sizePolicy)
        self.clear_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.clear_pushButton.setMaximumSize(QtCore.QSize(40, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_pushButton.setIcon(icon2)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout_3.addWidget(self.clear_pushButton, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tooth_label.setText(QtGui.QApplication.translate("Form", "ToothId", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "Pocketing", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "Bleeding", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Form", "Plaque", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Form", "Recession", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("Form", "Furcation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("Form", "Suppuration", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("Form", "Mobility", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("Form", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTooth_pushButton.setToolTip(QtGui.QApplication.translate("Form", "Apply and move Back a tooth", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTooth_pushButton.setToolTip(QtGui.QApplication.translate("Form", "Apply & Move to Next Tooth", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_pushButton.setText(QtGui.QApplication.translate("Form", "Copy &All", None, QtGui.QApplication.UnicodeUTF8))
        self.cp_pushButton.setToolTip(QtGui.QApplication.translate("Form", "delete tooth data", None, QtGui.QApplication.UnicodeUTF8))
        self.cp_pushButton.setText(QtGui.QApplication.translate("Form", "Cp", None, QtGui.QApplication.UnicodeUTF8))
        self.mobilitycomboBox.setItemText(0, QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.mobilitycomboBox.setItemText(1, QtGui.QApplication.translate("Form", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.mobilitycomboBox.setItemText(2, QtGui.QApplication.translate("Form", "II", None, QtGui.QApplication.UnicodeUTF8))
        self.mobilitycomboBox.setItemText(3, QtGui.QApplication.translate("Form", "III", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_pushButton.setToolTip(QtGui.QApplication.translate("Form", "delete tooth data", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
