#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'openmolar',
 'build_date': '2009-09-02 10:31:02 +0100',
 'clean': None,
 'date': '2009-09-02 10:26:26 +0100',
 'revision_id': 'rowinggolfer@googlemail.com-20090902092626-9iqx7cs0n0f8xcbz',
 'revno': 307}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
