#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'openmolar',
 'build_date': '2009-11-16 12:52:59 +0000',
 'clean': None,
 'date': '2009-11-16 09:19:01 +0000',
 'revision_id': 'rowinggolfer@googlemail.com-20091116091901-kks2vfld61gm3l54',
 'revno': 460}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
