#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'openmolar',
 'build_date': '2009-11-11 01:27:17 +0000',
 'clean': None,
 'date': '2009-11-10 15:28:41 +0000',
 'revision_id': 'rowinggolfer@googlemail.com-20091110152841-7vz26o6qarzk19pu',
 'revno': 444}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
