# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exam_wizard.ui'
#
# Created: Wed Nov 18 23:32:56 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(332, 320)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.examA_radioButton = QtGui.QRadioButton(Dialog)
        self.examA_radioButton.setChecked(True)
        self.examA_radioButton.setObjectName("examA_radioButton")
        self.verticalLayout.addWidget(self.examA_radioButton)
        self.examB_radioButton = QtGui.QRadioButton(Dialog)
        self.examB_radioButton.setObjectName("examB_radioButton")
        self.verticalLayout.addWidget(self.examB_radioButton)
        self.examC_radioButton = QtGui.QRadioButton(Dialog)
        self.examC_radioButton.setObjectName("examC_radioButton")
        self.verticalLayout.addWidget(self.examC_radioButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 2, 3)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 3, 2, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dateEdit = QtGui.QDateEdit(Dialog)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_3.addWidget(self.dateEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 4, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dents_comboBox = QtGui.QComboBox(Dialog)
        self.dents_comboBox.setObjectName("dents_comboBox")
        self.verticalLayout_2.addWidget(self.dents_comboBox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 4, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 5)
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 5)
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 4, 0, 1, 1)
        self.co_comboBox = QtGui.QComboBox(Dialog)
        self.co_comboBox.setObjectName("co_comboBox")
        self.co_comboBox.addItem("")
        self.co_comboBox.addItem("")
        self.co_comboBox.addItem("")
        self.co_comboBox.addItem("")
        self.co_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.co_comboBox, 4, 1, 1, 4)
        self.softTissues_checkBox = QtGui.QCheckBox(Dialog)
        self.softTissues_checkBox.setObjectName("softTissues_checkBox")
        self.gridLayout_2.addWidget(self.softTissues_checkBox, 5, 0, 1, 5)
        self.oh_checkBox = QtGui.QCheckBox(Dialog)
        self.oh_checkBox.setObjectName("oh_checkBox")
        self.gridLayout_2.addWidget(self.oh_checkBox, 6, 0, 1, 5)
        self.canines_checkBox = QtGui.QCheckBox(Dialog)
        self.canines_checkBox.setObjectName("canines_checkBox")
        self.gridLayout_2.addWidget(self.canines_checkBox, 7, 0, 1, 5)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 8, 0, 1, 5)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_( u"Exam Wizard"))
        self.label.setText(_( u"Type"))
        self.examA_radioButton.setText(_( u"Standard"))
        self.examB_radioButton.setText(_( u"Extensive"))
        self.examC_radioButton.setText(_( u"Full Case Assessment"))
        self.label_3.setText(_( u"Exam Date"))
        self.label_2.setText(_( u"Dentist"))
        self.label_5.setText(_( u"Notes"))
        self.checkBox.setText(_( u"Pt c/o"))
        self.co_comboBox.setItemText(0, _( u"nil"))
        self.co_comboBox.setItemText(1, _( u"Broken Tooth"))
        self.co_comboBox.setItemText(2, _( u"Pain"))
        self.co_comboBox.setItemText(3, _( u"Denture Problems"))
        self.co_comboBox.setItemText(4, _( u"Sensitive Teeth"))
        self.softTissues_checkBox.setText(_( u"Soft Tissues Checked"))
        self.oh_checkBox.setText(_( u"OHI given"))
        self.canines_checkBox.setText(_( u"Palpated for upper canines - NAD"))

