# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar/src/openmolar/qt-designer/fee_item_wizard.ui'
#
# Created: Sun Mar 14 22:33:02 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(770, 596)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.itemcode_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.itemcode_label.setFont(font)
        self.itemcode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.itemcode_label.setObjectName("itemcode_label")
        self.gridLayout_5.addWidget(self.itemcode_label, 0, 0, 1, 3)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.usercode_plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.usercode_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.usercode_plainTextEdit.setObjectName("usercode_plainTextEdit")
        self.gridLayout_2.addWidget(self.usercode_plainTextEdit, 0, 1, 4, 1)
        self.uc_radioButton = QtGui.QRadioButton(self.tab)
        self.uc_radioButton.setObjectName("uc_radioButton")
        self.gridLayout_2.addWidget(self.uc_radioButton, 1, 0, 1, 1)
        self.uc_reg_radioButton = QtGui.QRadioButton(self.tab)
        self.uc_reg_radioButton.setObjectName("uc_reg_radioButton")
        self.gridLayout_2.addWidget(self.uc_reg_radioButton, 2, 0, 1, 1)
        self.uc_multireg_radioButton = QtGui.QRadioButton(self.tab)
        self.uc_multireg_radioButton.setObjectName("uc_multireg_radioButton")
        self.gridLayout_2.addWidget(self.uc_multireg_radioButton, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.regulations_plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.regulations_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.regulations_plainTextEdit.setObjectName("regulations_plainTextEdit")
        self.gridLayout_3.addWidget(self.regulations_plainTextEdit, 0, 1, 2, 1)
        self.regwizard_pushButton = QtGui.QPushButton(self.tab)
        self.regwizard_pushButton.setObjectName("regwizard_pushButton")
        self.gridLayout_3.addWidget(self.regwizard_pushButton, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtGui.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.category_comboBox = QtGui.QComboBox(self.tab)
        self.category_comboBox.setObjectName("category_comboBox")
        self.horizontalLayout_5.addWidget(self.category_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.pl_cmp_comboBox = QtGui.QComboBox(self.tab)
        self.pl_cmp_comboBox.setObjectName("pl_cmp_comboBox")
        self.horizontalLayout_4.addWidget(self.pl_cmp_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.description_lineEdit = QtGui.QLineEdit(self.tab)
        self.description_lineEdit.setObjectName("description_lineEdit")
        self.gridLayout.addWidget(self.description_lineEdit, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.descriptions_plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.descriptions_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.descriptions_plainTextEdit.setObjectName("descriptions_plainTextEdit")
        self.gridLayout.addWidget(self.descriptions_plainTextEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.fees_lineEdit = QtGui.QLineEdit(self.tab)
        self.fees_lineEdit.setObjectName("fees_lineEdit")
        self.gridLayout_4.addWidget(self.fees_lineEdit, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.pt_fees_lineEdit = QtGui.QLineEdit(self.tab)
        self.pt_fees_lineEdit.setObjectName("pt_fees_lineEdit")
        self.gridLayout_4.addWidget(self.pt_fees_lineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.splitter = QtGui.QSplitter(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.orig_xml_plainTextEdit = QtGui.QPlainTextEdit(self.widget)
        self.orig_xml_plainTextEdit.setEnabled(True)
        self.orig_xml_plainTextEdit.setReadOnly(True)
        self.orig_xml_plainTextEdit.setObjectName("orig_xml_plainTextEdit")
        self.verticalLayout_2.addWidget(self.orig_xml_plainTextEdit)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtGui.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.xml_plainTextEdit = QtGui.QPlainTextEdit(self.widget1)
        self.xml_plainTextEdit.setObjectName("xml_plainTextEdit")
        self.verticalLayout_3.addWidget(self.xml_plainTextEdit)
        self.verticalLayout_4.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 3)
        self.test_pushButton = QtGui.QPushButton(Dialog)
        self.test_pushButton.setObjectName("test_pushButton")
        self.gridLayout_5.addWidget(self.test_pushButton, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(317, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_( u"Dialog"))
        self.itemcode_label.setText(_( u"TextLabel"))
        self.label_3.setText(_( u"UserCode"))
        self.uc_radioButton.setText(_( u"Standard"))
        self.uc_reg_radioButton.setText(_( u"Regex"))
        self.uc_multireg_radioButton.setText(_( u"Multiple Regex"))
        self.label_6.setText(_( u"Regulations"))
        self.regwizard_pushButton.setText(_( u"Regulation Wizard"))
        self.label.setText(_( u"Feescale Category"))
        self.label_4.setText(_( u"Category for treatment Planning"))
        self.label_5.setText(_( u"Patient\'s Description"))
        self.label_9.setText(_( u"Clinical Description(s)"))
        self.label_7.setText(_( u"Gross Fees (csv)"))
        self.label_8.setText(_( u"Net Fees (csv)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _( u"Wizard"))
        self.label_2.setText(_( u"Below is the XML for this item (this is how they are stored in the database)"))
        self.label_10.setText(_( u"Original (read only)"))
        self.label_11.setText(_( u"New"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _( u"XML"))
        self.test_pushButton.setText(_( u"Test Fee Item Logic"))

