# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar/src/openmolar/qt-designer/fee_item_wizard.ui'
#
# Created: Wed Mar 10 12:38:53 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 618)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.itemcode_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.itemcode_label.setFont(font)
        self.itemcode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.itemcode_label.setObjectName("itemcode_label")
        self.verticalLayout_2.addWidget(self.itemcode_label)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.usercode_lineEdit = QtGui.QLineEdit(self.tab)
        self.usercode_lineEdit.setObjectName("usercode_lineEdit")
        self.gridLayout_2.addWidget(self.usercode_lineEdit, 0, 1, 1, 3)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.uc_radioButton = QtGui.QRadioButton(self.tab)
        self.uc_radioButton.setObjectName("uc_radioButton")
        self.gridLayout_2.addWidget(self.uc_radioButton, 1, 1, 1, 1)
        self.uc_reg_radioButton = QtGui.QRadioButton(self.tab)
        self.uc_reg_radioButton.setObjectName("uc_reg_radioButton")
        self.gridLayout_2.addWidget(self.uc_reg_radioButton, 1, 2, 1, 1)
        self.uc_multireg_radioButton = QtGui.QRadioButton(self.tab)
        self.uc_multireg_radioButton.setObjectName("uc_multireg_radioButton")
        self.gridLayout_2.addWidget(self.uc_multireg_radioButton, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.regulations_lineEdit = QtGui.QLineEdit(self.tab)
        self.regulations_lineEdit.setObjectName("regulations_lineEdit")
        self.horizontalLayout.addWidget(self.regulations_lineEdit)
        self.regwizard_pushButton = QtGui.QPushButton(self.tab)
        self.regwizard_pushButton.setObjectName("regwizard_pushButton")
        self.horizontalLayout.addWidget(self.regwizard_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtGui.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.category_comboBox = QtGui.QComboBox(self.tab)
        self.category_comboBox.setObjectName("category_comboBox")
        self.horizontalLayout_5.addWidget(self.category_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.pl_cmp_comboBox = QtGui.QComboBox(self.tab)
        self.pl_cmp_comboBox.setObjectName("pl_cmp_comboBox")
        self.horizontalLayout_4.addWidget(self.pl_cmp_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.description_lineEdit = QtGui.QLineEdit(self.tab)
        self.description_lineEdit.setObjectName("description_lineEdit")
        self.gridLayout.addWidget(self.description_lineEdit, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 2)
        self.descriptions_listWidget = QtGui.QListWidget(self.tab)
        self.descriptions_listWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.descriptions_listWidget.setObjectName("descriptions_listWidget")
        self.gridLayout.addWidget(self.descriptions_listWidget, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 2)
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 2)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.xml_plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.xml_plainTextEdit.setObjectName("xml_plainTextEdit")
        self.verticalLayout_3.addWidget(self.xml_plainTextEdit)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_( u"Dialog"))
        self.itemcode_label.setText(_( u"TextLabel"))
        self.label_3.setText(_( u"UserCode"))
        self.label_10.setText(_( u"UserCode Type"))
        self.uc_radioButton.setText(_( u"Standard"))
        self.uc_reg_radioButton.setText(_( u"Regex"))
        self.uc_multireg_radioButton.setText(_( u"Multiple Regex"))
        self.label_6.setText(_( u"Regulation"))
        self.regwizard_pushButton.setText(_( u"Regulation Wizard"))
        self.label.setText(_( u"Category"))
        self.label_4.setText(_( u"Category for treatment Planning"))
        self.label_5.setText(_( u"Patient\'s Description"))
        self.label_9.setText(_( u"Clinical Descriptions"))
        self.label_7.setText(_( u"Gross Fees (csv)"))
        self.label_8.setText(_( u"Net Fees (csv)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _( u"Wizard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _( u"XML"))

