# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initialise.ui'
#
# Created: Wed Jan 13 11:44:45 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 476)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtGui.QLabel(self.tab_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 2)
        self.modifydb_radioButton = QtGui.QRadioButton(self.tab_8)
        self.modifydb_radioButton.setEnabled(False)
        self.modifydb_radioButton.setObjectName("modifydb_radioButton")
        self.gridLayout_3.addWidget(self.modifydb_radioButton, 4, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab_8)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 4, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab_8)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 5, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 407, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 1, 1, 1)
        self.blankdb_radioButton = QtGui.QRadioButton(self.tab_8)
        self.blankdb_radioButton.setChecked(True)
        self.blankdb_radioButton.setObjectName("blankdb_radioButton")
        self.gridLayout_3.addWidget(self.blankdb_radioButton, 2, 0, 1, 1)
        self.newdb_template_radioButton = QtGui.QRadioButton(self.tab_8)
        self.newdb_template_radioButton.setChecked(False)
        self.newdb_template_radioButton.setObjectName("newdb_template_radioButton")
        self.gridLayout_3.addWidget(self.newdb_template_radioButton, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.practice_frame = QtGui.QFrame(self.tab)
        self.practice_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.practice_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.practice_frame.setObjectName("practice_frame")
        self.gridLayout = QtGui.QGridLayout(self.practice_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.practice_frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.practice_frame)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.practice_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.practice_frame)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.practice_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.practice_frame)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.practice_frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.practice_frame)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.practice_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.practice_frame)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.practice_frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.practice_frame)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 5, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.practice_frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.practice_frame)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.practice_frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 7, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.practice_frame)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 7, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.practice_frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 8, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.practice_frame)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 8, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.practice_frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 9, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.practice_frame)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 9, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.practice_frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 10, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.practice_frame)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 10, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.practice_frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 2, 1, 2)
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.frame_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 3, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.frame_2)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 3, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_33 = QtGui.QLabel(self.tab_3)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        self.frame_3 = QtGui.QFrame(self.tab_3)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_29 = QtGui.QLabel(self.frame_3)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_7.addWidget(self.label_29)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_30 = QtGui.QLabel(self.frame_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_4.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.frame_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 1, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_4.addWidget(self.lineEdit_15, 1, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.frame_3)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 2, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_4.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.checkBox_2 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_7.addWidget(self.checkBox_2)
        self.checkBox_5 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_7.addWidget(self.checkBox_5)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_38 = QtGui.QLabel(self.tab_4)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_4.addWidget(self.label_38)
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.tableWidget_3)
        self.frame_4 = QtGui.QFrame(self.tab_4)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_32 = QtGui.QLabel(self.frame_4)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_8.addWidget(self.label_32)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_34 = QtGui.QLabel(self.frame_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 0, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_5.addWidget(self.lineEdit_16, 0, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 1, 0, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_5.addWidget(self.lineEdit_17, 1, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.frame_4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 2, 0, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_5.addWidget(self.lineEdit_22, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.checkBox_3 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_8.addWidget(self.checkBox_3)
        self.checkBox_6 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_8.addWidget(self.checkBox_6)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_6 = QtGui.QFrame(self.tab_5)
        self.frame_6.setGeometry(QtCore.QRect(30, 30, 206, 224))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_7 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_7.addWidget(self.checkBox_7, 0, 0, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_7.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.timeEdit_2 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_7.addWidget(self.timeEdit_2, 0, 2, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_7.addWidget(self.checkBox_8, 1, 0, 1, 1)
        self.timeEdit_3 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout_7.addWidget(self.timeEdit_3, 1, 1, 1, 1)
        self.timeEdit_4 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout_7.addWidget(self.timeEdit_4, 1, 2, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_7.addWidget(self.checkBox_9, 2, 0, 1, 1)
        self.timeEdit_5 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.gridLayout_7.addWidget(self.timeEdit_5, 2, 1, 1, 1)
        self.timeEdit_6 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.gridLayout_7.addWidget(self.timeEdit_6, 2, 2, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_7.addWidget(self.checkBox_10, 3, 0, 1, 1)
        self.timeEdit_7 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.gridLayout_7.addWidget(self.timeEdit_7, 3, 1, 1, 1)
        self.timeEdit_8 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_8.setObjectName("timeEdit_8")
        self.gridLayout_7.addWidget(self.timeEdit_8, 3, 2, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_7.addWidget(self.checkBox_11, 4, 0, 1, 1)
        self.timeEdit_10 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_10.setObjectName("timeEdit_10")
        self.gridLayout_7.addWidget(self.timeEdit_10, 4, 1, 1, 1)
        self.timeEdit_11 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_11.setObjectName("timeEdit_11")
        self.gridLayout_7.addWidget(self.timeEdit_11, 4, 2, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_7.addWidget(self.checkBox_12, 5, 0, 1, 1)
        self.timeEdit_12 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_12.setObjectName("timeEdit_12")
        self.gridLayout_7.addWidget(self.timeEdit_12, 5, 1, 1, 1)
        self.timeEdit_9 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_9.setObjectName("timeEdit_9")
        self.gridLayout_7.addWidget(self.timeEdit_9, 5, 2, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_7.addWidget(self.checkBox_13, 6, 0, 1, 1)
        self.timeEdit_13 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_13.setObjectName("timeEdit_13")
        self.gridLayout_7.addWidget(self.timeEdit_13, 6, 1, 1, 1)
        self.timeEdit_14 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_14.setObjectName("timeEdit_14")
        self.gridLayout_7.addWidget(self.timeEdit_14, 6, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_43 = QtGui.QLabel(self.tab_9)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_6.addWidget(self.label_43)
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_9)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.verticalLayout_6.addWidget(self.tableWidget_4)
        self.frame_5 = QtGui.QFrame(self.tab_9)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_39 = QtGui.QLabel(self.frame_5)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.frame_5)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 3, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_6.addWidget(self.lineEdit_18, 3, 1, 1, 4)
        self.label_41 = QtGui.QLabel(self.frame_5)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 4, 0, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_6.addWidget(self.lineEdit_19, 4, 1, 1, 3)
        self.pushButton = QtGui.QPushButton(self.frame_5)
        self.pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 4, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 4, 5, 1, 1)
        self.label_42 = QtGui.QLabel(self.frame_5)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 5, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.frame_5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_5, 5, 1, 1, 2)
        self.spinBox_2 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_6.addWidget(self.spinBox_2, 5, 3, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.frame_5)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_6.addWidget(self.spinBox, 5, 4, 1, 1)
        self.label_44 = QtGui.QLabel(self.frame_5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 1, 0, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_20.setMaxLength(1)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_6.addWidget(self.lineEdit_20, 1, 1, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.frame_5)
        self.checkBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_6.addWidget(self.checkBox_4, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xml_label = QtGui.QLabel(self.tab_7)
        self.xml_label.setTextFormat(QtCore.Qt.PlainText)
        self.xml_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.xml_label.setWordWrap(True)
        self.xml_label.setObjectName("xml_label")
        self.horizontalLayout.addWidget(self.xml_label)
        self.tabWidget.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Template = QtGui.QAction(MainWindow)
        self.actionLoad_Template.setObjectName("actionLoad_Template")
        self.action_Save_Template = QtGui.QAction(MainWindow)
        self.action_Save_Template.setObjectName("action_Save_Template")
        self.menuFile.addAction(self.actionLoad_Template)
        self.menuFile.addAction(self.action_Save_Template)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_( u"OpenMolar - database wizard"))
        self.label_17.setText(_( u"What do you want to do?"))
        self.modifydb_radioButton.setText(_( u"Modify an existing openmolar database"))
        self.blankdb_radioButton.setText(_( u"Create a New database from scratch"))
        self.newdb_template_radioButton.setText(_( u"Create a New database (from a known template)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _( u"Start"))
        self.label.setText(_( u"Practice Name"))
        self.label_18.setText(_( u"Used in receipts, appointment cards etc."))
        self.label_2.setText(_( u"Address Line 1"))
        self.label_3.setText(_( u"Address Line 2"))
        self.label_4.setText(_( u"Address Line 3"))
        self.label_5.setText(_( u"Town"))
        self.label_6.setText(_( u"County"))
        self.label_7.setText(_( u"Postcode / Zip"))
        self.label_8.setText(_( u"Telephone"))
        self.label_9.setText(_( u"Fax"))
        self.label_10.setText(_( u"Website"))
        self.label_11.setText(_( u"Email"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _( u"Practice Details"))
        self.label_12.setText(_( u"The Following users can login to the application"))
        self.tableWidget.horizontalHeaderItem(0).setText(_( u"Initials"))
        self.tableWidget.horizontalHeaderItem(1).setText(_( u"Name"))
        self.tableWidget.horizontalHeaderItem(2).setText(_( u"User Group"))
        self.tableWidget.horizontalHeaderItem(3).setText(_( u"Active?"))
        self.label_16.setText(_( u"Add a User"))
        self.label_13.setText(_( u"Initials"))
        self.label_14.setText(_( u"Name"))
        self.label_15.setText(_( u"User Group"))
        self.comboBox_2.setItemText(0, _( u"Standard User"))
        self.comboBox_2.setItemText(1, _( u"Dentist"))
        self.comboBox_2.setItemText(2, _( u"Hygienist"))
        self.comboBox_2.setItemText(3, _( u"Receptionist"))
        self.checkBox.setText(_( u"Active User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _( u"Users"))
        self.label_33.setText(_( u"The Following dentists have notes in this database\n"
"(note - dentists should not be removed from the database, as this could create lookup issues for cashbooks and notes) "))
        self.tableWidget_2.horizontalHeaderItem(0).setText(_( u"Initials"))
        self.tableWidget_2.horizontalHeaderItem(1).setText(_( u"Name"))
        self.tableWidget_2.horizontalHeaderItem(2).setText(_( u"User Group"))
        self.tableWidget_2.horizontalHeaderItem(3).setText(_( u"Active?"))
        self.label_29.setText(_( u"Add a Dentist"))
        self.label_30.setText(_( u"Initials"))
        self.label_31.setText(_( u"Name"))
        self.label_45.setText(_( u"Registration"))
        self.checkBox_2.setText(_( u"Active Appointment Book"))
        self.checkBox_5.setText(_( u"Patients can be assigned to this dentist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _( u"Dentists"))
        self.label_38.setText(_( u"The Following hygienists have notes in this database\n"
"(note - hygienists should not be removed from the database, as this could create lookup issues for cashbooks and notes) "))
        self.tableWidget_3.horizontalHeaderItem(0).setText(_( u"Initials"))
        self.tableWidget_3.horizontalHeaderItem(1).setText(_( u"Name"))
        self.tableWidget_3.horizontalHeaderItem(2).setText(_( u"User Group"))
        self.tableWidget_3.horizontalHeaderItem(3).setText(_( u"Active?"))
        self.label_32.setText(_( u"Add a Dentist"))
        self.label_34.setText(_( u"Initials"))
        self.label_35.setText(_( u"Name"))
        self.label_46.setText(_( u"Registration"))
        self.checkBox_3.setText(_( u"Active Appointment Book"))
        self.checkBox_6.setText(_( u"Patients can be assigned to this dentist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _( u"Hygienists"))
        self.checkBox_7.setText(_( u"Monday"))
        self.checkBox_8.setText(_( u"Tuesday"))
        self.checkBox_9.setText(_( u"Wednesday"))
        self.checkBox_10.setText(_( u"Thursday"))
        self.checkBox_11.setText(_( u"Friday"))
        self.checkBox_12.setText(_( u"Saturday"))
        self.checkBox_13.setText(_( u"Sunday"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _( u"Practice Hours"))
        self.label_43.setText(_( u"The Following Categories are used in this database"))
        self.tableWidget_4.horizontalHeaderItem(0).setText(_( u"Category"))
        self.tableWidget_4.horizontalHeaderItem(1).setText(_( u"Category Name"))
        self.tableWidget_4.horizontalHeaderItem(2).setText(_( u"Image"))
        self.tableWidget_4.horizontalHeaderItem(3).setText(_( u"Age Category"))
        self.tableWidget_4.horizontalHeaderItem(4).setText(_( u"Minimum Age"))
        self.tableWidget_4.horizontalHeaderItem(5).setText(_( u"Maximum Age"))
        self.label_39.setText(_( u"Add a Category"))
        self.label_40.setText(_( u"Category Name"))
        self.label_41.setText(_( u"Image"))
        self.pushButton.setText(_( u"..."))
        self.label_42.setText(_( u"Age Limit"))
        self.comboBox_5.setItemText(0, _( u"None"))
        self.comboBox_5.setItemText(1, _( u"Under 18"))
        self.comboBox_5.setItemText(2, _( u"Adult"))
        self.comboBox_5.setItemText(3, _( u"OAP"))
        self.comboBox_5.setItemText(4, _( u"Other"))
        self.label_44.setText(_( u"Category Letter"))
        self.checkBox_4.setText(_( u"Category Active"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _( u"Patient Categories"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _( u"Treatments and Fees"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _( u"Referral Centres"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _( u"View XML"))
        self.menuFile.setTitle(_( u"File"))
        self.actionLoad_Template.setText(_( u"L&oad Template"))
        self.action_Save_Template.setText(_( u"&Save Template"))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

