# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar1/src/openmolar/qt-designer/initialise.ui'
#
# Created: Wed Nov  6 23:05:24 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 507)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_17 = QtGui.QLabel(self.tab_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 2)
        self.modifydb_radioButton = QtGui.QRadioButton(self.tab_8)
        self.modifydb_radioButton.setEnabled(False)
        self.modifydb_radioButton.setObjectName(_fromUtf8("modifydb_radioButton"))
        self.gridLayout_3.addWidget(self.modifydb_radioButton, 4, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab_8)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_3.addWidget(self.comboBox, 4, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab_8)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 5, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 407, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 1, 1, 1)
        self.blankdb_radioButton = QtGui.QRadioButton(self.tab_8)
        self.blankdb_radioButton.setChecked(True)
        self.blankdb_radioButton.setObjectName(_fromUtf8("blankdb_radioButton"))
        self.gridLayout_3.addWidget(self.blankdb_radioButton, 2, 0, 1, 1)
        self.newdb_template_radioButton = QtGui.QRadioButton(self.tab_8)
        self.newdb_template_radioButton.setChecked(False)
        self.newdb_template_radioButton.setObjectName(_fromUtf8("newdb_template_radioButton"))
        self.gridLayout_3.addWidget(self.newdb_template_radioButton, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.practice_frame = QtGui.QFrame(self.tab)
        self.practice_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.practice_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.practice_frame.setObjectName(_fromUtf8("practice_frame"))
        self.gridLayout = QtGui.QGridLayout(self.practice_frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.practice_frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.practice_frame)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.practice_frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.practice_frame)
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.practice_frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.practice_frame)
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.practice_frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.practice_frame)
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.practice_frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.practice_frame)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.practice_frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.practice_frame)
        self.label_28.setText(_fromUtf8(""))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 5, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.practice_frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.practice_frame)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 6, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.practice_frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 7, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.practice_frame)
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 7, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.practice_frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 8, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.practice_frame)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 8, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.practice_frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout.addWidget(self.lineEdit_10, 9, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.practice_frame)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 9, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.practice_frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.practice_frame)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout.addWidget(self.lineEdit_11, 10, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.practice_frame)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 10, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.practice_frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.users_tableWidget = QtGui.QTableWidget(self.tab_2)
        self.users_tableWidget.setAlternatingRowColors(True)
        self.users_tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.users_tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.users_tableWidget.setObjectName(_fromUtf8("users_tableWidget"))
        self.users_tableWidget.setColumnCount(6)
        self.users_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.users_tableWidget)
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.modifyUser_pushButton = QtGui.QPushButton(self.frame_2)
        self.modifyUser_pushButton.setObjectName(_fromUtf8("modifyUser_pushButton"))
        self.verticalLayout_11.addWidget(self.modifyUser_pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.user_groupBox = QtGui.QGroupBox(self.frame_2)
        self.user_groupBox.setObjectName(_fromUtf8("user_groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.user_groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_14 = QtGui.QLabel(self.user_groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.userName_lineEdit = QtGui.QLineEdit(self.user_groupBox)
        self.userName_lineEdit.setObjectName(_fromUtf8("userName_lineEdit"))
        self.gridLayout_8.addWidget(self.userName_lineEdit, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.user_groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 1, 0, 1, 1)
        self.userInits_lineEdit = QtGui.QLineEdit(self.user_groupBox)
        self.userInits_lineEdit.setObjectName(_fromUtf8("userInits_lineEdit"))
        self.gridLayout_8.addWidget(self.userInits_lineEdit, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.user_groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_8.addWidget(self.label_15, 2, 0, 1, 1)
        self.userGroup_comboBox = QtGui.QComboBox(self.user_groupBox)
        self.userGroup_comboBox.setObjectName(_fromUtf8("userGroup_comboBox"))
        self.userGroup_comboBox.addItem(_fromUtf8(""))
        self.userGroup_comboBox.addItem(_fromUtf8(""))
        self.userGroup_comboBox.addItem(_fromUtf8(""))
        self.userGroup_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.userGroup_comboBox, 2, 1, 1, 1)
        self.userActive_checkBox = QtGui.QCheckBox(self.user_groupBox)
        self.userActive_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.userActive_checkBox.setChecked(True)
        self.userActive_checkBox.setObjectName(_fromUtf8("userActive_checkBox"))
        self.gridLayout_8.addWidget(self.userActive_checkBox, 2, 2, 1, 1)
        self.user_date_label = QtGui.QLabel(self.user_groupBox)
        self.user_date_label.setObjectName(_fromUtf8("user_date_label"))
        self.gridLayout_8.addWidget(self.user_date_label, 3, 0, 1, 1)
        self.user_dateEdit = QtGui.QDateEdit(self.user_groupBox)
        self.user_dateEdit.setCalendarPopup(True)
        self.user_dateEdit.setObjectName(_fromUtf8("user_dateEdit"))
        self.gridLayout_8.addWidget(self.user_dateEdit, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.user_groupBox)
        self.newUser_pushButton = QtGui.QPushButton(self.frame_2)
        self.newUser_pushButton.setEnabled(True)
        self.newUser_pushButton.setObjectName(_fromUtf8("newUser_pushButton"))
        self.horizontalLayout.addWidget(self.newUser_pushButton)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_33 = QtGui.QLabel(self.tab_3)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_5.addWidget(self.label_33)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        self.frame_3 = QtGui.QFrame(self.tab_3)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_29 = QtGui.QLabel(self.frame_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_7.addWidget(self.label_29)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_30 = QtGui.QLabel(self.frame_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 0, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_4.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.frame_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 1, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_4.addWidget(self.lineEdit_15, 1, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.frame_3)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_4.addWidget(self.label_45, 2, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_21.setText(_fromUtf8(""))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_4.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.checkBox_2 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_7.addWidget(self.checkBox_2)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_38 = QtGui.QLabel(self.tab_4)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_4.addWidget(self.label_38)
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.tableWidget_3)
        self.frame_4 = QtGui.QFrame(self.tab_4)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_32 = QtGui.QLabel(self.frame_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_8.addWidget(self.label_32)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_34 = QtGui.QLabel(self.frame_4)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_5.addWidget(self.label_34, 0, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_5.addWidget(self.lineEdit_16, 0, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_4)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_5.addWidget(self.label_35, 1, 0, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_5.addWidget(self.lineEdit_17, 1, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.frame_4)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_5.addWidget(self.label_46, 2, 0, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_22.setText(_fromUtf8(""))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_5.addWidget(self.lineEdit_22, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.checkBox_3 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.verticalLayout_8.addWidget(self.checkBox_3)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_6 = QtGui.QFrame(self.tab_5)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.checkBox_7 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_7.addWidget(self.checkBox_7, 0, 0, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.gridLayout_7.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.timeEdit_2 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_2.setObjectName(_fromUtf8("timeEdit_2"))
        self.gridLayout_7.addWidget(self.timeEdit_2, 0, 2, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout_7.addWidget(self.checkBox_8, 1, 0, 1, 1)
        self.timeEdit_3 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_3.setObjectName(_fromUtf8("timeEdit_3"))
        self.gridLayout_7.addWidget(self.timeEdit_3, 1, 1, 1, 1)
        self.timeEdit_4 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_4.setObjectName(_fromUtf8("timeEdit_4"))
        self.gridLayout_7.addWidget(self.timeEdit_4, 1, 2, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout_7.addWidget(self.checkBox_9, 2, 0, 1, 1)
        self.timeEdit_5 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_5.setObjectName(_fromUtf8("timeEdit_5"))
        self.gridLayout_7.addWidget(self.timeEdit_5, 2, 1, 1, 1)
        self.timeEdit_6 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_6.setObjectName(_fromUtf8("timeEdit_6"))
        self.gridLayout_7.addWidget(self.timeEdit_6, 2, 2, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout_7.addWidget(self.checkBox_10, 3, 0, 1, 1)
        self.timeEdit_7 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_7.setObjectName(_fromUtf8("timeEdit_7"))
        self.gridLayout_7.addWidget(self.timeEdit_7, 3, 1, 1, 1)
        self.timeEdit_8 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_8.setObjectName(_fromUtf8("timeEdit_8"))
        self.gridLayout_7.addWidget(self.timeEdit_8, 3, 2, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout_7.addWidget(self.checkBox_11, 4, 0, 1, 1)
        self.timeEdit_10 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_10.setObjectName(_fromUtf8("timeEdit_10"))
        self.gridLayout_7.addWidget(self.timeEdit_10, 4, 1, 1, 1)
        self.timeEdit_11 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_11.setObjectName(_fromUtf8("timeEdit_11"))
        self.gridLayout_7.addWidget(self.timeEdit_11, 4, 2, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout_7.addWidget(self.checkBox_12, 5, 0, 1, 1)
        self.timeEdit_12 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_12.setObjectName(_fromUtf8("timeEdit_12"))
        self.gridLayout_7.addWidget(self.timeEdit_12, 5, 1, 1, 1)
        self.timeEdit_9 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_9.setObjectName(_fromUtf8("timeEdit_9"))
        self.gridLayout_7.addWidget(self.timeEdit_9, 5, 2, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout_7.addWidget(self.checkBox_13, 6, 0, 1, 1)
        self.timeEdit_13 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_13.setObjectName(_fromUtf8("timeEdit_13"))
        self.gridLayout_7.addWidget(self.timeEdit_13, 6, 1, 1, 1)
        self.timeEdit_14 = QtGui.QTimeEdit(self.frame_6)
        self.timeEdit_14.setObjectName(_fromUtf8("timeEdit_14"))
        self.gridLayout_7.addWidget(self.timeEdit_14, 6, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Template = QtGui.QAction(MainWindow)
        self.actionLoad_Template.setObjectName(_fromUtf8("actionLoad_Template"))
        self.action_Save_Template = QtGui.QAction(MainWindow)
        self.action_Save_Template.setObjectName(_fromUtf8("action_Save_Template"))
        self.menuFile.addAction(self.actionLoad_Template)
        self.menuFile.addAction(self.action_Save_Template)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_("OpenMolar - database wizard"))
        self.label_17.setText(_("What do you want to do?"))
        self.modifydb_radioButton.setText(_("Modify an existing openmolar database"))
        self.blankdb_radioButton.setText(_("Create a New database from scratch"))
        self.newdb_template_radioButton.setText(_("Create a New database (from a known template)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _("Start"))
        self.label.setText(_("Practice Name"))
        self.label_18.setText(_("Used in receipts, appointment cards etc."))
        self.label_2.setText(_("Address Line 1"))
        self.label_3.setText(_("Address Line 2"))
        self.label_4.setText(_("Address Line 3"))
        self.label_5.setText(_("Town"))
        self.label_6.setText(_("County"))
        self.label_7.setText(_("Postcode / Zip"))
        self.label_8.setText(_("Telephone"))
        self.label_9.setText(_("Fax"))
        self.label_10.setText(_("Website"))
        self.label_11.setText(_("Email"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Practice Details"))
        self.label_12.setText(_("The Following users can login to the application"))
        item = self.users_tableWidget.horizontalHeaderItem(0)
        item.setText(_("Id"))
        item = self.users_tableWidget.horizontalHeaderItem(1)
        item.setText(_("Initials"))
        item = self.users_tableWidget.horizontalHeaderItem(2)
        item.setText(_("Name"))
        item = self.users_tableWidget.horizontalHeaderItem(3)
        item.setText(_("User Group"))
        item = self.users_tableWidget.horizontalHeaderItem(4)
        item.setText(_("Active?"))
        item = self.users_tableWidget.horizontalHeaderItem(5)
        item.setText(_("DeActivation Date"))
        self.modifyUser_pushButton.setText(_("Modify Selected User"))
        self.user_groupBox.setTitle(_("New User Details"))
        self.label_14.setText(_("Name"))
        self.label_13.setText(_("Initials"))
        self.label_15.setText(_("User Group"))
        self.userGroup_comboBox.setItemText(0, _("Standard User"))
        self.userGroup_comboBox.setItemText(1, _("Dentist"))
        self.userGroup_comboBox.setItemText(2, _("Hygienist"))
        self.userGroup_comboBox.setItemText(3, _("Receptionist"))
        self.userActive_checkBox.setText(_("Active User"))
        self.user_date_label.setText(_("DeActivation Date"))
        self.newUser_pushButton.setText(_("Add a New User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Users"))
        self.label_33.setText(_("The Following dentists have notes in this database\n"
"(note - dentists should not be removed from the database, as this could create lookup issues for cashbooks and notes) "))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_("Initials"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_("Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_("User Group"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_("Active?"))
        self.label_29.setText(_("Add a Dentist"))
        self.label_30.setText(_("Initials"))
        self.label_31.setText(_("Name"))
        self.label_45.setText(_("Registration"))
        self.checkBox_2.setText(_("Active Appointment Book"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _("Dentists"))
        self.label_38.setText(_("The Following hygienists have notes in this database\n"
"(note - hygienists should not be removed from the database, as this could create lookup issues for cashbooks and notes) "))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_("Initials"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_("Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_("User Group"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_("Active?"))
        self.label_32.setText(_("Add a Dentist"))
        self.label_34.setText(_("Initials"))
        self.label_35.setText(_("Name"))
        self.label_46.setText(_("Registration"))
        self.checkBox_3.setText(_("Active Appointment Book"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _("Hygienists"))
        self.checkBox_7.setText(_("Monday"))
        self.checkBox_8.setText(_("Tuesday"))
        self.checkBox_9.setText(_("Wednesday"))
        self.checkBox_10.setText(_("Thursday"))
        self.checkBox_11.setText(_("Friday"))
        self.checkBox_12.setText(_("Saturday"))
        self.checkBox_13.setText(_("Sunday"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _("Practice Hours"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _("View XML"))
        self.menuFile.setTitle(_("File"))
        self.actionLoad_Template.setText(_("L&oad Template"))
        self.action_Save_Template.setText(_("&Save Template"))


if __name__ == "__main__":
    import gettext
    gettext.install("openmolar")
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

