# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newSetup.ui'
#
# Created: Sat Oct  3 00:10:08 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from gettext import gettext as _

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 269)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setMinimumSize(QtCore.QSize(0, 100))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.page)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.stackedWidget.addWidget(self.page)
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_2 = QtGui.QGridLayout(self.page_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtGui.QSpacerItem(358, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.page_1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.main_password_lineEdit = QtGui.QLineEdit(self.page_1)
        self.main_password_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.main_password_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.main_password_lineEdit.setObjectName("main_password_lineEdit")
        self.gridLayout_2.addWidget(self.main_password_lineEdit, 1, 1, 1, 1)
        self.mainpassword_checkBox = QtGui.QCheckBox(self.page_1)
        self.mainpassword_checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mainpassword_checkBox.setObjectName("mainpassword_checkBox")
        self.gridLayout_2.addWidget(self.mainpassword_checkBox, 1, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.page_1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 0, 1, 3)
        self.mainPassword_label = QtGui.QLabel(self.page_1)
        self.mainPassword_label.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.mainPassword_label.setFont(font)
        self.mainPassword_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mainPassword_label.setWordWrap(True)
        self.mainPassword_label.setObjectName("mainPassword_label")
        self.gridLayout_2.addWidget(self.mainPassword_label, 0, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_1)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtGui.QLabel(self.page_6)
        self.label_13.setEnabled(True)
        self.label_13.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(103, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 2, 1)
        self.label_12 = QtGui.QLabel(self.page_6)
        self.label_12.setEnabled(True)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 1, 1, 1)
        self.host_lineEdit = QtGui.QLineEdit(self.page_6)
        self.host_lineEdit.setEnabled(True)
        self.host_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.host_lineEdit.setObjectName("host_lineEdit")
        self.gridLayout_3.addWidget(self.host_lineEdit, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(103, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 3, 2, 1)
        self.label_14 = QtGui.QLabel(self.page_6)
        self.label_14.setEnabled(True)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 1, 1, 1)
        self.port_lineEdit = QtGui.QLineEdit(self.page_6)
        self.port_lineEdit.setEnabled(True)
        self.port_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.gridLayout_3.addWidget(self.port_lineEdit, 2, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(103, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 3, 0, 1, 4)
        self.pushButton_8 = QtGui.QPushButton(self.page_6)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 4, 0, 1, 4)
        self.stackedWidget.addWidget(self.page_6)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_4 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.createDB_pushButton = QtGui.QPushButton(self.page_5)
        self.createDB_pushButton.setObjectName("createDB_pushButton")
        self.gridLayout_4.addWidget(self.createDB_pushButton, 2, 0, 1, 1)
        self.haveDB_pushButton = QtGui.QPushButton(self.page_5)
        self.haveDB_pushButton.setObjectName("haveDB_pushButton")
        self.gridLayout_4.addWidget(self.haveDB_pushButton, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_5)
        self.label_11.setMinimumSize(QtCore.QSize(0, 100))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 52, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout = QtGui.QGridLayout(self.page_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.page_4)
        self.label_9.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 3)
        self.label_4 = QtGui.QLabel(self.page_4)
        self.label_4.setEnabled(True)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.database_lineEdit = QtGui.QLineEdit(self.page_4)
        self.database_lineEdit.setEnabled(True)
        self.database_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.database_lineEdit.setObjectName("database_lineEdit")
        self.gridLayout.addWidget(self.database_lineEdit, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_4)
        self.label_2.setEnabled(True)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.user_lineEdit = QtGui.QLineEdit(self.page_4)
        self.user_lineEdit.setEnabled(True)
        self.user_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.gridLayout.addWidget(self.user_lineEdit, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_4)
        self.label_3.setEnabled(True)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.password_lineEdit = QtGui.QLineEdit(self.page_4)
        self.password_lineEdit.setEnabled(True)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.password_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 3, 1, 1, 1)
        self.dbpassword_checkBox = QtGui.QCheckBox(self.page_4)
        self.dbpassword_checkBox.setEnabled(True)
        self.dbpassword_checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dbpassword_checkBox.setObjectName("dbpassword_checkBox")
        self.gridLayout.addWidget(self.dbpassword_checkBox, 3, 2, 1, 1)
        self.testDB_pushButton = QtGui.QPushButton(self.page_4)
        self.testDB_pushButton.setObjectName("testDB_pushButton")
        self.gridLayout.addWidget(self.testDB_pushButton, 4, 0, 1, 3)
        self.pushButton_9 = QtGui.QPushButton(self.page_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 6, 0, 1, 3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtGui.QLabel(self.page_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.saveQuit_pushButton = QtGui.QPushButton(self.page_3)
        self.saveQuit_pushButton.setObjectName("saveQuit_pushButton")
        self.gridLayout_6.addWidget(self.saveQuit_pushButton, 2, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_7 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.mainPassword_label_2 = QtGui.QLabel(self.page_2)
        self.mainPassword_label_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.mainPassword_label_2.setFont(font)
        self.mainPassword_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mainPassword_label_2.setWordWrap(True)
        self.mainPassword_label_2.setObjectName("mainPassword_label_2")
        self.gridLayout_7.addWidget(self.mainPassword_label_2, 0, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 1, 0, 1, 1)
        self.rootPassword_lineEdit = QtGui.QLineEdit(self.page_2)
        self.rootPassword_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.rootPassword_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.rootPassword_lineEdit.setObjectName("rootPassword_lineEdit")
        self.gridLayout_7.addWidget(self.rootPassword_lineEdit, 1, 1, 1, 1)
        self.rootPassword_checkBox = QtGui.QCheckBox(self.page_2)
        self.rootPassword_checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rootPassword_checkBox.setObjectName("rootPassword_checkBox")
        self.gridLayout_7.addWidget(self.rootPassword_checkBox, 1, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(348, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem8, 2, 0, 1, 3)
        self.createDB_pushButton_2 = QtGui.QPushButton(self.page_2)
        self.createDB_pushButton_2.setObjectName("createDB_pushButton_2")
        self.gridLayout_7.addWidget(self.createDB_pushButton_2, 3, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton, self.main_password_lineEdit)
        Dialog.setTabOrder(self.main_password_lineEdit, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.host_lineEdit)
        Dialog.setTabOrder(self.host_lineEdit, self.port_lineEdit)
        Dialog.setTabOrder(self.port_lineEdit, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.haveDB_pushButton)
        Dialog.setTabOrder(self.haveDB_pushButton, self.createDB_pushButton)
        Dialog.setTabOrder(self.createDB_pushButton, self.pushButton_9)
        Dialog.setTabOrder(self.pushButton_9, self.database_lineEdit)
        Dialog.setTabOrder(self.database_lineEdit, self.user_lineEdit)
        Dialog.setTabOrder(self.user_lineEdit, self.password_lineEdit)
        Dialog.setTabOrder(self.password_lineEdit, self.testDB_pushButton)
        Dialog.setTabOrder(self.testDB_pushButton, self.saveQuit_pushButton)
        Dialog.setTabOrder(self.saveQuit_pushButton, self.rootPassword_lineEdit)
        Dialog.setTabOrder(self.rootPassword_lineEdit, self.createDB_pushButton_2)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_( "First Run"))
        self.label_7.setText(_( "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome to the openMolar settings wizard.</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This will set your system password, configure your mysql server, and install a small demo database if required.</p></body></html>"))
        self.pushButton.setText(_( "OK, continue"))
        self.label_5.setText(_( "Password"))
        self.mainpassword_checkBox.setText(_( "show password"))
        self.pushButton_2.setText(_( "OK, continue"))
        self.mainPassword_label.setText(_( "Please enter a password to prevent unauthorised running of this application."))
        self.label_13.setText(_( "Where is your mysql server located?"))
        self.label_12.setText(_( "Host"))
        self.host_lineEdit.setText(_( "localhost"))
        self.label_14.setText(_( "Port"))
        self.port_lineEdit.setText(_( "3306"))
        self.pushButton_8.setText(_( "OK, continue"))
        self.createDB_pushButton.setText(_( "Yes please"))
        self.haveDB_pushButton.setText(_( "No, I have a database already, continue."))
        self.label_11.setText(_( "Would you like to create a demo openmolar database now?"))
        self.label_9.setText(_( "Please enter a mysql user who has privileges for the openmolar database."))
        self.label_4.setText(_( "Database Name"))
        self.database_lineEdit.setText(_( "openmolar_demo"))
        self.label_2.setText(_( "User"))
        self.user_lineEdit.setText(_( "OMuser"))
        self.label_3.setText(_( "(mysql)Password"))
        self.password_lineEdit.setText(_( "password"))
        self.dbpassword_checkBox.setText(_( "display password"))
        self.testDB_pushButton.setText(_( "Test this connection to this database"))
        self.pushButton_9.setText(_( "OK, continue"))
        self.label.setText(_( "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">OK.... you are all set to go.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You will be presented with a login screen.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">I trust you remember your password?</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you created a demo database... </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">enter <span style=\" font-weight:600; text-decoration: underline;\">user</span> into the user1 field of the login screen.</p></body></html>"))
        self.saveQuit_pushButton.setText(_( "Save settings and launch openmolar"))
        self.mainPassword_label_2.setText(_( "To create a database, please enter the password of your ROOT mysql user."))
        self.label_6.setText(_( "Password"))
        self.rootPassword_checkBox.setText(_( "show password"))
        self.createDB_pushButton_2.setText(_( "Create openmolar_demo database, and continue"))

