#! /usr/bin/python

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar1/src/openmolar/qt-designer/newBPE.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(261, 161)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(90)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 90))
        self.frame.setMaximumSize(QtCore.QSize(300, 90))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.bpe_comboBox = QtGui.QComboBox(self.frame)
        self.bpe_comboBox.setObjectName("bpe_comboBox")
        self.bpe_comboBox.addItem("")
        self.bpe_comboBox.addItem("")
        self.bpe_comboBox.addItem("")
        self.bpe_comboBox.addItem("")
        self.bpe_comboBox.addItem("")
        self.bpe_comboBox.addItem("")
        self.gridLayout.addWidget(self.bpe_comboBox, 0, 0, 1, 1)
        self.bpe2_comboBox = QtGui.QComboBox(self.frame)
        self.bpe2_comboBox.setObjectName("bpe2_comboBox")
        self.bpe2_comboBox.addItem("")
        self.bpe2_comboBox.addItem("")
        self.bpe2_comboBox.addItem("")
        self.bpe2_comboBox.addItem("")
        self.bpe2_comboBox.addItem("")
        self.bpe2_comboBox.addItem("")
        self.gridLayout.addWidget(self.bpe2_comboBox, 0, 1, 1, 1)
        self.bpe3_comboBox = QtGui.QComboBox(self.frame)
        self.bpe3_comboBox.setObjectName("bpe3_comboBox")
        self.bpe3_comboBox.addItem("")
        self.bpe3_comboBox.addItem("")
        self.bpe3_comboBox.addItem("")
        self.bpe3_comboBox.addItem("")
        self.bpe3_comboBox.addItem("")
        self.bpe3_comboBox.addItem("")
        self.gridLayout.addWidget(self.bpe3_comboBox, 0, 2, 1, 1)
        self.bpe4_comboBox = QtGui.QComboBox(self.frame)
        self.bpe4_comboBox.setObjectName("bpe4_comboBox")
        self.bpe4_comboBox.addItem("")
        self.bpe4_comboBox.addItem("")
        self.bpe4_comboBox.addItem("")
        self.bpe4_comboBox.addItem("")
        self.bpe4_comboBox.addItem("")
        self.bpe4_comboBox.addItem("")
        self.gridLayout.addWidget(self.bpe4_comboBox, 1, 0, 1, 1)
        self.bpe5_comboBox = QtGui.QComboBox(self.frame)
        self.bpe5_comboBox.setObjectName("bpe5_comboBox")
        self.bpe5_comboBox.addItem("")
        self.bpe5_comboBox.addItem("")
        self.bpe5_comboBox.addItem("")
        self.bpe5_comboBox.addItem("")
        self.bpe5_comboBox.addItem("")
        self.bpe5_comboBox.addItem("")
        self.gridLayout.addWidget(self.bpe5_comboBox, 1, 1, 1, 1)
        self.bpe6_comboBox = QtGui.QComboBox(self.frame)
        self.bpe6_comboBox.setObjectName("bpe6_comboBox")
        self.bpe6_comboBox.addItem("")
        self.bpe6_comboBox.addItem("")
        self.bpe6_comboBox.addItem("")
        self.bpe6_comboBox.addItem("")
        self.bpe6_comboBox.addItem("")
        self.bpe6_comboBox.addItem("")
        self.gridLayout.addWidget(self.bpe6_comboBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.buttonBox, self.bpe_comboBox)
        Dialog.setTabOrder(self.bpe_comboBox, self.bpe2_comboBox)
        Dialog.setTabOrder(self.bpe2_comboBox, self.bpe3_comboBox)
        Dialog.setTabOrder(self.bpe3_comboBox, self.bpe6_comboBox)
        Dialog.setTabOrder(self.bpe6_comboBox, self.bpe5_comboBox)
        Dialog.setTabOrder(self.bpe5_comboBox, self.bpe4_comboBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_("New CPITN score"))
        self.bpe_comboBox.setItemText(0, _("0"))
        self.bpe_comboBox.setItemText(1, _("1"))
        self.bpe_comboBox.setItemText(2, _("2"))
        self.bpe_comboBox.setItemText(3, _("3"))
        self.bpe_comboBox.setItemText(4, _("4"))
        self.bpe_comboBox.setItemText(5, _("*"))
        self.bpe2_comboBox.setItemText(0, _("0"))
        self.bpe2_comboBox.setItemText(1, _("1"))
        self.bpe2_comboBox.setItemText(2, _("2"))
        self.bpe2_comboBox.setItemText(3, _("3"))
        self.bpe2_comboBox.setItemText(4, _("4"))
        self.bpe2_comboBox.setItemText(5, _("*"))
        self.bpe3_comboBox.setItemText(0, _("0"))
        self.bpe3_comboBox.setItemText(1, _("1"))
        self.bpe3_comboBox.setItemText(2, _("2"))
        self.bpe3_comboBox.setItemText(3, _("3"))
        self.bpe3_comboBox.setItemText(4, _("4"))
        self.bpe3_comboBox.setItemText(5, _("*"))
        self.bpe4_comboBox.setItemText(0, _("0"))
        self.bpe4_comboBox.setItemText(1, _("1"))
        self.bpe4_comboBox.setItemText(2, _("2"))
        self.bpe4_comboBox.setItemText(3, _("3"))
        self.bpe4_comboBox.setItemText(4, _("4"))
        self.bpe4_comboBox.setItemText(5, _("*"))
        self.bpe5_comboBox.setItemText(0, _("0"))
        self.bpe5_comboBox.setItemText(1, _("1"))
        self.bpe5_comboBox.setItemText(2, _("2"))
        self.bpe5_comboBox.setItemText(3, _("3"))
        self.bpe5_comboBox.setItemText(4, _("4"))
        self.bpe5_comboBox.setItemText(5, _("*"))
        self.bpe6_comboBox.setItemText(0, _("0"))
        self.bpe6_comboBox.setItemText(1, _("1"))
        self.bpe6_comboBox.setItemText(2, _("2"))
        self.bpe6_comboBox.setItemText(3, _("3"))
        self.bpe6_comboBox.setItemText(4, _("4"))
        self.bpe6_comboBox.setItemText(5, _("*"))


if __name__ == "__main__":
    import gettext
    gettext.install("openmolar")
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

