# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ortho_ref_wizard.ui'
#
# Created: Sat Jan  2 16:05:28 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(941, 598)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.ref1_radioButton = QtGui.QRadioButton(self.frame)
        self.ref1_radioButton.setChecked(True)
        self.ref1_radioButton.setObjectName("ref1_radioButton")
        self.gridLayout.addWidget(self.ref1_radioButton, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 2)
        self.ref2_radioButton = QtGui.QRadioButton(self.frame)
        self.ref2_radioButton.setObjectName("ref2_radioButton")
        self.gridLayout.addWidget(self.ref2_radioButton, 1, 0, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.frame)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.tx_checkBox = QtGui.QCheckBox(Dialog)
        self.tx_checkBox.setObjectName("tx_checkBox")
        self.gridLayout_5.addWidget(self.tx_checkBox, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setMargin(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.crowding1_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.crowding1_radioButton.setObjectName("crowding1_radioButton")
        self.horizontalLayout_2.addWidget(self.crowding1_radioButton)
        self.crowding2_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.crowding2_radioButton.setObjectName("crowding2_radioButton")
        self.horizontalLayout_2.addWidget(self.crowding2_radioButton)
        self.crowding3_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.crowding3_radioButton.setObjectName("crowding3_radioButton")
        self.horizontalLayout_2.addWidget(self.crowding3_radioButton)
        self.crowding4_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.crowding4_radioButton.setObjectName("crowding4_radioButton")
        self.horizontalLayout_2.addWidget(self.crowding4_radioButton)
        self.crowding5_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.crowding5_radioButton.setObjectName("crowding5_radioButton")
        self.horizontalLayout_2.addWidget(self.crowding5_radioButton)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.oj_spinBox = QtGui.QSpinBox(self.groupBox_3)
        self.oj_spinBox.setMinimum(-20)
        self.oj_spinBox.setMaximum(20)
        self.oj_spinBox.setObjectName("oj_spinBox")
        self.gridLayout_2.addWidget(self.oj_spinBox, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(248, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 3)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.ob1_radioButton = QtGui.QRadioButton(self.groupBox_3)
        self.ob1_radioButton.setObjectName("ob1_radioButton")
        self.gridLayout_2.addWidget(self.ob1_radioButton, 1, 2, 1, 1)
        self.ob2_radioButton = QtGui.QRadioButton(self.groupBox_3)
        self.ob2_radioButton.setObjectName("ob2_radioButton")
        self.gridLayout_2.addWidget(self.ob2_radioButton, 1, 3, 1, 1)
        self.ob3_radioButton = QtGui.QRadioButton(self.groupBox_3)
        self.ob3_radioButton.setObjectName("ob3_radioButton")
        self.gridLayout_2.addWidget(self.ob3_radioButton, 1, 4, 1, 1)
        self.ob_spinBox = QtGui.QSpinBox(self.groupBox_3)
        self.ob_spinBox.setMaximum(100)
        self.ob_spinBox.setObjectName("ob_spinBox")
        self.gridLayout_2.addWidget(self.ob_spinBox, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mh__textEdit = QtGui.QTextEdit(self.groupBox_4)
        self.mh__textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mh__textEdit.setObjectName("mh__textEdit")
        self.gridLayout_3.addWidget(self.mh__textEdit, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dh_textEdit = QtGui.QTextEdit(self.groupBox_5)
        self.dh_textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dh_textEdit.setObjectName("dh_textEdit")
        self.gridLayout_4.addWidget(self.dh_textEdit, 0, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.chart_groupBox = QtGui.QGroupBox(self.groupBox)
        self.chart_groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.chart_groupBox.setObjectName("chart_groupBox")
        self.verticalLayout_2.addWidget(self.chart_groupBox)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.removable_checkBox = QtGui.QCheckBox(self.groupBox_6)
        self.removable_checkBox.setObjectName("removable_checkBox")
        self.horizontalLayout.addWidget(self.removable_checkBox)
        self.fixed_checkBox = QtGui.QCheckBox(self.groupBox_6)
        self.fixed_checkBox.setObjectName("fixed_checkBox")
        self.horizontalLayout.addWidget(self.fixed_checkBox)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.gridLayout_5.addWidget(self.groupBox, 2, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.notes_textEdit = QtGui.QTextEdit(Dialog)
        self.notes_textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.notes_textEdit.setObjectName("notes_textEdit")
        self.gridLayout_5.addWidget(self.notes_textEdit, 0, 1, 3, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_( u"Dialog"))
        self.ref1_radioButton.setText(_( u"1st referral"))
        self.ref2_radioButton.setText(_( u"re - referral"))
        self.label_2.setText(_( u"Previous Referral Date"))
        self.tx_checkBox.setText(_( u"I am Willing to carry out simple treatment"))
        self.groupBox.setTitle(_( u"Reason for Referral"))
        self.groupBox_2.setTitle(_( u"Crowding"))
        self.crowding1_radioButton.setText(_( u"Spaced"))
        self.crowding2_radioButton.setText(_( u"None"))
        self.crowding3_radioButton.setText(_( u"Mild"))
        self.crowding4_radioButton.setText(_( u"Moderate"))
        self.crowding5_radioButton.setText(_( u"Severe"))
        self.groupBox_3.setTitle(_( u"Incisal Relationship"))
        self.label.setText(_( u"Overjet:"))
        self.oj_spinBox.setSuffix(_( u"mm"))
        self.label_3.setText(_( u"Overbite"))
        self.ob1_radioButton.setText(_( u"Complete"))
        self.ob2_radioButton.setText(_( u"InComplete"))
        self.ob3_radioButton.setText(_( u"Traumatic"))
        self.ob_spinBox.setSuffix(_( u"%"))
        self.groupBox_4.setTitle(_( u"Relevant Medical History"))
        self.mh__textEdit.setHtml(_( u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Serif\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.groupBox_5.setTitle(_( u"Dental History"))
        self.chart_groupBox.setTitle(_( u"Teeth With Poor Prognosis"))
        self.groupBox_6.setTitle(_( u"Patient Motivation"))
        self.removable_checkBox.setText(_( u"Removable Applicance"))
        self.fixed_checkBox.setText(_( u"Fixed Appliance"))

