# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar/src/openmolar/qt-designer/record_tools.ui'
#
# Created: Tue Apr 23 10:40:52 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(628, 521)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.money_scrollArea = QtGui.QScrollArea(self.tab)
        self.money_scrollArea.setWidgetResizable(True)
        self.money_scrollArea.setObjectName(_fromUtf8("money_scrollArea"))
        self.money_scrollAreaWidgetContents = QtGui.QWidget()
        self.money_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 443, 424))
        self.money_scrollAreaWidgetContents.setObjectName(_fromUtf8("money_scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.money_scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.money0_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money0_spinBox.setMaximum(1000000)
        self.money0_spinBox.setObjectName(_fromUtf8("money0_spinBox"))
        self.gridLayout.addWidget(self.money0_spinBox, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.money2_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money2_spinBox.setMaximum(1000000)
        self.money2_spinBox.setObjectName(_fromUtf8("money2_spinBox"))
        self.gridLayout.addWidget(self.money2_spinBox, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.money4_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money4_spinBox.setMaximum(1000000)
        self.money4_spinBox.setObjectName(_fromUtf8("money4_spinBox"))
        self.gridLayout.addWidget(self.money4_spinBox, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.money5_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money5_spinBox.setMaximum(1000000)
        self.money5_spinBox.setObjectName(_fromUtf8("money5_spinBox"))
        self.gridLayout.addWidget(self.money5_spinBox, 8, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.money6_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money6_spinBox.setMaximum(1000000)
        self.money6_spinBox.setObjectName(_fromUtf8("money6_spinBox"))
        self.gridLayout.addWidget(self.money6_spinBox, 9, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.money7_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money7_spinBox.setMaximum(1000000)
        self.money7_spinBox.setObjectName(_fromUtf8("money7_spinBox"))
        self.gridLayout.addWidget(self.money7_spinBox, 10, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 11, 0, 1, 1)
        self.money8_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money8_spinBox.setMaximum(1000000)
        self.money8_spinBox.setObjectName(_fromUtf8("money8_spinBox"))
        self.gridLayout.addWidget(self.money8_spinBox, 11, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 12, 0, 1, 1)
        self.money9_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money9_spinBox.setMaximum(1000000)
        self.money9_spinBox.setObjectName(_fromUtf8("money9_spinBox"))
        self.gridLayout.addWidget(self.money9_spinBox, 12, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 13, 0, 1, 1)
        self.money10_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money10_spinBox.setMaximum(1000000)
        self.money10_spinBox.setObjectName(_fromUtf8("money10_spinBox"))
        self.gridLayout.addWidget(self.money10_spinBox, 13, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 14, 0, 1, 1)
        self.money11_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money11_spinBox.setMaximum(1000000)
        self.money11_spinBox.setObjectName(_fromUtf8("money11_spinBox"))
        self.gridLayout.addWidget(self.money11_spinBox, 14, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.money1_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money1_spinBox.setMaximum(1000000)
        self.money1_spinBox.setObjectName(_fromUtf8("money1_spinBox"))
        self.gridLayout.addWidget(self.money1_spinBox, 3, 1, 1, 1)
        self.money3_spinBox = QtGui.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money3_spinBox.setMaximum(1000000)
        self.money3_spinBox.setObjectName(_fromUtf8("money3_spinBox"))
        self.gridLayout.addWidget(self.money3_spinBox, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 0, 1, 2)
        self.label_14 = QtGui.QLabel(self.money_scrollAreaWidgetContents)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 2)
        self.money_scrollArea.setWidget(self.money_scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.money_scrollArea, 0, 0, 4, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 1, 1, 1)
        self.total_label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_label.setFont(font)
        self.total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_label.setObjectName(_fromUtf8("total_label"))
        self.gridLayout_2.addWidget(self.total_label, 1, 1, 1, 1)
        self.money_pushButton = QtGui.QPushButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/button_ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.money_pushButton.setIcon(icon)
        self.money_pushButton.setObjectName(_fromUtf8("money_pushButton"))
        self.gridLayout_2.addWidget(self.money_pushButton, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 337, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dates_pushButton = QtGui.QPushButton(self.tab_2)
        self.dates_pushButton.setIcon(icon)
        self.dates_pushButton.setObjectName(_fromUtf8("dates_pushButton"))
        self.gridLayout_4.addWidget(self.dates_pushButton, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(82, 388, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 1, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 345, 263))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pd5_dateEdit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.pd5_dateEdit.setCalendarPopup(True)
        self.pd5_dateEdit.setObjectName(_fromUtf8("pd5_dateEdit"))
        self.horizontalLayout.addWidget(self.pd5_dateEdit)
        self.pd5_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pd5_pushButton.setObjectName(_fromUtf8("pd5_pushButton"))
        self.horizontalLayout.addWidget(self.pd5_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pd6_dateEdit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.pd6_dateEdit.setCalendarPopup(True)
        self.pd6_dateEdit.setObjectName(_fromUtf8("pd6_dateEdit"))
        self.horizontalLayout_2.addWidget(self.pd6_dateEdit)
        self.pd6_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pd6_pushButton.setObjectName(_fromUtf8("pd6_pushButton"))
        self.horizontalLayout_2.addWidget(self.pd6_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pd7_dateEdit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.pd7_dateEdit.setCalendarPopup(True)
        self.pd7_dateEdit.setObjectName(_fromUtf8("pd7_dateEdit"))
        self.horizontalLayout_3.addWidget(self.pd7_dateEdit)
        self.pd7_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pd7_pushButton.setObjectName(_fromUtf8("pd7_pushButton"))
        self.horizontalLayout_3.addWidget(self.pd7_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pd8_dateEdit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.pd8_dateEdit.setCalendarPopup(True)
        self.pd8_dateEdit.setObjectName(_fromUtf8("pd8_dateEdit"))
        self.horizontalLayout_4.addWidget(self.pd8_dateEdit)
        self.pd8_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pd8_pushButton.setObjectName(_fromUtf8("pd8_pushButton"))
        self.horizontalLayout_4.addWidget(self.pd8_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pd9_dateEdit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.pd9_dateEdit.setCalendarPopup(True)
        self.pd9_dateEdit.setObjectName(_fromUtf8("pd9_dateEdit"))
        self.horizontalLayout_5.addWidget(self.pd9_dateEdit)
        self.pd9_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pd9_pushButton.setObjectName(_fromUtf8("pd9_pushButton"))
        self.horizontalLayout_5.addWidget(self.pd9_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pd10_dateEdit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.pd10_dateEdit.setCalendarPopup(True)
        self.pd10_dateEdit.setObjectName(_fromUtf8("pd10_dateEdit"))
        self.horizontalLayout_6.addWidget(self.pd10_dateEdit)
        self.pd10_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pd10_pushButton.setObjectName(_fromUtf8("pd10_pushButton"))
        self.horizontalLayout_6.addWidget(self.pd10_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.billdate_dateEdit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.billdate_dateEdit.setCalendarPopup(True)
        self.billdate_dateEdit.setObjectName(_fromUtf8("billdate_dateEdit"))
        self.horizontalLayout_7.addWidget(self.billdate_dateEdit)
        self.billdate_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.billdate_pushButton.setObjectName(_fromUtf8("billdate_pushButton"))
        self.horizontalLayout_7.addWidget(self.billdate_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 6, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 7, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 36, 28))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chartplan_frame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.chartplan_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.chartplan_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.chartplan_frame.setObjectName(_fromUtf8("chartplan_frame"))
        self.verticalLayout_2.addWidget(self.chartplan_frame)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.addWidget(self.scrollArea_2, 0, 0, 2, 3)
        self.plan_pushButton = QtGui.QPushButton(self.tab_3)
        self.plan_pushButton.setIcon(icon)
        self.plan_pushButton.setObjectName(_fromUtf8("plan_pushButton"))
        self.gridLayout_11.addWidget(self.plan_pushButton, 0, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(82, 388, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem4, 1, 3, 2, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 0, 0, 1, 2)
        self.xraypl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.xraypl_lineEdit.setMaxLength(56)
        self.xraypl_lineEdit.setObjectName(_fromUtf8("xraypl_lineEdit"))
        self.gridLayout_9.addWidget(self.xraypl_lineEdit, 0, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_9.addWidget(self.label_23, 1, 0, 1, 2)
        self.periopl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.periopl_lineEdit.setMaxLength(56)
        self.periopl_lineEdit.setObjectName(_fromUtf8("periopl_lineEdit"))
        self.gridLayout_9.addWidget(self.periopl_lineEdit, 1, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab_3)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_9.addWidget(self.label_47, 2, 0, 1, 2)
        self.anaespl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.anaespl_lineEdit.setMaxLength(56)
        self.anaespl_lineEdit.setObjectName(_fromUtf8("anaespl_lineEdit"))
        self.gridLayout_9.addWidget(self.anaespl_lineEdit, 2, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.tab_3)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_9.addWidget(self.label_48, 3, 0, 1, 2)
        self.otherpl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.otherpl_lineEdit.setMaxLength(56)
        self.otherpl_lineEdit.setObjectName(_fromUtf8("otherpl_lineEdit"))
        self.gridLayout_9.addWidget(self.otherpl_lineEdit, 3, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.tab_3)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_9.addWidget(self.label_49, 4, 0, 1, 2)
        self.custompl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.custompl_lineEdit.setMaxLength(56)
        self.custompl_lineEdit.setObjectName(_fromUtf8("custompl_lineEdit"))
        self.gridLayout_9.addWidget(self.custompl_lineEdit, 4, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_11.addWidget(self.line_2, 2, 1, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_51 = QtGui.QLabel(self.tab_3)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_10.addWidget(self.label_51, 0, 0, 1, 3)
        self.label_52 = QtGui.QLabel(self.tab_3)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_10.addWidget(self.label_52, 1, 0, 1, 2)
        self.label_53 = QtGui.QLabel(self.tab_3)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_10.addWidget(self.label_53, 2, 0, 1, 2)
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_10.addWidget(self.line, 3, 0, 1, 3)
        self.label_54 = QtGui.QLabel(self.tab_3)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_10.addWidget(self.label_54, 4, 0, 1, 2)
        self.odupl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.odupl_lineEdit.setMaxLength(56)
        self.odupl_lineEdit.setObjectName(_fromUtf8("odupl_lineEdit"))
        self.gridLayout_10.addWidget(self.odupl_lineEdit, 4, 2, 1, 1)
        self.label_55 = QtGui.QLabel(self.tab_3)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_10.addWidget(self.label_55, 5, 0, 1, 2)
        self.odlpl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.odlpl_lineEdit.setMaxLength(56)
        self.odlpl_lineEdit.setObjectName(_fromUtf8("odlpl_lineEdit"))
        self.gridLayout_10.addWidget(self.odlpl_lineEdit, 5, 2, 1, 1)
        self.ndupl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.ndupl_lineEdit.setMaxLength(56)
        self.ndupl_lineEdit.setObjectName(_fromUtf8("ndupl_lineEdit"))
        self.gridLayout_10.addWidget(self.ndupl_lineEdit, 1, 2, 1, 1)
        self.ndlpl_lineEdit = QtGui.QLineEdit(self.tab_3)
        self.ndlpl_lineEdit.setMaxLength(56)
        self.ndlpl_lineEdit.setObjectName(_fromUtf8("ndlpl_lineEdit"))
        self.gridLayout_10.addWidget(self.ndlpl_lineEdit, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_4)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 461, 225))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chartcompleted_frame = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.chartcompleted_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.chartcompleted_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.chartcompleted_frame.setObjectName(_fromUtf8("chartcompleted_frame"))
        self.verticalLayout_3.addWidget(self.chartcompleted_frame)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.addWidget(self.scrollArea_3, 0, 0, 2, 3)
        self.completed_pushButton = QtGui.QPushButton(self.tab_4)
        self.completed_pushButton.setIcon(icon)
        self.completed_pushButton.setObjectName(_fromUtf8("completed_pushButton"))
        self.gridLayout_5.addWidget(self.completed_pushButton, 0, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(82, 388, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 1, 3, 2, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_12.addWidget(self.label_24, 0, 0, 1, 2)
        self.xraycmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.xraycmp_lineEdit.setMaxLength(56)
        self.xraycmp_lineEdit.setObjectName(_fromUtf8("xraycmp_lineEdit"))
        self.gridLayout_12.addWidget(self.xraycmp_lineEdit, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 1, 0, 1, 2)
        self.periocmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.periocmp_lineEdit.setMaxLength(56)
        self.periocmp_lineEdit.setObjectName(_fromUtf8("periocmp_lineEdit"))
        self.gridLayout_12.addWidget(self.periocmp_lineEdit, 1, 2, 1, 1)
        self.label_50 = QtGui.QLabel(self.tab_4)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_12.addWidget(self.label_50, 2, 0, 1, 2)
        self.anaescmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.anaescmp_lineEdit.setMaxLength(56)
        self.anaescmp_lineEdit.setObjectName(_fromUtf8("anaescmp_lineEdit"))
        self.gridLayout_12.addWidget(self.anaescmp_lineEdit, 2, 2, 1, 1)
        self.label_56 = QtGui.QLabel(self.tab_4)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_12.addWidget(self.label_56, 3, 0, 1, 2)
        self.othercmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.othercmp_lineEdit.setMaxLength(56)
        self.othercmp_lineEdit.setObjectName(_fromUtf8("othercmp_lineEdit"))
        self.gridLayout_12.addWidget(self.othercmp_lineEdit, 3, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.tab_4)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_12.addWidget(self.label_57, 4, 0, 1, 2)
        self.customcmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.customcmp_lineEdit.setMaxLength(56)
        self.customcmp_lineEdit.setObjectName(_fromUtf8("customcmp_lineEdit"))
        self.gridLayout_12.addWidget(self.customcmp_lineEdit, 4, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_12, 2, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.tab_4)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_5.addWidget(self.line_3, 2, 1, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_58 = QtGui.QLabel(self.tab_4)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_13.addWidget(self.label_58, 0, 0, 1, 3)
        self.label_59 = QtGui.QLabel(self.tab_4)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_13.addWidget(self.label_59, 1, 0, 1, 2)
        self.label_60 = QtGui.QLabel(self.tab_4)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_13.addWidget(self.label_60, 2, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.tab_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_13.addWidget(self.line_4, 3, 0, 1, 3)
        self.label_61 = QtGui.QLabel(self.tab_4)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_13.addWidget(self.label_61, 4, 0, 1, 2)
        self.oducmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.oducmp_lineEdit.setMaxLength(56)
        self.oducmp_lineEdit.setObjectName(_fromUtf8("oducmp_lineEdit"))
        self.gridLayout_13.addWidget(self.oducmp_lineEdit, 4, 2, 1, 1)
        self.label_62 = QtGui.QLabel(self.tab_4)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_13.addWidget(self.label_62, 5, 0, 1, 2)
        self.odlcmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.odlcmp_lineEdit.setMaxLength(56)
        self.odlcmp_lineEdit.setObjectName(_fromUtf8("odlcmp_lineEdit"))
        self.gridLayout_13.addWidget(self.odlcmp_lineEdit, 5, 2, 1, 1)
        self.nducmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.nducmp_lineEdit.setMaxLength(56)
        self.nducmp_lineEdit.setObjectName(_fromUtf8("nducmp_lineEdit"))
        self.gridLayout_13.addWidget(self.nducmp_lineEdit, 1, 2, 1, 1)
        self.ndlcmp_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.ndlcmp_lineEdit.setMaxLength(56)
        self.ndlcmp_lineEdit.setObjectName(_fromUtf8("ndlcmp_lineEdit"))
        self.gridLayout_13.addWidget(self.ndlcmp_lineEdit, 2, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_13, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_4.addWidget(self.label_26)
        self.hidden_notes_tableWidget = QtGui.QTableWidget(self.tab_5)
        self.hidden_notes_tableWidget.setObjectName(_fromUtf8("hidden_notes_tableWidget"))
        self.hidden_notes_tableWidget.setColumnCount(0)
        self.hidden_notes_tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.hidden_notes_tableWidget)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 2, 1)
        self.hidden_notes_pushButton = QtGui.QPushButton(self.tab_5)
        self.hidden_notes_pushButton.setIcon(icon)
        self.hidden_notes_pushButton.setObjectName(_fromUtf8("hidden_notes_pushButton"))
        self.gridLayout_6.addWidget(self.hidden_notes_pushButton, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 377, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_( u"Advanced Record Alteration"))
        self.label.setText(_( u"NHS current fees (money0)"))
        self.label_2.setText(_( u"NHS payments (money2)"))
        self.label_5.setText(_( u"NHS estimated (money4)"))
        self.label_6.setText(_( u"private estimate (money5)"))
        self.label_7.setText(_( u"Exempt - nhs gross - completed treatment (money6)"))
        self.label_8.setText(_( u"Exempt - NHS gross - estimated current (money7)"))
        self.label_9.setText(_( u"credit (money8)"))
        self.label_10.setText(_( u"debt (money9)"))
        self.label_11.setText(_( u"debt2 (money10)"))
        self.label_12.setText(_( u"money 11 (always 0!)"))
        self.label_3.setText(_( u"private current fees (money1) "))
        self.label_4.setText(_( u"private payments (money3)"))
        self.label_14.setText(_( u"ALL AMOUNTS ARE IN PENCE (cents)"))
        self.label_13.setText(_( u"Outstanding <br />amount"))
        self.total_label.setText(_( u"0.00"))
        self.money_pushButton.setText(_( u"Apply Changes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _( u"Money"))
        self.dates_pushButton.setText(_( u"Apply Changes"))
        self.label_15.setText(_( u"Last CE (pd5)"))
        self.pd5_pushButton.setText(_( u"Add Date"))
        self.label_16.setText(_( u"Last ECE (pd6)"))
        self.pd6_pushButton.setText(_( u"Add Date"))
        self.label_17.setText(_( u"Last FCA (pd7)"))
        self.pd7_pushButton.setText(_( u"Add Date"))
        self.label_18.setText(_( u"Last OPT (pd8)"))
        self.pd8_pushButton.setText(_( u"Add Date"))
        self.label_19.setText(_( u"Last intraoral Xrays (pd9)"))
        self.pd9_pushButton.setText(_( u"Add Date"))
        self.label_20.setText(_( u"Last SP (pd10)"))
        self.pd10_pushButton.setText(_( u"Add Date"))
        self.label_21.setText(_( u"Last Account sent (billdate)"))
        self.billdate_pushButton.setText(_( u"Add Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _( u"Dates"))
        self.plan_pushButton.setText(_( u"Apply Changes"))
        self.label_22.setText(_( u"Xray"))
        self.label_23.setText(_( u"Perio"))
        self.label_47.setText(_( u"anaesthetics"))
        self.label_48.setText(_( u"other"))
        self.label_49.setText(_( u"custom"))
        self.label_51.setText(_( u"Dentures"))
        self.label_52.setText(_( u"new upper"))
        self.label_53.setText(_( u"new lower"))
        self.label_54.setText(_( u"repair upper"))
        self.label_55.setText(_( u"repair lower"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _( u"Treatment Plan"))
        self.completed_pushButton.setText(_( u"Apply Changes"))
        self.label_24.setText(_( u"Xray"))
        self.label_25.setText(_( u"Perio"))
        self.label_50.setText(_( u"anaesthetics"))
        self.label_56.setText(_( u"other"))
        self.label_57.setText(_( u"custom"))
        self.label_58.setText(_( u"Dentures"))
        self.label_59.setText(_( u"new upper"))
        self.label_60.setText(_( u"new lower"))
        self.label_61.setText(_( u"repair upper"))
        self.label_62.setText(_( u"repair lower"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _( u"Completed Treatment"))
        self.label_26.setText(_( u"Hidden Notes"))
        self.hidden_notes_pushButton.setText(_( u"Apply Changes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _( u"Miscellaneous"))

from openmolar.qt4gui import resources_rc
