# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar1/src/openmolar/qt-designer/record_tools.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from gettext import gettext as _
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(497, 585)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.money_scrollArea = QtWidgets.QScrollArea(self.tab)
        self.money_scrollArea.setWidgetResizable(True)
        self.money_scrollArea.setObjectName("money_scrollArea")
        self.money_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.money_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 455, 503))
        self.money_scrollAreaWidgetContents.setObjectName("money_scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.money_scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.money0_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money0_spinBox.setMaximum(1000000)
        self.money0_spinBox.setObjectName("money0_spinBox")
        self.gridLayout.addWidget(self.money0_spinBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.money2_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money2_spinBox.setMaximum(1000000)
        self.money2_spinBox.setObjectName("money2_spinBox")
        self.gridLayout.addWidget(self.money2_spinBox, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.money4_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money4_spinBox.setMaximum(1000000)
        self.money4_spinBox.setObjectName("money4_spinBox")
        self.gridLayout.addWidget(self.money4_spinBox, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.money5_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money5_spinBox.setMaximum(1000000)
        self.money5_spinBox.setObjectName("money5_spinBox")
        self.gridLayout.addWidget(self.money5_spinBox, 8, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.money6_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money6_spinBox.setMaximum(1000000)
        self.money6_spinBox.setObjectName("money6_spinBox")
        self.gridLayout.addWidget(self.money6_spinBox, 9, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.money7_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money7_spinBox.setMaximum(1000000)
        self.money7_spinBox.setObjectName("money7_spinBox")
        self.gridLayout.addWidget(self.money7_spinBox, 10, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 11, 0, 1, 1)
        self.money8_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money8_spinBox.setMaximum(1000000)
        self.money8_spinBox.setObjectName("money8_spinBox")
        self.gridLayout.addWidget(self.money8_spinBox, 11, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 12, 0, 1, 1)
        self.money9_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money9_spinBox.setMaximum(1000000)
        self.money9_spinBox.setObjectName("money9_spinBox")
        self.gridLayout.addWidget(self.money9_spinBox, 12, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 13, 0, 1, 1)
        self.money10_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money10_spinBox.setMaximum(1000000)
        self.money10_spinBox.setObjectName("money10_spinBox")
        self.gridLayout.addWidget(self.money10_spinBox, 13, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 14, 0, 1, 1)
        self.money11_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money11_spinBox.setMaximum(1000000)
        self.money11_spinBox.setObjectName("money11_spinBox")
        self.gridLayout.addWidget(self.money11_spinBox, 14, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.money1_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money1_spinBox.setMaximum(1000000)
        self.money1_spinBox.setObjectName("money1_spinBox")
        self.gridLayout.addWidget(self.money1_spinBox, 3, 1, 1, 1)
        self.money3_spinBox = QtWidgets.QSpinBox(self.money_scrollAreaWidgetContents)
        self.money3_spinBox.setMaximum(1000000)
        self.money3_spinBox.setObjectName("money3_spinBox")
        self.gridLayout.addWidget(self.money3_spinBox, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.money_scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 2)
        self.money_scrollArea.setWidget(self.money_scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.money_scrollArea, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.total_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_label.setFont(font)
        self.total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_label.setObjectName("total_label")
        self.gridLayout_2.addWidget(self.total_label, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 455, 520))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pd5_dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.pd5_dateEdit.setCalendarPopup(True)
        self.pd5_dateEdit.setObjectName("pd5_dateEdit")
        self.horizontalLayout.addWidget(self.pd5_dateEdit)
        self.pd5_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pd5_pushButton.setObjectName("pd5_pushButton")
        self.horizontalLayout.addWidget(self.pd5_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pd6_dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.pd6_dateEdit.setCalendarPopup(True)
        self.pd6_dateEdit.setObjectName("pd6_dateEdit")
        self.horizontalLayout_2.addWidget(self.pd6_dateEdit)
        self.pd6_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pd6_pushButton.setObjectName("pd6_pushButton")
        self.horizontalLayout_2.addWidget(self.pd6_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pd7_dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.pd7_dateEdit.setCalendarPopup(True)
        self.pd7_dateEdit.setObjectName("pd7_dateEdit")
        self.horizontalLayout_3.addWidget(self.pd7_dateEdit)
        self.pd7_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pd7_pushButton.setObjectName("pd7_pushButton")
        self.horizontalLayout_3.addWidget(self.pd7_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pd8_dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.pd8_dateEdit.setCalendarPopup(True)
        self.pd8_dateEdit.setObjectName("pd8_dateEdit")
        self.horizontalLayout_4.addWidget(self.pd8_dateEdit)
        self.pd8_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pd8_pushButton.setObjectName("pd8_pushButton")
        self.horizontalLayout_4.addWidget(self.pd8_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pd9_dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.pd9_dateEdit.setCalendarPopup(True)
        self.pd9_dateEdit.setObjectName("pd9_dateEdit")
        self.horizontalLayout_5.addWidget(self.pd9_dateEdit)
        self.pd9_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pd9_pushButton.setObjectName("pd9_pushButton")
        self.horizontalLayout_5.addWidget(self.pd9_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pd10_dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.pd10_dateEdit.setCalendarPopup(True)
        self.pd10_dateEdit.setObjectName("pd10_dateEdit")
        self.horizontalLayout_6.addWidget(self.pd10_dateEdit)
        self.pd10_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pd10_pushButton.setObjectName("pd10_pushButton")
        self.horizontalLayout_6.addWidget(self.pd10_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.billdate_dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.billdate_dateEdit.setCalendarPopup(True)
        self.billdate_dateEdit.setObjectName("billdate_dateEdit")
        self.horizontalLayout_7.addWidget(self.billdate_dateEdit)
        self.billdate_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.billdate_pushButton.setObjectName("billdate_pushButton")
        self.horizontalLayout_7.addWidget(self.billdate_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 7, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.hidden_notes_tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.hidden_notes_tableWidget.setObjectName("hidden_notes_tableWidget")
        self.hidden_notes_tableWidget.setColumnCount(0)
        self.hidden_notes_tableWidget.setRowCount(0)
        self.hidden_notes_tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.hidden_notes_tableWidget)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_("Form"))
        self.label.setText(_("NHS current fees (money0)"))
        self.label_2.setText(_("NHS payments (money2)"))
        self.label_5.setText(_("NHS estimated (money4)"))
        self.label_6.setText(_("private estimate (money5)"))
        self.label_7.setText(_("Exempt - nhs gross - completed treatment (money6)"))
        self.label_8.setText(_("Exempt - NHS gross - estimated current (money7)"))
        self.label_9.setText(_("credit (money8)"))
        self.label_10.setText(_("debt (money9)"))
        self.label_11.setText(_("debt2 (money10)"))
        self.label_12.setText(_("money 11"))
        self.label_3.setText(_("private current fees (money1) "))
        self.label_4.setText(_("private payments (money3)"))
        self.label_14.setText(_("ALL AMOUNTS ARE IN PENCE (cents)"))
        self.label_13.setText(_("Outstanding amount"))
        self.total_label.setText(_("0.00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Money"))
        self.label_15.setText(_("Last CE (pd5)"))
        self.pd5_pushButton.setText(_("Add Date"))
        self.label_16.setText(_("Last ECE (pd6)"))
        self.pd6_pushButton.setText(_("Add Date"))
        self.label_17.setText(_("Last FCA (pd7)"))
        self.pd7_pushButton.setText(_("Add Date"))
        self.label_18.setText(_("Last OPT (pd8)"))
        self.pd8_pushButton.setText(_("Add Date"))
        self.label_19.setText(_("Last intraoral Xrays (pd9)"))
        self.pd9_pushButton.setText(_("Add Date"))
        self.label_20.setText(_("Last SP (pd10)"))
        self.pd10_pushButton.setText(_("Add Date"))
        self.label_21.setText(_("Last Account sent (billdate)"))
        self.billdate_pushButton.setText(_("Add Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Dates"))
        self.label_26.setText(_("Hidden Notes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _("Miscellaneous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

