# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startscreen.ui'
#
# Created: Tue Oct  6 21:47:28 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(250, 320)
        Dialog.setMinimumSize(QtCore.QSize(200, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/openmolar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.password_lineEdit = QtGui.QLineEdit(Dialog)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.password_lineEdit.setMaximumSize(QtCore.QSize(71, 16777215))
        self.password_lineEdit.setMaxLength(10)
        self.password_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.horizontalLayout.addWidget(self.password_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.user1_lineEdit = QtGui.QLineEdit(Dialog)
        self.user1_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.user1_lineEdit.setMaxLength(6)
        self.user1_lineEdit.setObjectName("user1_lineEdit")
        self.gridLayout.addWidget(self.user1_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.user2_lineEdit = QtGui.QLineEdit(Dialog)
        self.user2_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.user2_lineEdit.setMaxLength(6)
        self.user2_lineEdit.setObjectName("user2_lineEdit")
        self.gridLayout.addWidget(self.user2_lineEdit, 1, 1, 1, 1)
        self.surgery_radioButton = QtGui.QRadioButton(Dialog)
        self.surgery_radioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.surgery_radioButton.setChecked(True)
        self.surgery_radioButton.setObjectName("surgery_radioButton")
        self.gridLayout.addWidget(self.surgery_radioButton, 2, 0, 1, 2)
        self.reception_radioButton = QtGui.QRadioButton(Dialog)
        self.reception_radioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reception_radioButton.setObjectName("reception_radioButton")
        self.gridLayout.addWidget(self.reception_radioButton, 3, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.options_pushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_pushButton.sizePolicy().hasHeightForWidth())
        self.options_pushButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.options_pushButton.setIcon(icon1)
        self.options_pushButton.setObjectName("options_pushButton")
        self.verticalLayout_2.addWidget(self.options_pushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.server_comboBox = QtGui.QComboBox(self.page_2)
        self.server_comboBox.setObjectName("server_comboBox")
        self.verticalLayout.addWidget(self.server_comboBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_( u"openMolar"))
        self.label_3.setText(_( u"System Password"))
        self.label.setText(_( u"User 1(required)"))
        self.label_2.setText(_( u"User 2 (optional)"))
        self.surgery_radioButton.setText(_( u"Surgery Machine"))
        self.reception_radioButton.setText(_( u"Reception Machine"))
        self.options_pushButton.setText(_( u"Show Advanced Options"))
        self.label_4.setText(_( u"Chose a server"))

import resources_rc
