# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar1/src/openmolar/qt-designer/specify_appointment.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from gettext import gettext as _
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 404)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.apptlength_comboBox = QtWidgets.QComboBox(self.frame)
        self.apptlength_comboBox.setMaxVisibleItems(20)
        self.apptlength_comboBox.setObjectName("apptlength_comboBox")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.apptlength_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.apptlength_comboBox, 1, 1, 1, 1)
        self.practix_comboBox = QtWidgets.QComboBox(self.frame)
        self.practix_comboBox.setObjectName("practix_comboBox")
        self.gridLayout_3.addWidget(self.practix_comboBox, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.trt3_comboBox = QtWidgets.QComboBox(self.widget)
        self.trt3_comboBox.setMinimumSize(QtCore.QSize(176, 0))
        self.trt3_comboBox.setMaxVisibleItems(20)
        self.trt3_comboBox.setObjectName("trt3_comboBox")
        self.trt3_comboBox.addItem("")
        self.trt3_comboBox.setItemText(0, "")
        self.gridLayout.addWidget(self.trt3_comboBox, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.trt2_comboBox = QtWidgets.QComboBox(self.widget)
        self.trt2_comboBox.setMinimumSize(QtCore.QSize(176, 0))
        self.trt2_comboBox.setMaxVisibleItems(20)
        self.trt2_comboBox.setObjectName("trt2_comboBox")
        self.trt2_comboBox.addItem("")
        self.trt2_comboBox.setItemText(0, "")
        self.gridLayout.addWidget(self.trt2_comboBox, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.trt1_comboBox = QtWidgets.QComboBox(self.widget)
        self.trt1_comboBox.setMinimumSize(QtCore.QSize(176, 0))
        self.trt1_comboBox.setMaxVisibleItems(20)
        self.trt1_comboBox.setObjectName("trt1_comboBox")
        self.gridLayout.addWidget(self.trt1_comboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scheduleNow_pushButton = QtWidgets.QPushButton(Dialog)
        self.scheduleNow_pushButton.setObjectName("scheduleNow_pushButton")
        self.horizontalLayout_2.addWidget(self.scheduleNow_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.scheduleNow_pushButton.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_("Enter an appointment"))
        self.label.setText(_("Appointment with"))
        self.label_2.setText(_("Length"))
        self.apptlength_comboBox.setItemText(0, _("5 minutes"))
        self.apptlength_comboBox.setItemText(1, _("10 minutes"))
        self.apptlength_comboBox.setItemText(2, _("15 minutes"))
        self.apptlength_comboBox.setItemText(3, _("20 minutes"))
        self.apptlength_comboBox.setItemText(4, _("30 minutes"))
        self.apptlength_comboBox.setItemText(5, _("40 minutes"))
        self.apptlength_comboBox.setItemText(6, _("45 minutes"))
        self.apptlength_comboBox.setItemText(7, _("1 hour"))
        self.apptlength_comboBox.setItemText(8, _("1 hour 15 minutes"))
        self.apptlength_comboBox.setItemText(9, _("1 hour 20 minutes"))
        self.apptlength_comboBox.setItemText(10, _("1 hour 30 minutes"))
        self.apptlength_comboBox.setItemText(11, _("1 hour 45 minutes"))
        self.apptlength_comboBox.setItemText(12, _("2 hours"))
        self.apptlength_comboBox.setItemText(13, _("2 hours 30 minutes"))
        self.apptlength_comboBox.setItemText(14, _("3 hours"))
        self.apptlength_comboBox.setItemText(15, _("other"))
        self.label_6.setText(_("Memo (optional)"))
        self.label_4.setText(_("Reason 2"))
        self.label_5.setText(_("Reason 3"))
        self.label_3.setText(_("Reason 1"))
        self.scheduleNow_pushButton.setText(_("Schedule Now"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

