# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toothProps.ui'
#
# Created: Sat Oct  3 00:10:09 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from gettext import gettext as _

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 492)
        Form.setMinimumSize(QtCore.QSize(180, 459))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tooth_label = QtGui.QLabel(Form)
        self.tooth_label.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tooth_label.setFont(font)
        self.tooth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tooth_label.setObjectName("tooth_label")
        self.gridLayout.addWidget(self.tooth_label, 0, 0, 1, 3)
        self.clear_pushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_pushButton.sizePolicy().hasHeightForWidth())
        self.clear_pushButton.setSizePolicy(sizePolicy)
        self.clear_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.clear_pushButton.setMaximumSize(QtCore.QSize(48, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_pushButton.setIcon(icon)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout.addWidget(self.clear_pushButton, 0, 4, 1, 1)
        self.editframe = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editframe.sizePolicy().hasHeightForWidth())
        self.editframe.setSizePolicy(sizePolicy)
        self.editframe.setMinimumSize(QtCore.QSize(131, 24))
        self.editframe.setMaximumSize(QtCore.QSize(16777215, 24))
        self.editframe.setFrameShape(QtGui.QFrame.NoFrame)
        self.editframe.setFrameShadow(QtGui.QFrame.Plain)
        self.editframe.setObjectName("editframe")
        self.gridLayout.addWidget(self.editframe, 1, 0, 1, 5)
        self.comments_comboBox = QtGui.QComboBox(Form)
        self.comments_comboBox.setObjectName("comments_comboBox")
        self.comments_comboBox.addItem(QtCore.QString())
        self.comments_comboBox.setItemText(0, "")
        self.comments_comboBox.addItem(QtCore.QString())
        self.comments_comboBox.addItem(QtCore.QString())
        self.comments_comboBox.addItem(QtCore.QString())
        self.comments_comboBox.addItem(QtCore.QString())
        self.comments_comboBox.addItem(QtCore.QString())
        self.comments_comboBox.addItem(QtCore.QString())
        self.comments_comboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.comments_comboBox, 2, 0, 1, 5)
        self.frame = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(120, 100))
        self.frame.setMaximumSize(QtCore.QSize(130, 130))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 3, 0, 5, 4)
        self.am_pushButton = QtGui.QPushButton(Form)
        self.am_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.am_pushButton.setMaximumSize(QtCore.QSize(48, 28))
        self.am_pushButton.setAutoFillBackground(True)
        self.am_pushButton.setObjectName("am_pushButton")
        self.gridLayout.addWidget(self.am_pushButton, 3, 4, 1, 1)
        self.co_pushButton = QtGui.QPushButton(Form)
        self.co_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.co_pushButton.setMaximumSize(QtCore.QSize(48, 28))
        self.co_pushButton.setAutoFillBackground(True)
        self.co_pushButton.setObjectName("co_pushButton")
        self.gridLayout.addWidget(self.co_pushButton, 4, 4, 1, 1)
        self.gl_pushButton = QtGui.QPushButton(Form)
        self.gl_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.gl_pushButton.setMaximumSize(QtCore.QSize(48, 28))
        self.gl_pushButton.setAutoFillBackground(True)
        self.gl_pushButton.setObjectName("gl_pushButton")
        self.gridLayout.addWidget(self.gl_pushButton, 5, 4, 1, 1)
        self.porc_pushButton = QtGui.QPushButton(Form)
        self.porc_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.porc_pushButton.setMaximumSize(QtCore.QSize(48, 28))
        self.porc_pushButton.setAutoFillBackground(True)
        self.porc_pushButton.setObjectName("porc_pushButton")
        self.gridLayout.addWidget(self.porc_pushButton, 6, 4, 1, 1)
        self.gold_pushButton = QtGui.QPushButton(Form)
        self.gold_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.gold_pushButton.setMaximumSize(QtCore.QSize(48, 28))
        self.gold_pushButton.setAutoFillBackground(True)
        self.gold_pushButton.setObjectName("gold_pushButton")
        self.gridLayout.addWidget(self.gold_pushButton, 7, 4, 1, 1)
        self.leftTooth_pushButton = QtGui.QPushButton(Form)
        self.leftTooth_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.leftTooth_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftTooth_pushButton.setIcon(icon1)
        self.leftTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.leftTooth_pushButton.setObjectName("leftTooth_pushButton")
        self.gridLayout.addWidget(self.leftTooth_pushButton, 8, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setIconSize(QtCore.QSize(18, 24))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 1, 1, 1)
        self.rightTooth_pushButton = QtGui.QPushButton(Form)
        self.rightTooth_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.rightTooth_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTooth_pushButton.setIcon(icon2)
        self.rightTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.rightTooth_pushButton.setObjectName("rightTooth_pushButton")
        self.gridLayout.addWidget(self.rightTooth_pushButton, 8, 2, 1, 1)
        self.static_pushButton = QtGui.QPushButton(Form)
        self.static_pushButton.setMinimumSize(QtCore.QSize(48, 24))
        self.static_pushButton.setObjectName("static_pushButton")
        self.gridLayout.addWidget(self.static_pushButton, 8, 3, 1, 2)
        self.dec_pushButton = QtGui.QPushButton(Form)
        self.dec_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.dec_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.dec_pushButton.setObjectName("dec_pushButton")
        self.gridLayout.addWidget(self.dec_pushButton, 9, 0, 1, 1)
        self.at_pushButton = QtGui.QPushButton(Form)
        self.at_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.at_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.at_pushButton.setObjectName("at_pushButton")
        self.gridLayout.addWidget(self.at_pushButton, 9, 1, 1, 1)
        self.tm_pushButton = QtGui.QPushButton(Form)
        self.tm_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.tm_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.tm_pushButton.setObjectName("tm_pushButton")
        self.gridLayout.addWidget(self.tm_pushButton, 9, 2, 1, 1)
        self.plan_pushButton = QtGui.QPushButton(Form)
        self.plan_pushButton.setMinimumSize(QtCore.QSize(48, 24))
        self.plan_pushButton.setObjectName("plan_pushButton")
        self.gridLayout.addWidget(self.plan_pushButton, 9, 3, 1, 2)
        self.ex_pushButton = QtGui.QPushButton(Form)
        self.ex_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.ex_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.ex_pushButton.setObjectName("ex_pushButton")
        self.gridLayout.addWidget(self.ex_pushButton, 10, 0, 1, 1)
        self.rt_pushButton = QtGui.QPushButton(Form)
        self.rt_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.rt_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.rt_pushButton.setObjectName("rt_pushButton")
        self.gridLayout.addWidget(self.rt_pushButton, 10, 1, 1, 1)
        self.defaultCrown_pushButton = QtGui.QPushButton(Form)
        self.defaultCrown_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.defaultCrown_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.defaultCrown_pushButton.setObjectName("defaultCrown_pushButton")
        self.gridLayout.addWidget(self.defaultCrown_pushButton, 10, 2, 1, 1)
        self.comp_pushButton = QtGui.QPushButton(Form)
        self.comp_pushButton.setMinimumSize(QtCore.QSize(48, 24))
        self.comp_pushButton.setObjectName("comp_pushButton")
        self.gridLayout.addWidget(self.comp_pushButton, 10, 3, 1, 2)
        self.fs_comboBox = QtGui.QComboBox(Form)
        self.fs_comboBox.setObjectName("fs_comboBox")
        self.fs_comboBox.addItem(QtCore.QString())
        self.fs_comboBox.addItem(QtCore.QString())
        self.fs_comboBox.addItem(QtCore.QString())
        self.fs_comboBox.addItem(QtCore.QString())
        self.fs_comboBox.setItemText(3, "")
        self.gridLayout.addWidget(self.fs_comboBox, 11, 0, 1, 5)
        self.br_comboBox = QtGui.QComboBox(Form)
        self.br_comboBox.setObjectName("br_comboBox")
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.br_comboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.br_comboBox, 12, 0, 1, 5)
        self.endo_comboBox = QtGui.QComboBox(Form)
        self.endo_comboBox.setObjectName("endo_comboBox")
        self.endo_comboBox.addItem(QtCore.QString())
        self.endo_comboBox.addItem(QtCore.QString())
        self.endo_comboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.endo_comboBox, 13, 0, 1, 5)
        self.ex_comboBox = QtGui.QComboBox(Form)
        self.ex_comboBox.setObjectName("ex_comboBox")
        self.ex_comboBox.addItem(QtCore.QString())
        self.ex_comboBox.addItem(QtCore.QString())
        self.ex_comboBox.addItem(QtCore.QString())
        self.ex_comboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.ex_comboBox, 14, 0, 1, 5)
        self.static_comboBox = QtGui.QComboBox(Form)
        self.static_comboBox.setObjectName("static_comboBox")
        self.static_comboBox.addItem(QtCore.QString())
        self.static_comboBox.addItem(QtCore.QString())
        self.static_comboBox.addItem(QtCore.QString())
        self.static_comboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.static_comboBox, 15, 0, 1, 5)
        spacerItem = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_( "Form"))
        self.clear_pushButton.setToolTip(_( "delete tooth data"))
        self.comments_comboBox.setItemText(1, _( "!KUO"))
        self.comments_comboBox.setItemText(2, _( "!Mobile Tooth"))
        self.comments_comboBox.setItemText(3, _( "!Early Caries"))
        self.comments_comboBox.setItemText(4, _( "!Filling Missing"))
        self.comments_comboBox.setItemText(5, _( "!Chipped"))
        self.comments_comboBox.setItemText(6, _( "!Cracked"))
        self.comments_comboBox.setItemText(7, _( "DELETE COMMENTS"))
        self.am_pushButton.setText(_( "AM"))
        self.co_pushButton.setText(_( "CO"))
        self.gl_pushButton.setText(_( "GL"))
        self.porc_pushButton.setText(_( "Po"))
        self.gold_pushButton.setText(_( "Go"))
        self.leftTooth_pushButton.setToolTip(_( "Apply and move Back a tooth"))
        self.pushButton.setToolTip(_( "Apply & Add Another Item"))
        self.pushButton.setText(_( "&&"))
        self.rightTooth_pushButton.setToolTip(_( "Apply & Move to Next Tooth"))
        self.static_pushButton.setToolTip(_( "Toggle between static and plan"))
        self.static_pushButton.setText(_( "Static"))
        self.dec_pushButton.setToolTip(_( "toggle between deciduous and permanent tooth"))
        self.dec_pushButton.setText(_( "Dec"))
        self.at_pushButton.setToolTip(_( "denture tooth"))
        self.at_pushButton.setText(_( "AT"))
        self.tm_pushButton.setToolTip(_( "tooth missing"))
        self.tm_pushButton.setText(_( "TM"))
        self.plan_pushButton.setToolTip(_( "Toggle between static and plan"))
        self.plan_pushButton.setText(_( "Plan"))
        self.ex_pushButton.setToolTip(_( "extract (plan only!)"))
        self.ex_pushButton.setText(_( "Ex"))
        self.rt_pushButton.setToolTip(_( "root treatment"))
        self.rt_pushButton.setText(_( "RT"))
        self.defaultCrown_pushButton.setToolTip(_( "porcelain veneer"))
        self.defaultCrown_pushButton.setText(_( "Cr"))
        self.comp_pushButton.setToolTip(_( "Toggle between static and plan"))
        self.comp_pushButton.setText(_( "Comp"))
        self.fs_comboBox.setItemText(0, _( "--Fissure Sealants"))
        self.fs_comboBox.setItemText(1, _( "Fissure Sealant"))
        self.fs_comboBox.setItemText(2, _( "Fissure Sealant/Composite"))
        self.br_comboBox.setItemText(0, _( "--Bridge"))
        self.br_comboBox.setItemText(1, _( "Bonded Retainer"))
        self.br_comboBox.setItemText(2, _( "Bonded Pontic"))
        self.br_comboBox.setItemText(3, _( "Adhesive Wing"))
        self.br_comboBox.setItemText(4, _( "Lava Retainer"))
        self.br_comboBox.setItemText(5, _( "Lava Pontic"))
        self.br_comboBox.setItemText(6, _( "Gold Retainer"))
        self.br_comboBox.setItemText(7, _( "Gold Pontic"))
        self.br_comboBox.setItemText(8, _( "Other Retainer"))
        self.br_comboBox.setItemText(9, _( "Other Pontic"))
        self.endo_comboBox.setItemText(0, _( "--Endo"))
        self.endo_comboBox.setItemText(1, _( "Pulp Extirpation"))
        self.endo_comboBox.setItemText(2, _( "Root Canal"))
        self.ex_comboBox.setItemText(0, _( "--Surgical"))
        self.ex_comboBox.setItemText(1, _( "Extraction"))
        self.ex_comboBox.setItemText(2, _( "Surgical Extraction"))
        self.ex_comboBox.setItemText(3, _( "Apicectomy"))
        self.static_comboBox.setItemText(0, _( "--Static items"))
        self.static_comboBox.setItemText(1, _( "Tooth Missing"))
        self.static_comboBox.setItemText(2, _( "Denture Tooth"))
        self.static_comboBox.setItemText(3, _( "Root Present"))

import resources_rc
