# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toothPerioProps.ui'
#
# Created: Tue Oct  6 21:47:27 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(499, 148)
        Form.setMinimumSize(QtCore.QSize(0, 120))
        Form.setMaximumSize(QtCore.QSize(16777215, 517))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tooth_label = QtGui.QLabel(Form)
        self.tooth_label.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tooth_label.setFont(font)
        self.tooth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tooth_label.setObjectName("tooth_label")
        self.gridLayout.addWidget(self.tooth_label, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.comboBox, 0, 3, 1, 2)
        self.orig_frame = QtGui.QFrame(Form)
        self.orig_frame.setMinimumSize(QtCore.QSize(100, 100))
        self.orig_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.orig_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.orig_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.orig_frame.setObjectName("orig_frame")
        self.gridLayout.addWidget(self.orig_frame, 1, 0, 2, 1)
        self.new_frame = QtGui.QFrame(Form)
        self.new_frame.setMinimumSize(QtCore.QSize(100, 100))
        self.new_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.new_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.new_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.new_frame.setObjectName("new_frame")
        self.gridLayout.addWidget(self.new_frame, 1, 1, 2, 1)
        self.copy_pushButton = QtGui.QPushButton(Form)
        self.copy_pushButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.copy_pushButton.setObjectName("copy_pushButton")
        self.gridLayout.addWidget(self.copy_pushButton, 1, 2, 1, 1)
        self.cp_pushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cp_pushButton.sizePolicy().hasHeightForWidth())
        self.cp_pushButton.setSizePolicy(sizePolicy)
        self.cp_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.cp_pushButton.setMaximumSize(QtCore.QSize(40, 28))
        self.cp_pushButton.setObjectName("cp_pushButton")
        self.gridLayout.addWidget(self.cp_pushButton, 1, 3, 1, 1)
        self.clear_pushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_pushButton.sizePolicy().hasHeightForWidth())
        self.clear_pushButton.setSizePolicy(sizePolicy)
        self.clear_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.clear_pushButton.setMaximumSize(QtCore.QSize(40, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_pushButton.setIcon(icon)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout.addWidget(self.clear_pushButton, 1, 4, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftTooth_pushButton = QtGui.QPushButton(Form)
        self.leftTooth_pushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.leftTooth_pushButton.setMaximumSize(QtCore.QSize(24, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftTooth_pushButton.setIcon(icon1)
        self.leftTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.leftTooth_pushButton.setObjectName("leftTooth_pushButton")
        self.horizontalLayout.addWidget(self.leftTooth_pushButton)
        self.le_frame = QtGui.QFrame(Form)
        self.le_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.le_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.le_frame.setObjectName("le_frame")
        self.horizontalLayout.addWidget(self.le_frame)
        self.rightTooth_pushButton = QtGui.QPushButton(Form)
        self.rightTooth_pushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.rightTooth_pushButton.setMaximumSize(QtCore.QSize(24, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTooth_pushButton.setIcon(icon2)
        self.rightTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.rightTooth_pushButton.setObjectName("rightTooth_pushButton")
        self.horizontalLayout.addWidget(self.rightTooth_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 2, 1, 2)
        self.mobilitycomboBox = QtGui.QComboBox(Form)
        self.mobilitycomboBox.setMaximumSize(QtCore.QSize(16777215, 28))
        self.mobilitycomboBox.setObjectName("mobilitycomboBox")
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.mobilitycomboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.mobilitycomboBox, 2, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_( u"Form"))
        self.tooth_label.setText(_( u"ToothId"))
        self.comboBox.setItemText(0, _( u"Pocketing"))
        self.comboBox.setItemText(1, _( u"Bleeding"))
        self.comboBox.setItemText(2, _( u"Plaque"))
        self.comboBox.setItemText(3, _( u"Recession"))
        self.comboBox.setItemText(4, _( u"Furcation"))
        self.comboBox.setItemText(5, _( u"Suppuration"))
        self.comboBox.setItemText(6, _( u"Mobility"))
        self.comboBox.setItemText(7, _( u"Other"))
        self.copy_pushButton.setText(_( u"Copy &All"))
        self.cp_pushButton.setToolTip(_( u"delete tooth data"))
        self.cp_pushButton.setText(_( u"Cp"))
        self.clear_pushButton.setToolTip(_( u"delete tooth data"))
        self.leftTooth_pushButton.setToolTip(_( u"Apply and move Back a tooth"))
        self.rightTooth_pushButton.setToolTip(_( u"Apply & Move to Next Tooth"))
        self.mobilitycomboBox.setItemText(0, _( u"-"))
        self.mobilitycomboBox.setItemText(1, _( u"I"))
        self.mobilitycomboBox.setItemText(2, _( u"II"))
        self.mobilitycomboBox.setItemText(3, _( u"III"))

import resources_rc
