# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toothProps.ui'
#
# Created: Thu Nov 19 21:47:05 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(180, 479)
        Form.setMinimumSize(QtCore.QSize(180, 459))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_pushButton = QtGui.QPushButton(Form)
        self.edit_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.edit_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_pushButton.setIcon(icon)
        self.edit_pushButton.setFlat(True)
        self.edit_pushButton.setObjectName("edit_pushButton")
        self.horizontalLayout.addWidget(self.edit_pushButton)
        self.tooth_label = QtGui.QLabel(Form)
        self.tooth_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tooth_label.setFont(font)
        self.tooth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tooth_label.setObjectName("tooth_label")
        self.horizontalLayout.addWidget(self.tooth_label)
        self.clear_pushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_pushButton.sizePolicy().hasHeightForWidth())
        self.clear_pushButton.setSizePolicy(sizePolicy)
        self.clear_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.clear_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_pushButton.setIcon(icon1)
        self.clear_pushButton.setFlat(True)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.horizontalLayout.addWidget(self.clear_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.editframe = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editframe.sizePolicy().hasHeightForWidth())
        self.editframe.setSizePolicy(sizePolicy)
        self.editframe.setMinimumSize(QtCore.QSize(131, 24))
        self.editframe.setMaximumSize(QtCore.QSize(16777215, 24))
        self.editframe.setFrameShape(QtGui.QFrame.NoFrame)
        self.editframe.setFrameShadow(QtGui.QFrame.Plain)
        self.editframe.setObjectName("editframe")
        self.verticalLayout.addWidget(self.editframe)
        self.comments_comboBox = QtGui.QComboBox(Form)
        self.comments_comboBox.setObjectName("comments_comboBox")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.comments_comboBox.addItem("")
        self.verticalLayout.addWidget(self.comments_comboBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(120, 100))
        self.frame.setMaximumSize(QtCore.QSize(130, 130))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 5, 1)
        self.am_pushButton = QtGui.QPushButton(Form)
        self.am_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.am_pushButton.setMaximumSize(QtCore.QSize(48, 24))
        self.am_pushButton.setAutoFillBackground(True)
        self.am_pushButton.setObjectName("am_pushButton")
        self.gridLayout.addWidget(self.am_pushButton, 0, 1, 1, 1)
        self.co_pushButton = QtGui.QPushButton(Form)
        self.co_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.co_pushButton.setMaximumSize(QtCore.QSize(48, 24))
        self.co_pushButton.setAutoFillBackground(True)
        self.co_pushButton.setObjectName("co_pushButton")
        self.gridLayout.addWidget(self.co_pushButton, 1, 1, 1, 1)
        self.gl_pushButton = QtGui.QPushButton(Form)
        self.gl_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.gl_pushButton.setMaximumSize(QtCore.QSize(48, 24))
        self.gl_pushButton.setAutoFillBackground(True)
        self.gl_pushButton.setObjectName("gl_pushButton")
        self.gridLayout.addWidget(self.gl_pushButton, 2, 1, 1, 1)
        self.porc_pushButton = QtGui.QPushButton(Form)
        self.porc_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.porc_pushButton.setMaximumSize(QtCore.QSize(48, 24))
        self.porc_pushButton.setAutoFillBackground(True)
        self.porc_pushButton.setObjectName("porc_pushButton")
        self.gridLayout.addWidget(self.porc_pushButton, 3, 1, 1, 1)
        self.gold_pushButton = QtGui.QPushButton(Form)
        self.gold_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.gold_pushButton.setMaximumSize(QtCore.QSize(48, 24))
        self.gold_pushButton.setAutoFillBackground(True)
        self.gold_pushButton.setObjectName("gold_pushButton")
        self.gridLayout.addWidget(self.gold_pushButton, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.leftTooth_pushButton = QtGui.QPushButton(Form)
        self.leftTooth_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.leftTooth_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftTooth_pushButton.setIcon(icon2)
        self.leftTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.leftTooth_pushButton.setFlat(True)
        self.leftTooth_pushButton.setObjectName("leftTooth_pushButton")
        self.gridLayout_2.addWidget(self.leftTooth_pushButton, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setIconSize(QtCore.QSize(18, 24))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.rightTooth_pushButton = QtGui.QPushButton(Form)
        self.rightTooth_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.rightTooth_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightTooth_pushButton.setIcon(icon3)
        self.rightTooth_pushButton.setIconSize(QtCore.QSize(24, 18))
        self.rightTooth_pushButton.setFlat(True)
        self.rightTooth_pushButton.setObjectName("rightTooth_pushButton")
        self.gridLayout_2.addWidget(self.rightTooth_pushButton, 0, 2, 1, 1)
        self.static_pushButton = QtGui.QPushButton(Form)
        self.static_pushButton.setMinimumSize(QtCore.QSize(48, 24))
        self.static_pushButton.setObjectName("static_pushButton")
        self.gridLayout_2.addWidget(self.static_pushButton, 0, 3, 1, 1)
        self.dec_pushButton = QtGui.QPushButton(Form)
        self.dec_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.dec_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.dec_pushButton.setObjectName("dec_pushButton")
        self.gridLayout_2.addWidget(self.dec_pushButton, 1, 0, 1, 1)
        self.at_pushButton = QtGui.QPushButton(Form)
        self.at_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.at_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.at_pushButton.setObjectName("at_pushButton")
        self.gridLayout_2.addWidget(self.at_pushButton, 1, 1, 1, 1)
        self.tm_pushButton = QtGui.QPushButton(Form)
        self.tm_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.tm_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.tm_pushButton.setObjectName("tm_pushButton")
        self.gridLayout_2.addWidget(self.tm_pushButton, 1, 2, 1, 1)
        self.plan_pushButton = QtGui.QPushButton(Form)
        self.plan_pushButton.setMinimumSize(QtCore.QSize(48, 24))
        self.plan_pushButton.setObjectName("plan_pushButton")
        self.gridLayout_2.addWidget(self.plan_pushButton, 1, 3, 1, 1)
        self.ex_pushButton = QtGui.QPushButton(Form)
        self.ex_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.ex_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.ex_pushButton.setObjectName("ex_pushButton")
        self.gridLayout_2.addWidget(self.ex_pushButton, 2, 0, 1, 1)
        self.rt_pushButton = QtGui.QPushButton(Form)
        self.rt_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.rt_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.rt_pushButton.setObjectName("rt_pushButton")
        self.gridLayout_2.addWidget(self.rt_pushButton, 2, 1, 1, 1)
        self.defaultCrown_pushButton = QtGui.QPushButton(Form)
        self.defaultCrown_pushButton.setMinimumSize(QtCore.QSize(32, 24))
        self.defaultCrown_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.defaultCrown_pushButton.setObjectName("defaultCrown_pushButton")
        self.gridLayout_2.addWidget(self.defaultCrown_pushButton, 2, 2, 1, 1)
        self.comp_pushButton = QtGui.QPushButton(Form)
        self.comp_pushButton.setMinimumSize(QtCore.QSize(48, 24))
        self.comp_pushButton.setObjectName("comp_pushButton")
        self.gridLayout_2.addWidget(self.comp_pushButton, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.cb_scrollArea = QtGui.QScrollArea(Form)
        self.cb_scrollArea.setMinimumSize(QtCore.QSize(0, 140))
        self.cb_scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cb_scrollArea.setWidgetResizable(True)
        self.cb_scrollArea.setObjectName("cb_scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.cb_scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 174, 140))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.cb_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.cb_scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_( u"Form"))
        self.clear_pushButton.setToolTip(_( u"delete tooth data"))
        self.comments_comboBox.setItemText(0, _( u"ADD COMMENTS"))
        self.comments_comboBox.setItemText(1, _( u"!KUO"))
        self.comments_comboBox.setItemText(2, _( u"!Mobile Tooth"))
        self.comments_comboBox.setItemText(3, _( u"!Early Caries"))
        self.comments_comboBox.setItemText(4, _( u"!Filling Missing"))
        self.comments_comboBox.setItemText(5, _( u"!Chipped"))
        self.comments_comboBox.setItemText(6, _( u"!Cracked"))
        self.comments_comboBox.setItemText(7, _( u"!Poor Prognosis"))
        self.comments_comboBox.setItemText(8, _( u"!Extract Soon"))
        self.comments_comboBox.setItemText(9, _( u"!Implant required"))
        self.comments_comboBox.setItemText(10, _( u"DELETE COMMENTS"))
        self.am_pushButton.setText(_( u"AM"))
        self.co_pushButton.setText(_( u"CO"))
        self.gl_pushButton.setText(_( u"GL"))
        self.porc_pushButton.setText(_( u"Po"))
        self.gold_pushButton.setText(_( u"Go"))
        self.leftTooth_pushButton.setToolTip(_( u"Apply and move Back a tooth"))
        self.pushButton.setToolTip(_( u"Apply & Add Another Item"))
        self.pushButton.setText(_( u"&&"))
        self.rightTooth_pushButton.setToolTip(_( u"Apply & Move to Next Tooth"))
        self.static_pushButton.setToolTip(_( u"Toggle between static and plan"))
        self.static_pushButton.setText(_( u"Static"))
        self.dec_pushButton.setToolTip(_( u"toggle between deciduous and permanent tooth"))
        self.dec_pushButton.setText(_( u"Dec"))
        self.at_pushButton.setToolTip(_( u"denture tooth"))
        self.at_pushButton.setText(_( u"AT"))
        self.tm_pushButton.setToolTip(_( u"tooth missing"))
        self.tm_pushButton.setText(_( u"TM"))
        self.plan_pushButton.setToolTip(_( u"Toggle between static and plan"))
        self.plan_pushButton.setText(_( u"Plan"))
        self.ex_pushButton.setToolTip(_( u"extract (plan only!)"))
        self.ex_pushButton.setText(_( u"Ex"))
        self.rt_pushButton.setToolTip(_( u"root treatment"))
        self.rt_pushButton.setText(_( u"RT"))
        self.defaultCrown_pushButton.setToolTip(_( u"porcelain veneer"))
        self.defaultCrown_pushButton.setText(_( u"Cr"))
        self.comp_pushButton.setToolTip(_( u"Toggle between static and plan"))
        self.comp_pushButton.setText(_( u"Comp"))

import resources_rc
