# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/neil/openmolar/openmolar/qt-designer/newSetup.ui'
#
# Created: Sat May  2 23:49:17 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 232)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtGui.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.page)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_2 = QtGui.QGridLayout(self.page_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainPassword_label = QtGui.QLabel(self.page_1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.mainPassword_label.setFont(font)
        self.mainPassword_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mainPassword_label.setWordWrap(True)
        self.mainPassword_label.setObjectName("mainPassword_label")
        self.gridLayout_2.addWidget(self.mainPassword_label, 0, 0, 1, 4)
        self.label_5 = QtGui.QLabel(self.page_1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.main_password_lineEdit = QtGui.QLineEdit(self.page_1)
        self.main_password_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.main_password_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.main_password_lineEdit.setObjectName("main_password_lineEdit")
        self.gridLayout_2.addWidget(self.main_password_lineEdit, 1, 1, 1, 2)
        self.mainpassword_checkBox = QtGui.QCheckBox(self.page_1)
        self.mainpassword_checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mainpassword_checkBox.setObjectName("mainpassword_checkBox")
        self.gridLayout_2.addWidget(self.mainpassword_checkBox, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 82, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.page_1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(115, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtGui.QLabel(self.page_6)
        self.label_13.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 3)
        self.ping_pushButton = QtGui.QPushButton(self.page_6)
        self.ping_pushButton.setObjectName("ping_pushButton")
        self.gridLayout_3.addWidget(self.ping_pushButton, 3, 0, 1, 3)
        self.host_lineEdit = QtGui.QLineEdit(self.page_6)
        self.host_lineEdit.setEnabled(True)
        self.host_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.host_lineEdit.setObjectName("host_lineEdit")
        self.gridLayout_3.addWidget(self.host_lineEdit, 1, 1, 1, 2)
        self.port_lineEdit = QtGui.QLineEdit(self.page_6)
        self.port_lineEdit.setEnabled(True)
        self.port_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.gridLayout_3.addWidget(self.port_lineEdit, 2, 1, 1, 2)
        self.label_14 = QtGui.QLabel(self.page_6)
        self.label_14.setEnabled(True)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.page_6)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 5, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(214, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(103, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 4, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.page_6)
        self.label_12.setEnabled(True)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_4 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtGui.QSpacerItem(20, 52, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_5)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 2)
        self.createDB_pushButton = QtGui.QPushButton(self.page_5)
        self.createDB_pushButton.setObjectName("createDB_pushButton")
        self.gridLayout_4.addWidget(self.createDB_pushButton, 2, 0, 1, 1)
        self.haveDB_pushButton = QtGui.QPushButton(self.page_5)
        self.haveDB_pushButton.setObjectName("haveDB_pushButton")
        self.gridLayout_4.addWidget(self.haveDB_pushButton, 2, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 52, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout = QtGui.QGridLayout(self.page_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.page_4)
        self.label_9.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 3)
        self.label_4 = QtGui.QLabel(self.page_4)
        self.label_4.setEnabled(True)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.database_lineEdit = QtGui.QLineEdit(self.page_4)
        self.database_lineEdit.setEnabled(True)
        self.database_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.database_lineEdit.setObjectName("database_lineEdit")
        self.gridLayout.addWidget(self.database_lineEdit, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_4)
        self.label_2.setEnabled(True)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.user_lineEdit = QtGui.QLineEdit(self.page_4)
        self.user_lineEdit.setEnabled(True)
        self.user_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.gridLayout.addWidget(self.user_lineEdit, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_4)
        self.label_3.setEnabled(True)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.password_lineEdit = QtGui.QLineEdit(self.page_4)
        self.password_lineEdit.setEnabled(True)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.password_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 3, 1, 1, 1)
        self.dbpassword_checkBox = QtGui.QCheckBox(self.page_4)
        self.dbpassword_checkBox.setEnabled(True)
        self.dbpassword_checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dbpassword_checkBox.setObjectName("dbpassword_checkBox")
        self.gridLayout.addWidget(self.dbpassword_checkBox, 3, 2, 1, 1)
        self.testDB_pushButton = QtGui.QPushButton(self.page_4)
        self.testDB_pushButton.setObjectName("testDB_pushButton")
        self.gridLayout.addWidget(self.testDB_pushButton, 4, 0, 1, 3)
        spacerItem6 = QtGui.QSpacerItem(97, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 5, 1, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.page_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 5, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtGui.QLabel(self.page_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.saveQuit_pushButton = QtGui.QPushButton(self.page_3)
        self.saveQuit_pushButton.setObjectName("saveQuit_pushButton")
        self.gridLayout_6.addWidget(self.saveQuit_pushButton, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.main_password_lineEdit, QtCore.SIGNAL("returnPressed()"), self.pushButton_2.click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton, self.main_password_lineEdit)
        Dialog.setTabOrder(self.main_password_lineEdit, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.host_lineEdit)
        Dialog.setTabOrder(self.host_lineEdit, self.port_lineEdit)
        Dialog.setTabOrder(self.port_lineEdit, self.ping_pushButton)
        Dialog.setTabOrder(self.ping_pushButton, self.haveDB_pushButton)
        Dialog.setTabOrder(self.haveDB_pushButton, self.createDB_pushButton)
        Dialog.setTabOrder(self.createDB_pushButton, self.pushButton_9)
        Dialog.setTabOrder(self.pushButton_9, self.database_lineEdit)
        Dialog.setTabOrder(self.database_lineEdit, self.user_lineEdit)
        Dialog.setTabOrder(self.user_lineEdit, self.password_lineEdit)
        Dialog.setTabOrder(self.password_lineEdit, self.dbpassword_checkBox)
        Dialog.setTabOrder(self.dbpassword_checkBox, self.testDB_pushButton)
        Dialog.setTabOrder(self.testDB_pushButton, self.saveQuit_pushButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "First Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "This Appears to be the first time you have run OpenMolar on this computer. \n"
"You need to enter some information before we can proceed.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.mainPassword_label.setText(QtGui.QApplication.translate("Dialog", "Please enter a password to prevent unauthorised running of this application.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.mainpassword_checkBox.setText(QtGui.QApplication.translate("Dialog", "show password", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Where is your mysql server located?", None, QtGui.QApplication.UnicodeUTF8))
        self.ping_pushButton.setText(QtGui.QApplication.translate("Dialog", "Test for Available Server", None, QtGui.QApplication.UnicodeUTF8))
        self.host_lineEdit.setText(QtGui.QApplication.translate("Dialog", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.port_lineEdit.setText(QtGui.QApplication.translate("Dialog", "3306", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Would you like to create a demo openmolar database now?", None, QtGui.QApplication.UnicodeUTF8))
        self.createDB_pushButton.setText(QtGui.QApplication.translate("Dialog", "Yes please", None, QtGui.QApplication.UnicodeUTF8))
        self.haveDB_pushButton.setText(QtGui.QApplication.translate("Dialog", "No, I have a database already.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Please enter a mysql user who has privileges for the openmolar database.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Database Name", None, QtGui.QApplication.UnicodeUTF8))
        self.database_lineEdit.setText(QtGui.QApplication.translate("Dialog", "openmolar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.user_lineEdit.setText(QtGui.QApplication.translate("Dialog", "user", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.password_lineEdit.setText(QtGui.QApplication.translate("Dialog", "password", None, QtGui.QApplication.UnicodeUTF8))
        self.dbpassword_checkBox.setText(QtGui.QApplication.translate("Dialog", "display password", None, QtGui.QApplication.UnicodeUTF8))
        self.testDB_pushButton.setText(QtGui.QApplication.translate("Dialog", "Test connection to this database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "OK.... you are all set to go.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveQuit_pushButton.setText(QtGui.QApplication.translate("Dialog", "Save settings and launch openmolar", None, QtGui.QApplication.UnicodeUTF8))

