# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openmolar/openmolar/qt4gui_layouts/specify_appointment.ui'
#
# Created: Thu Mar  5 10:49:54 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(593, 351)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtGui.QSpacerItem(81, 56, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.practix_comboBox = QtGui.QComboBox(Dialog)
        self.practix_comboBox.setObjectName("practix_comboBox")
        self.gridLayout_3.addWidget(self.practix_comboBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.apptlength_comboBox = QtGui.QComboBox(Dialog)
        self.apptlength_comboBox.setMaxVisibleItems(20)
        self.apptlength_comboBox.setObjectName("apptlength_comboBox")
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.apptlength_comboBox.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.apptlength_comboBox, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 2, 2)
        self.combinedApptcheckBox = QtGui.QCheckBox(Dialog)
        self.combinedApptcheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.combinedApptcheckBox.setObjectName("combinedApptcheckBox")
        self.gridLayout_2.addWidget(self.combinedApptcheckBox, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(55, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.trt1_comboBox = QtGui.QComboBox(Dialog)
        self.trt1_comboBox.setMinimumSize(QtCore.QSize(176, 0))
        self.trt1_comboBox.setMaxVisibleItems(20)
        self.trt1_comboBox.setObjectName("trt1_comboBox")
        self.gridLayout.addWidget(self.trt1_comboBox, 1, 0, 1, 1)
        self.trt2_comboBox = QtGui.QComboBox(Dialog)
        self.trt2_comboBox.setMinimumSize(QtCore.QSize(176, 0))
        self.trt2_comboBox.setMaxVisibleItems(20)
        self.trt2_comboBox.setObjectName("trt2_comboBox")
        self.trt2_comboBox.addItem(QtCore.QString())
        self.trt2_comboBox.setItemText(0, "")
        self.gridLayout.addWidget(self.trt2_comboBox, 1, 1, 1, 1)
        self.trt3_comboBox = QtGui.QComboBox(Dialog)
        self.trt3_comboBox.setMinimumSize(QtCore.QSize(176, 0))
        self.trt3_comboBox.setMaxVisibleItems(20)
        self.trt3_comboBox.setObjectName("trt3_comboBox")
        self.trt3_comboBox.addItem(QtCore.QString())
        self.trt3_comboBox.setItemText(0, "")
        self.gridLayout.addWidget(self.trt3_comboBox, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 4)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 3, 0, 1, 4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(181, 16777215))
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 0, 1, 4)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 5, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scheduleNow_pushButton = QtGui.QPushButton(Dialog)
        self.scheduleNow_pushButton.setObjectName("scheduleNow_pushButton")
        self.horizontalLayout_2.addWidget(self.scheduleNow_pushButton)
        spacerItem2 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 6, 0, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.scheduleNow_pushButton, QtCore.SIGNAL("clicked()"), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Enter an appointment", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Appointment with", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "5 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "10 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "15 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "20 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "30 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "40 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(6, QtGui.QApplication.translate("Dialog", "45 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(7, QtGui.QApplication.translate("Dialog", "1 hour", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(8, QtGui.QApplication.translate("Dialog", "1 hour 15 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(9, QtGui.QApplication.translate("Dialog", "1 hour 20 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(10, QtGui.QApplication.translate("Dialog", "1 hour 30 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(11, QtGui.QApplication.translate("Dialog", "1 hour 45 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(12, QtGui.QApplication.translate("Dialog", "2 hours", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(13, QtGui.QApplication.translate("Dialog", "2 hours 30 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(14, QtGui.QApplication.translate("Dialog", "3 hours", None, QtGui.QApplication.UnicodeUTF8))
        self.apptlength_comboBox.setItemText(15, QtGui.QApplication.translate("Dialog", "other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Combined Appointment with Hygenist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Reason 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Reason 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Reason 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Brief Note for Clinician (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.scheduleNow_pushButton.setText(QtGui.QApplication.translate("Dialog", "Schedule Appointment Now", None, QtGui.QApplication.UnicodeUTF8))

