# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openmolar/openmolar/qt-designer/medhist.ui'
#
# Created: Wed Mar 25 09:43:11 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(864, 500)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 500))
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.doctor_lineEdit = QtGui.QLineEdit(Dialog)
        self.doctor_lineEdit.setMaxLength(60)
        self.doctor_lineEdit.setObjectName("doctor_lineEdit")
        self.gridLayout_2.addWidget(self.doctor_lineEdit, 0, 2, 1, 3)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.doctorAddy_lineEdit = QtGui.QLineEdit(Dialog)
        self.doctorAddy_lineEdit.setMaxLength(60)
        self.doctorAddy_lineEdit.setObjectName("doctorAddy_lineEdit")
        self.gridLayout_2.addWidget(self.doctorAddy_lineEdit, 1, 2, 1, 3)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.curMeds_lineEdit = QtGui.QLineEdit(Dialog)
        self.curMeds_lineEdit.setMaxLength(60)
        self.curMeds_lineEdit.setObjectName("curMeds_lineEdit")
        self.gridLayout_2.addWidget(self.curMeds_lineEdit, 2, 2, 1, 3)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.pastMeds_lineEdit = QtGui.QLineEdit(Dialog)
        self.pastMeds_lineEdit.setMaxLength(60)
        self.pastMeds_lineEdit.setObjectName("pastMeds_lineEdit")
        self.gridLayout_2.addWidget(self.pastMeds_lineEdit, 3, 2, 1, 3)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 2)
        self.allergies_lineEdit = QtGui.QLineEdit(Dialog)
        self.allergies_lineEdit.setMaxLength(60)
        self.allergies_lineEdit.setObjectName("allergies_lineEdit")
        self.gridLayout_2.addWidget(self.allergies_lineEdit, 4, 2, 1, 3)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.heart_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.heart_lineEdit.setMaxLength(60)
        self.heart_lineEdit.setObjectName("heart_lineEdit")
        self.gridLayout.addWidget(self.heart_lineEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.lungs_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lungs_lineEdit.setMaxLength(60)
        self.lungs_lineEdit.setObjectName("lungs_lineEdit")
        self.gridLayout.addWidget(self.lungs_lineEdit, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.liver_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.liver_lineEdit.setMaxLength(60)
        self.liver_lineEdit.setObjectName("liver_lineEdit")
        self.gridLayout.addWidget(self.liver_lineEdit, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.bleeding_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.bleeding_lineEdit.setMaxLength(60)
        self.bleeding_lineEdit.setObjectName("bleeding_lineEdit")
        self.gridLayout.addWidget(self.bleeding_lineEdit, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.kidneys_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.kidneys_lineEdit.setMaxLength(60)
        self.kidneys_lineEdit.setObjectName("kidneys_lineEdit")
        self.gridLayout.addWidget(self.kidneys_lineEdit, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.anaesthetic_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.anaesthetic_lineEdit.setMaxLength(60)
        self.anaesthetic_lineEdit.setObjectName("anaesthetic_lineEdit")
        self.gridLayout.addWidget(self.anaesthetic_lineEdit, 5, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.other_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.other_lineEdit.setMaxLength(60)
        self.other_lineEdit.setObjectName("other_lineEdit")
        self.gridLayout.addWidget(self.other_lineEdit, 6, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 5, 0, 1, 5)
        self.history_pushButton = QtGui.QPushButton(Dialog)
        self.history_pushButton.setObjectName("history_pushButton")
        self.gridLayout_2.addWidget(self.history_pushButton, 6, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 6, 1, 1, 1)
        self.checked_pushButton = QtGui.QPushButton(Dialog)
        self.checked_pushButton.setObjectName("checked_pushButton")
        self.gridLayout_2.addWidget(self.checked_pushButton, 6, 2, 1, 1)
        self.label_13 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 6, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Medical Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Doctor\'s Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Address / Tel No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Current Medication", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Past Medication", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Allergies (*turns MH button red*)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Known Conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Heart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Lungs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Liver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Bleeding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Kidneys", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Anaesthetic / operations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.history_pushButton.setText(QtGui.QApplication.translate("Dialog", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.checked_pushButton.setText(QtGui.QApplication.translate("Dialog", "Mark as Checked Today", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "openMolar can\'t update MH yet!", None, QtGui.QApplication.UnicodeUTF8))

